### ISSUE TITLE
How to correctly pass HTTP headers

### ISSUE THREAD

**Issue by mattcollum** [getsentry/sentry-go#10]
In raven-go if you pass the headers using raven.Http like so:

headersMap := make(map[string]string)

// add headers
...

raven.SetHttpContext(&raven.Http{
    Method: "GET",
    URL: "https://example.com/raven-go",
   Headers: headersMap,
})

Sentry and/or Raven-Go client infers lots of useful info such as device, browser, os, etc for each event.  Using the migration guide here I'm not seeing a clear way to do this and have the same info appear.  Is this possible with the new client?

**Comment by kamilogorek** [comment]
https://github.com/getsentry/sentry-go/blob/master/MIGRATION.md#globally

```go
headersMap := make(map[string]string)
headersMap["some"] = "header"

sentry.ConfigureScope(func(scope *sentry.Scope) {
    scope.SetContext("Request", map[string]interface{}{
        "Method": "GET",
        "URL": "https://example.com/raven-go",
        "Headers": headersMap,
    })
})
```

This will set the appropriate context (see docs here: https://docs.sentry.io/development/sdk-dev/interfaces/#http-interface) and our UI will read it just fine.

Also right now it's not necessary to have those headers for device, browser or os. We extract it ourselves.

Here's the output of default config + scope configuration from the above:

![image](https://user-images.githubusercontent.com/1523305/58425445-1492e180-809a-11e9-9abf-da70fbae21b9.png)

Cheers!

**Comment by mattcollum** [comment]
Thanks for the prompt replies to both my questions!

So I had tried this originally and wasn't seeing the results I expected.  Went back to this approach and am still not seeing parity with what we used to get.  Some gaps:

- Top level view in Sentry shows 'go Version: go1.12' and 'Unknown Device Arch: amd64'.  With the same test data previously it shows 'Mobile Safari Version: 10.0' and 'iPhone'

- Scrolling down previously the Request section has the URL as a clickable link, options to show Formatted or Curl.  New view shows it as 'REQUEST (Request)' with none of the other options.  



- 

-

**Comment by kamilogorek** [comment]
@mattcollum got it, thanks for the detailed write-up! I'll get it fixed first thing in the morning.

**Comment by mattcollum** [comment]
Amazing thanks!

**Comment by mattcollum** [comment]
Just to help your fix/debugging.  I ended up switching to use the CaptureEvent and all the data seems to be appearing in the UI properly.  Perhaps just something with CaptureException that isn't mapping properly

**Comment by kamilogorek** [comment]
@mattcollum the main issue was that we had no access to the request object itself in scenario other than recovering from panic, as it was attached to the context. It's now changed and request lives on the scope (using context as I showed above will indeed present slightly differently in the UI than using top-level `request` key).

I introduced `SetRequest` and `Request{}.FromHTTPRequest(req)` method so it's easier to work with. Can you give it a try?

Relevant commits:
https://github.com/getsentry/sentry-go/commit/f22ac281d5395cb664ac95e485031692c6bebd41 
https://github.com/getsentry/sentry-go/commit/2bb693075636d9c0e506411d0236f6feb2e2986c
https://github.com/getsentry/sentry-go/commit/184080f6bcc1df749424fae2e9e9fe4315c84879
https://github.com/getsentry/sentry-go/commit/ae7f25b4881fb1b0fa585420cdc3929ffca65b41

**Comment by mattcollum** [comment]
We're using CaptureEvent directly, mainly so I can generate my own stacktraces at the time of the error.  Maybe not ideal but seems to get the data across in the way we need it

**Comment by kamilogorek** [comment]
Got it. Can this issue be closed then? Also thanks for using the beta version, it really helps to get everything ironed out! :)

**Comment by mattcollum** [comment]
Absolutely and happy to help!
