### ISSUE TITLE
Support showing path of file in stacktraces

### ISSUE THREAD

**Issue by fho** [getsentry/sentry-go#101]
raven-go supports the `SetIncludePaths` (https://github.com/getsentry/raven-go/blob/5c24d5110e0e198d9ae16f1f3465366085001d92/client.go#L937) option to show paths of the file in stacktraces.

It would be great if sentry-go would also allow to show absolute or GOPATH relative paths to the source codefiles in the stacktrace.

This can be especially helpful when a stacktrace contains the same sourcecode filename from different packages.

**Comment by kamilogorek** [comment]
`IncludePaths` is used to mark some of the frames in the stacktrace as coming from the app instead of 3rd party module. It doesn't modify the paths at all, see: https://github.com/getsentry/raven-go/blob/5c24d5110e0e198d9ae16f1f3465366085001d92/stacktrace.go#L176-L186

**Comment by fho** [comment]
@kamilogorek thanks, you are right, `SetIncludePaths` seems not related.

Is there a way to show the full path the source code file in the stacktraces instead of only the filenames?

**Comment by kamilogorek** [comment]
@fho we already does that. When you go to `sentry-go/example/basic` and run it `go run main.go` you'll see that the exception has all the data, including absolute path of a frame:

![image](https://user-images.githubusercontent.com/1523305/70053692-40a59700-15d6-11ea-8648-525c009389b7.png)

Is this not the case for you? Can you provide a link to an event that's missing this data?

**Comment by fho** [comment]
I figured out that only the representation in the UI changed.
The full-paths are still there:

With raven-go I had full-paths in the stacktrace and no mouseover, like:
![image](https://user-images.githubusercontent.com/514535/70054708-587e1a80-15d8-11ea-99d9-351e20e7bbbc.png)

--------------------

With sentry-go the full-path show up as mouse-over text in the stacktrace:
![new](https://user-images.githubusercontent.com/514535/70055018-f7a31200-15d8-11ea-89d7-6682fd49fda1.png)



Sorry for the effort and thanks for the help!

**Comment by kamilogorek** [comment]
No worries, glad you found what you needed :) Cheers!
