### ISSUE TITLE
Improve documentation of sentry.Flush

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/sentry-go#106]
The documentation in https://godoc.org/github.com/getsentry/sentry-go#Flush could be more specific to help users understand when `Flush` needs to be called, if at all.

Similarly, the example code in https://docs.sentry.io/platforms/go/ can be improved to follow the same line.

Typically `Flush` should only be called once from the main goroutine when a program is terminating.

---

Subtasks:

- [x] Update README.md -- #152
- [x] Update documentation in https://godoc.org/github.com/getsentry/sentry-go#Flush -- #153
- [x] Update example in https://docs.sentry.io/platforms/go/ -- https://github.com/getsentry/sentry-docs/pull/1482

**Comment by rhcarvalho** [comment]
Tracking issue to help users understand better how to use the SDK and avoid cases like https://github.com/getsentry/sentry-go/issues/103#issuecomment-561379867
> I've been using flush on every error I wanted to send to Sentry

**Comment by mmacheerpuppy** [comment]
Thanks @rhcarvalho I think this line in the example code is where I derived the confusion

```
	if err != nil {
		sentry.CaptureException(err)
		sentry.Flush(time.Second * 5)
	}
```

**Comment by rhcarvalho** [comment]
I randomly run into this code looking at Reddit r/golang today: [gist-cleaner/backend/main.go#L312-L317](https://github.com/NdoleStudio/gist-cleaner/blob/74a98f01dd4afc447ace1c620d6f0a53df39f7dc/backend/main.go#L312-L317)

The usage of `time.Second * 5` (more commonly written as `5 * time.Second`) matches the docs in https://docs.sentry.io/platforms/go/#usage and reinforces the importance of clarifying the docs.

I plan to solve this in the coming weeks by implementing `sentry.Close` (#111) and improving the docs (this issue). Both improvements should land in [v0.5.0](https://github.com/getsentry/sentry-go/milestone/1).

**Comment by rhcarvalho** [comment]
@mmacheerpuppy @BonnieMilian I acknowledge you might be busy.

Given that you both ran into #103, I'd like to share that I've rewritten the example code and usage steps documented in the README.md of the Sentry Go SDK.

I would appreciate feedback if you have any! The changes are live here: https://github.com/rhcarvalho/sentry-go/blob/readme/README.md#usage

Hope to clear out any confusion with regards to `sentry.Flush`.

Thanks a lot!

**Comment by mmacheerpuppy** [comment]
@rhcarvalho Not a prbolem, is there a deadline on this PR? I can certainly find room for this this week!

**Comment by rhcarvalho** [comment]
@mmacheerpuppy certainly not a deadline for you ;)
If we end up merging before you comment, we'd have no problems amending to it as a follow up.

Thanks :heart:

**Comment by rhcarvalho** [comment]
Documentation updates landed at

- https://docs.sentry.io/platforms/go/;
- https://github.com/getsentry/sentry-go/blob/master/README.md#usage; and
- https://godoc.org/github.com/getsentry/sentry-go#Flush.

Considering this resolved. If anyone finds the updates unsatisfactory, please comment here or file a new issue and we'll iterate on it.
