### ISSUE TITLE
No stacktrace in UI when panics are sent

### ISSUE THREAD

**Issue by mattcollum** [getsentry/sentry-go#11]
Generated a panic and it was sent to sentry via Recover.  I see a bit of info here but no stacktrace, without which it's quite tough of course to determine the source/cause of the issue

**Comment by kamilogorek** [comment]
If you panic with `error` instance, it should work just fine (`panic(errors.New("Sorry with error :("))` vs. `panic("Sorry with message :(")`)

![image](https://user-images.githubusercontent.com/1523305/58488851-6b67ec00-816a-11e9-8f42-32f92cc232fb.png)

**Comment by mattcollum** [comment]
Tried with an error and am seeing the trace.   Would it be possible to generate a stacktrace for panic("string") as well as a lot of base Go packages and other libs use that approach.  eg. https://github.com/golang/go/blob/master/src/strings/strings.go

**Comment by kamilogorek** [comment]
> Would it be possible to generate a stacktrace for panic("string") as well as a lot of base Go packages and other libs use that approach

Yes, I'll implement this Today. We even have it in our other SDKs :)

**Comment by kamilogorek** [comment]
@mattcollum done. It's inlined with the rest of our SDKs and you should be able to turn it on with: ```go
sentry.Init(sentry.ClientOptions{
  AttachStacktrace: true,
})
```

Related commit: https://github.com/getsentry/sentry-go/commit/bd9b8f581f5b5ca2b7376f6fef0d179808ebe11c

**Comment by mattcollum** [comment]
Does this apply just to panics or all messages?

**Comment by kamilogorek** [comment]
All events created out of string input, so both `CaptureMessage("something")` and `panic("something")`

**Comment by mattcollum** [comment]
Seeing these from local env so think we're safe to close.  Thx for the quick turnaround!
