### ISSUE TITLE
Is it possible to read source code from release files?

### ISSUE THREAD

**Issue by hulucc** [getsentry/sentry-go#118]
I don't want to put the source code into the docker image.
So I wondering is there a way I could upload the source code bundle to sentry, and sentry will pickup it to show stacktrace context ?

**Comment by kamilogorek** [comment]
There are two parts to this question. One is reading function names, file paths and location of an error and one is reading surrounding source code.

The first one will happen automatically if your binaries are not stripped of debug information (compiled without `-s -w` flags), however, the second part requires the source code to be there.

Unfortunately, debug information (either in non-striped binary, or inside DWARF file) contains only information about the frame itself, like function name, arguments etc., but it has no concept of the source code like for example source maps in JS does.

**Comment by hulucc** [comment]
Thank u for the reply.

**Comment by rhcarvalho** [comment]
> So I wondering is there a way I could upload the source code bundle to sentry, and sentry will pickup it to show stacktrace context ?

For anyone landing here, server-side source context is being tracked in https://github.com/getsentry/sentry-go/issues/177.
