### ISSUE TITLE
Stacktraces are empty in AWS Lambda

### ISSUE THREAD

**Issue by mattcollum** [getsentry/sentry-go#12]
Using the following code in an AWS Lambda running the Go 1.x image (Amazon Linux) the generated output is empty:

`stacktrace := sentry.NewStacktrace()`

Running the same command on a Mac dev machine returns the expected stack.

**Comment by kamilogorek** [comment]
Fixed in https://github.com/getsentry/sentry-go/commit/18c90128b8582641e330b23394ed9a68f1586026

Tested manually on AWS and works fine now!
![image](https://user-images.githubusercontent.com/1523305/58633152-ec002700-82e7-11e9-86d2-f6bcf98c8c24.png)

Can you please confirm?

**Comment by kamilogorek** [comment]
There are no breaking changes for now, but if you want to feel "safer", I'll release `beta.2` tomorrow morning :)

**Comment by mattcollum** [comment]
Works for me!

**Comment by kamilogorek** [comment]
@mattcollum https://github.com/getsentry/sentry-go/releases/tag/v0.0.1-beta.2

**Comment by mattcollum** [comment]
Trying to test this and not seeing any events at all in Sentry anymore from lambdas. Did something change with flush?   And what's the best approach to using that to ensure all messages make it out before the function ends?

**Comment by mattcollum** [comment]
Upped the time on Flush to 1 second and am seeing events again.  Can see stacktraces but they are missing the code snippets that I see when sending from local tests.  Any way to include those?  Getting closer!

**Comment by kamilogorek** [comment]
@mattcollum it's not possible to extract source files from binaries, as symbol resolutions in go allow to read lines and function names only.

However, we can kinda work around it: https://github.com/getsentry/sentry-go/commit/5d6d24943a90e128155f888e4d82897103f5379b

In order to get the context right, you need to bundle your source code with the binary, eg.

```sh
GOOS=linux go build main.go && zip handler.zip ./main ./main.go ./other.go ./sources.go
```

However, it'll only work if all the files are within the root directory, as we resolve it based on the filename and making it more flexible would require a lot of changes right now (we'll definitely make them if there'll be a huge need for that.

**Comment by mattcollum** [comment]
Right that makes total sense. Thanks for the tip, I'll play around with this and see if its worth it for us.

**Comment by mattcollum** [comment]
@kamilogorek So was thinking of trying this out and wanted to ensure I read this right.  For this to work we need to flatten out the source code into a single directory and then zip it alongside the go binary?  We have files with the same name in different packages so thinking this might be an issue unfortunately

**Comment by kamilogorek** [comment]
@mattcollum I agree that it's not ideal, and that's why I'll update how it works this week so you won't have to flatten it anymore. I'll keep you posted.

**Comment by mattcollum** [comment]
Awesome as always, thx @kamilogorek

**Comment by kamilogorek** [comment]
@mattcollum aaand it's released. Update to `0.1.2` and deploy your lambdas with source code included, that's all. Directory structure doesn't matter anymore, so you can even push the whole thing up there.

```
$ GOOS=linux go build main.go && zip -r handler.zip *
```

**Comment by mattcollum** [comment]
nice!

so the goal here is instead of a straight Go binary that we deploy to lambda, we upload a zip containing the binary and the source code?  we're using serverless so need to weave this into our build/deploy process properly

**Comment by kamilogorek** [comment]
Correct. There's, unfortunately, no easy way to make it work other than providing source code directly in Go.

**Comment by kamilogorek** [comment]
Working example:

![image](https://user-images.githubusercontent.com/1523305/60979498-1efbf880-a333-11e9-99a7-10679798c10b.png)

**Comment by mattcollum** [comment]
nice.  trying it now and will lyk

**Comment by mattcollum** [comment]
Does it matter how closely it matches your model?  I've got the following in zip

-srcdir1
-srcdir2
-srcdirn
-functions/functionDir/main.go
-bin/app

Zip deploys fine and the Lambda runs but just seeing regular stacktraces with no source.  Could it be the fact I've got the binary in a bin dir as opposed to at the root of the zip?  Is there another setting I need when initializing Sentry maybe that I missed from earlier chats?

**Comment by kamilogorek** [comment]
@mattcollum it's kinda more complex structure, as what I do right now is that I'm looking for the main frame, assume (blindly) that it's living in the root directory of the project and then try to extract path prefix from it.
I have a better idea now though, so will try to implement it soon.

**Comment by mattcollum** [comment]
Got it.  Not pressing so schedule as you see fit but let me know when I should try again

**Comment by kamilogorek** [comment]
@mattcollum it's done on master. Can you give it a try without a new release? It should read the file content now without any additional config, even with the structure like yours.

There's now also a way to opt-out of this feature if someone doesn't want to have it (eg. for a possible performance boost, as it has to perform I/O operation).

```go
sentry.Init(sentry.ClientOptions{
	Integrations: func(integrations []sentry.Integration) []sentry.Integration {
		var filteredIntegrations []sentry.Integration
		for _, integration := range integrations {
			if integration.Name() == "ContextifyFrames" {
				continue
			}
			filteredIntegrations = append(filteredIntegrations, integration)
		}
		return filteredIntegrations
	},
})
```

**Comment by mattcollum** [comment]
Let there be stacktraces!  Nice work :)

**Comment by kamilogorek** [comment]
Woohoo! Will release `0.1.3` now then :) Thanks for a quick turnaround!

**Comment by mattcollum** [comment]
Likewise :)
