### ISSUE TITLE
Make isInAppFrame customizable by clients

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/sentry-go#136]
There's a cockroachdb fork that implements a custom `isInAppFrame` function and makes it customizable.

Such level of customization should be provided upstream.

Reference: https://github.com/cockroachdb/sentry-go/commit/2061d6c803c44899e4d3e2d3c6ac70d329587513

**Comment by cleptric** [comment]
Duplicate of https://github.com/getsentry/sentry-go/issues/124
