### ISSUE TITLE
Remove AddGlobalEventProcessor and globalEventProcessors

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/sentry-go#147]
I propose removing the undocumented exported function `AddGlobalEventProcessor` together with the unexported global value it operates on `globalEventProcessors`.

https://github.com/getsentry/sentry-go/blob/763dc7f49323f467d4c62ec15804723ec5350b37/client.go#L28-L32

## Rationale

All _Event Processors_ that ship with the SDK are wrapped as an _Integration_ and are attached to a `Client`. Namely:

- contextifyFramesIntegration: adds context to stacktrace frames
- environmentIntegration: adds environment information to events
- modulesIntegration: adds modules list to events
- ignoreErrorsIntegration: filters out errors that match ClientOptions.IgnoreErrors

This is in agreement with our decision to instead of exposing EventProcessors in the SDKs to hide them behind an Integration. The reason for this was that users don't have to deal with EventProcessors themselves, they only need to enable/disable Integrations.

I have checked 169 of the [public packages that import sentry-go](https://pkg.go.dev/github.com/getsentry/sentry-go?tab=importedby) and none uses `AddGlobalEventProcessor`.

After removing `AddGlobalEventProcessor`, the same effect can be obtained with `Scope.AddEventProcessor` or `Client.AddEventProcessor`.

Note that an EventProcessor may still have its own global state if it desires so.

Pros:

- Smaller API surface for a future v1.
- Less global state.
- Less room for concurrency issues (data races): `AddGlobalEventProcessor` must not be called from multiple goroutines concurrently.
- API easier to be composed/wrapped (there are users trying to do that, see [example](https://bitbucket.org/netwide/common/src/4cba93c9600e8710c2485157f67b061448d1e137/notifier.go?at=master#lines-69:86)).

Cons:

- Potentially breaking closed-source users, however those have a very easy replacement.

**Comment by rhcarvalho** [comment]
@kamilogorek @bruno-garcia @HazAT for comments, if any.

**Comment by bruno-garcia** [comment]
I'd like to see this change land.

**Comment by kamilogorek** [comment]
Sounds good to me. I followed the implementation of JS SDK to the T at first, thus why some parts might be unnecessary now.
