### ISSUE TITLE
Update multiple client example by adding a call to `flush`

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/sentry-go#155]
We need a clear example of how to use multiple clients and how to properly Flush events upon program termination.

---

See https://github.com/getsentry/sentry-go/pull/153#issuecomment-580000855

>> IMHO User only knows about `Sentry.flush` and worst case `SentryClient.flush` if they are working with the client directly (outside the SDK.init/Hub)
>
> I wish this was simpler too.
>
> If there is only ever one client, then `sentry.Flush` does the job.
> If new clients are created, then more `Flush` calls need to be sprinkled around for correctness. We need a clear example for this usage.

**Comment by rhcarvalho** [comment]
Oh, it's already there! https://github.com/getsentry/sentry-go/blob/master/example/multiclient/main.go

Good job @kamilogorek!

---

Need to update the example to call Flush.

**Comment by kamilogorek** [comment]
Thanks, tried my best :)
