### ISSUE TITLE
When can we expect a stable release?

### ISSUE THREAD

**Issue by harshilsharma63** [getsentry/sentry-go#16]
When can we expect a stable release?

**Comment by kamilogorek** [comment]
Working on it as we speak, docs are already done, just need to setup few devops things. Either tomorrow or Thursday :)

**Comment by harshilsharma63** [comment]
@kamilogorek awesome!

**Comment by kamilogorek** [comment]
*First stable release v0.1 is live!* 🎉 

- GitHub Repository: https://github.com/getsentry/sentry-go  (with brand new readme and raven-go migration note)
- https://github.com/getsentry/raven-go deprecation warning added
- New docs: https://docs.sentry.io/platforms/go/
- Old raven-go docs: https://docs.sentry.io/clients/go/
- Migration guide: https://docs.sentry.io/platforms/go/migration/
