### ISSUE TITLE
Add TODOs Badge to README

### ISSUE THREAD

**Issue by patrickdevivo** [getsentry/sentry-go#162]
Hi there! I wanted to propose adding the following badge to the README to indicate how many `TODO` comments are in this codebase:

[![TODOs](https://img.shields.io/endpoint?url=https://api.tickgit.com/badge?repo=github.com/getsentry/sentry-go)](https://www.tickgit.com/browse?repo=github.com/getsentry/sentry-go)

The badge links to `tickgit.com` which is a free service that indexes and displays TODO comments in public github repos. It can help surface latent work and be a way for contributors to find areas of code to improve, that might not be otherwise documented.

The markdown is:

```
[![TODOs](https://img.shields.io/endpoint?url=https://api.tickgit.com/badge?repo=github.com/getsentry/sentry-go)](https://www.tickgit.com/browse?repo=github.com/getsentry/sentry-go)
```

Thanks for considering, feel free to close this issue if it's not appropriate or you prefer not to!

**Comment by rhcarvalho** [comment]
Thank you! Good experiment, unfortunately I don't see use within sentry-go at the moment. We use GitHub issues to track work.

---

The badge is not rendering for me and following the link takes minutes to load just partially:

![image](https://user-images.githubusercontent.com/88819/74651732-c3290600-5184-11ea-8fa0-b3ff98da07a2.png)

**Comment by patrickdevivo** [comment]
Hi @rhcarvalho thanks for considering! I'm sorry the badge didn't seem to render, it appears to be finicky for me as well. Unfortunately, it seems the shields.io service used to produce it can be a bit slow at times (and time out), I'm looking to find a more reliable alternative (likely https://badgen.net/).

Thank you for posting the screenshot as well, it looks like you saw slow behavior on the app page, I apologize for that. I'm investigating why and likely bumping some of the underlying infrastructure. Thanks for the response!
