### ISSUE TITLE
Pull request #94 causes http.ErrBodyReadAfterClose

### ISSUE THREAD

**Issue by lagren** [getsentry/sentry-go#166]
I have experienced a bug that is mentioned by @faulkner in #94 (https://github.com/getsentry/sentry-go/pull/94/files#r373130154)

> This introduces a new bug. If `ioutil.ReadAll` returns an error the body is left in a closed state, so reading the body later results in a `http.ErrBodyReadAfterClose`, so instead of the original error getting sent to Sentry you end up just getting `http: invalid Read on closed Body` with no way of knowing what the original error was.

According to a follow-up comment, this would be addressed in #117. But that issue was closed without any code changes and I don't see any other issues opened to keep track of this bug.

**Comment by rhcarvalho** [comment]
@lagren I have a WIP that will address that (this) and #96.

**Comment by rhcarvalho** [comment]
@lagren could you please try with master?

I'm planning to cut v0.6.0 soon.
