### ISSUE TITLE
Document / add example using github.com/rotisserie/eris

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/sentry-go#173]
https://github.com/rotisserie/eris is an alternative to https://github.com/pkg/errors and https://github.com/golang/xerrors, should work out of the box with Sentry.

They have an example app to report errors with Sentry.

**Comment by ribice** [comment]
This works out of the box. `eris` errors implement both `Unwrap` and `Cause` methods.

We [check whether an error implements Unwrap](https://github.com/getsentry/sentry-go/blob/master/interfaces.go#L355), and if so get the unwrapped one.

![Image](https://github.com/user-attachments/assets/e5ae4861-456b-4438-9183-825988f7f126)

cc @cleptric

**Comment by cleptric** [comment]
Worth adding to https://docs.sentry.io/platforms/go/usage/#capturing-errors.

**Comment by ribice** [comment]
> Worth adding to https://docs.sentry.io/platforms/go/usage/#capturing-errors.

https://github.com/getsentry/sentry-docs/pull/12199
