### ISSUE TITLE
Transport customization

### ISSUE THREAD

**Issue by claytono** [getsentry/sentry-go#178]
We're currently using `raven-go` and looking into what's required to switch over to `sentry-go`.  One of the issues we've identified is the change in behavior on 429 responses.  In order to limit changes in behavior, we're looking at using the `HTTPSyncTransport`.  This transport appears to drop all exceptions that are received if it is in the retry-after window provided by the API, or one minute if the API doesn't provide that data.

We'd like to be able to customize this behavior.  At a minimum we want to report back metrics to our internal systems if we're dropping exceptions due to rate limiting.  I suspect the default retry-after behavior is not a good fit for us in general, since we funnel a large number of our internal exceptions through a centralized service, and dropping all exceptions for one minute when a single request is rate limited is probably not the right behavior for us.

The obvious route would be to provide our own transport that implements the behavior we desire.  This is something we can do, but there is some non-transport related logic in this package that is package private that we'd prefer to not duplicate.  The biggest one here seems to be `getRequestBodyFromEvent`. 

I'm curious what approach you'd recommend here?  Should we just fork HTTPSyncTransport?

**Comment by rhcarvalho** [comment]
Hi @claytono and sorry for the delay.

> One of the issues we've identified is the change in behavior on 429 responses.

Would you be so kind and elaborate on this?

> dropping all exceptions for one minute when a single request is rate limited is probably not the right behavior for us

Note that rate limiting is not for single requests, but for several reasons the server may refuse a request.
Ignoring the 429 and insisting on sending requests just generates more traffic.

You may be interested and perhaps contribute with discussion in https://github.com/getsentry/sentry-go/issues/171. I have a proposal to have the SDK shape the outgoing traffic to avoid the type of situation you might be considering yourself in. If that's the case, I'd welcome your validation of the idea.

> there is some non-transport related logic in this package that is package private that we'd prefer to not duplicate. The biggest one here seems to be `getRequestBodyFromEvent`.

Okay, I think this we can fix. On a quick look, I think `getRequestBodyFromEvent` should really be a method on Event `Event.MarshalJSON`. That would allow anybody downstream to serialize events with the same logic.

**Comment by rhcarvalho** [comment]
> On a quick look, I think `getRequestBodyFromEvent` should really be a method on Event `Event.MarshalJSON`. That would allow anybody downstream to serialize events with the same logic.

Looked at this again.

`getRequestBodyFromEvent` is basically "try to encode the event as JSON; if it doesn't work, strip out some fields (breadcrumbs, contexts and extra) and try again".

Implementing `Event.MarshalJSON` in terms of `getRequestBodyFromEvent` naively is not an option because we want to marshal using the default implementation of struct encoding from `encoding/json`, what would require at least some extra allocation and copying to avoid infinite mutual recursion.

I'd like to understand the problem better before introducing a new helper in the exported API.
