### ISSUE TITLE
Stacktrace for functions from "go.*" will have incorrect package name 

### ISSUE THREAD

**Issue by Pr0Ger** [getsentry/sentry-go#180]
https://github.com/getsentry/sentry-go/blob/4dddaaad5cc53f38de4928e98126dfbabd315423/stacktrace.go#L257-L262

This code as exptected will ignore parsing for functions which name starts from "go" however this is sometimes a valid package name. For example [zap](https://pkg.go.dev/go.uber.org/zap) library: `go.uber.org/zap/zapcore.(*CheckedEntry).Write` will not properly extract `go.uber.org/zap/zapcore` as a package name.

Since this code is copied from `debug/gosym` I filled same issue for original code https://github.com/golang/go/issues/37762

**Comment by rhcarvalho** [comment]
@Pr0Ger thanks for reporting here and upstream. I'll monitor what will happen upstream before we make changes here.
