### ISSUE TITLE
List of packages include "replace" package

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/sentry-go#184]
Among packages from `go.mod`, package list is also showing a `replace` entry, looks wrong:

![image](https://user-images.githubusercontent.com/88819/77349263-0ace1f00-6d3b-11ea-9a6e-b05cb3a5fb87.png)

Here's the code that needs improvement:

https://github.com/getsentry/sentry-go/blob/a0f55ee0c7108aef71a7cb94e7c82edafdb0ab83/integrations.go#L70-L104

**Comment by wingyplus** [comment]
Is it easy if we use `golang.org/x/mod` to parse mod file. I prototype an example below: 

```
package main

import (
	"fmt"
	"log"

	"golang.org/x/mod/modfile"
)

func main() {
	mod := []byte(`module git.linecorp.com/lineman/sentry-exp

go 1.14

require (
	github.com/getsentry/sentry-go v0.0.0
	github.com/gin-gonic/gin v1.6.2
)

replace github.com/getsentry/sentry-go v0.0.0 => ./pkg/sentry-go
`)
	f, err := modfile.Parse("go.mod", mod, nil)
	if err != nil {
		log.Fatal(err)
	}

	for _, req := range f.Require {
		fmt.Println(req.Mod.Path, req.Mod.Version)
	}
}
```

**Comment by wingyplus** [comment]
I prototype it using `golang.org/x/mod` module:

```
package main

import (
	"fmt"
	"log"

	"golang.org/x/mod/modfile"
)

func main() {
	mod := []byte(`module github.com/wingyplus/sentry-exp

go 1.14

require (
	github.com/getsentry/sentry-go v0.0.0
	github.com/gin-gonic/gin v1.6.2
)

replace github.com/getsentry/sentry-go v0.0.0 => ./pkg/sentry-go
`)
	f, err := modfile.Parse("go.mod", mod, nil)
	if err != nil {
		log.Fatal(err)
	}

	for _, req := range f.Require {
		fmt.Println(req.Mod.Path, req.Mod.Version)
	}
}
```

**Comment by rhcarvalho** [comment]
FTR for binaries built in Module Mode, there is https://golang.org/pkg/runtime/debug/#BuildInfo.
No dependencies required.

**Comment by wingyplus** [comment]
@rhcarvalho Nice! it's works!

**Comment by wingyplus** [comment]
@rhcarvalho I opened PR to fix this problem. It's good to see your feedback. :)
