### ISSUE TITLE
Operating System version is undefined when sentry issue come from darwin or linux  os

### ISSUE THREAD

**Issue by wingyplus** [getsentry/sentry-go#187]
I found an issue that version for darwin os will be `undefined` (see picture below): 

![Screen Shot 2563-04-03 at 15 33 55](https://user-images.githubusercontent.com/484530/78340694-b63f6500-75c0-11ea-8dde-744a2dfb0bbf.png)

Not sure for another os.

**Comment by wingyplus** [comment]
More information: 

go  v1.14 darwin/amd64
github.com/getsentry/sentry-go v0.5.1

**Comment by wingyplus** [comment]
Linux is undefined also: 

![Screen Shot 2563-04-03 at 15 45 24](https://user-images.githubusercontent.com/484530/78341637-3adeb300-75c2-11ea-89b8-708b1bbc2c70.png)

**Comment by wingyplus** [comment]
I think if we want  to do, we can fork it from raven-ruby context https://github.com/getsentry/raven-ruby/blob/master/lib/raven/context.rb#L27

**Comment by rhcarvalho** [comment]
@wingyplus thanks for reporting and proposing a PR. Indeed we currently only send the OS name, for all platforms.

https://github.com/getsentry/sentry-go/blob/87c79e35bd71d9d636dfcd51172766fd2ff53e08/integrations.go#L188-L190

**Comment by wingyplus** [comment]
@rhcavalho I see. The main issue will be version of os is undefined on sentry because the library didn’t send os version to the server.

**Comment by rhcarvalho** [comment]
Not all SDKs actually send the OS information. Is it the "undefined" that is bothering you, or do you have a use case that needs the OS version?

For the `"undefined"`, I think that's something to fix in the Sentry UI. I found these related issues:

- https://github.com/getsentry/sentry/issues/3968
- https://github.com/getsentry/sentry/issues/6830 (this is for Device Model, but in the end of the day is a similar problem)

**Comment by wingyplus** [comment]
@rhcarvalho it’s just bothering me that it’s always undefined. No use case specific at the moment.

**Comment by rhcarvalho** [comment]
@wingyplus are you running Sentry on-premise or using the hosted product at [sentry.io](https://sentry.io)?

This is from a recent event I have in sentry.io:

![image](https://user-images.githubusercontent.com/88819/78689653-dcce0a80-78f6-11ea-85d0-62639b095bdc.png)


If you are on-prem, you may need to update.

**Comment by wingyplus** [comment]
@rhcarvalho I use sentry on-premise. It's version 9.1.2 as I know.

**Comment by rhcarvalho** [comment]
I suspect it changed in https://github.com/getsentry/sentry/commit/a78bec2a6add01cdd96692227a3fb0f1408dab54.

**Comment by rhcarvalho** [comment]
As a stopgap solution, you can do something like this to replace "undefined" with a blank:

```go
func main() {
	err := sentry.Init(sentry.ClientOptions{
		BeforeSend: func(event *sentry.Event, hint *sentry.EventHint) *sentry.Event {
			if m, ok := event.Contexts["os"].(map[string]interface{}); ok && m["version"] == nil {
				m["version"] = " "
			}
			return event
		},
	})
	// ...
}
```

Definitely a hack. Gives this:

![image](https://user-images.githubusercontent.com/88819/78770290-a512a180-798e-11ea-9c39-226c0c6974af.png)


You can also use that same mechanism to actually fetch the OS version (using a syscall or whatever else).

Note that if you always run your Go program in a controlled environment there is little or no benefit to reporting OS version.

**Comment by rhcarvalho** [comment]
I'll reword the issue tittle and we can keep it open to track adding OS version, though I find it to be low priority. Happy to hear feedback from users.

**Comment by priscilawebdev** [comment]
@wingyplus thanks for the feedback @rhcarvalho thanks for checking this

We no longer display Version if it is undefined. The PR responsible for it was https://github.com/getsentry/sentry/pull/17239 

As Rodolfo suggested, you can use `"   "` to display the version without displaying `undefined`, but I would not recommend it. Please, is it important for you to display the Version property without a value?

**Comment by wingyplus** [comment]
@priscilawebdev I don't want to set version by myself and I think the sdk should do this job for us.
