### ISSUE TITLE
Sending timestamps including milliseconds

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/sentry-go#190]
> I didn't read through this thread in detail, but I came here searching for an issue where my millisecond and nanosecond breadcrumb timestamps (formated as a Unix timestamp integer with millis or nanos added) are being rejected by the Sentry API (regular Unix timestamps in seconds work as expected).
> 
> After verifying that my timestamps are correct, my mind drifted towards clock skew, which was how I found this issue.
> 
> Here's what the API injected into the raw JSON:
> 
> ```json
>   "_meta": {
>     "breadcrumbs": {
>       "values": {
>         "0": {
>           "timestamp": {
>             "": {
>               "val": 1585983484747,
>               "err": [
>                 [
>                   "invalid_data",
>                   {
>                     "reason": "timestamp out of range"
>                   }
>                 ]
>               ]
>             }
>           }
>         }
>       }
>     }
>   }
> ```
> 
> If this isn't related, I'll file a separate issue (assuming I'm not doing anything incorrectly).
> 
> This is using the Go SDK.

_Originally posted by @JeanMertz in https://github.com/getsentry/relay/issues/534#issuecomment-608990645_

**Comment by rhcarvalho** [comment]
The server only understands seconds when the timestamp is a numeric value. The value can be a float to include milliseconds, but note that [`float64` cannot represent nanoseconds since several decades ago](https://www.python.org/dev/peps/pep-0564/#float-type-limited-to-104-days).

The Go SDK at the moment represents timestamps as `int64` values, making it impossible to have anything other than seconds. That's a bug.

**Comment by JeanMertz** [comment]
Thank you for tracking this here and creating a fix @rhcarvalho. Much appreciated.
