### ISSUE TITLE
let event processors set contexts

### ISSUE THREAD

**Issue by gawen** [getsentry/sentry-go#193]
Currently, the SDK overwrites context keys `runtime`, `os`, `device` in the environment integration. Event processors are unable to set custom values.

Proposed PR https://github.com/getsentry/sentry-go/pull/186 did a quick fix, but does not work if all contexts are not `map[string]interface{}` (which they are in `v0.5.1`).

One idea would be to set values in the event's context as structure with the context fields as described in the [Context interface event payload documentation](https://docs.sentry.io/development/sdk-dev/event-payloads/contexts/).

```go
type ContextDevice struct {
    name string  `json:"name"`
    family string  `json:"name,omitempty"`
    ...
}

...

event.Contexts.Device = &ContextDevice{...}
event.Contexts.Os = &ContextOs{...}

// extra custom contextes?
event.Contexts.Map["foo"] = 42
```

**Comment by rhcarvalho** [comment]
@gawen not sure if we talked about it before, could you enlighten me on what you are trying to achieve?

Some background story would help me understand the root problem, not just the superficial fix.

Perhaps there's more than "do not overwrite contexts in integration".

How did you decide to write custom event processors?
Are you adding event processors to the client, scope or global?

Did you consider using `BeforeSend` too?

**Comment by gawen** [comment]
> @gawen not sure if we talked about it before, could you enlighten me on what you are trying to achieve?

We're setting an `sentry.EventProcessor` to add some `app`, `device` and `os` context to our Sentry events following the [event payload documentation](https://docs.sentry.io/development/sdk-dev/event-payloads/contexts/).

> How did you decide to write custom event processors?

We're running Go on mobile and needs to set specific metadata to our app and the system.

> Are you adding event processors to the client, scope or global?

Global.

> Did you consider using `BeforeSend` too?

No we didn't. We felt the event processor interface was the right one.
