### ISSUE TITLE
Report more Operating System details such as OS version

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/sentry-go#195]
Currently the SDK reports the Operating System type taken from `runtime.GOOS`. It could report more OS details such as version.

The use cases:

- programs that are distributed to end users and report errors back
- programs that run on heterogeneous environments (a generalization of the above, but also e.g. a web server running on different types of VMs)

_(Extracted from #187)_

**Comment by wingyplus** [comment]
gathering os information from uname syscall is enough?

**Comment by rhcarvalho** [comment]
> gathering os information from uname syscall is enough?

I believe for Linux/macOS we can read from https://godoc.org/golang.org/x/sys/unix#Utsname
And for Windows from https://godoc.org/golang.org/x/sys/windows#OsVersionInfoEx

Haven't tested, but seems your PR is in a good direction 👍

**Comment by wingyplus** [comment]
Regarding to my PR, it’s already using Utsname that’s require by Uname.

On Windows, I’m not familiar yet about os syscall but it’s sound interesting to try.

**Comment by tylerd-canva** [comment]
You can use [build constraints](https://pkg.go.dev/go/build#hdr-Build_Constraints) on test files to run different tests on different OSs. Of course, you then need to run your tests on different OSs so in this case it might be better to just have a few tests with the syscall mocked out.
