### ISSUE TITLE
Make SSL Certificate Verification Optional

### ISSUE THREAD

**Issue by ArcticSnowman** [getsentry/sentry-go#2]
The current raven-go has a major flaw for on-prem hosting of Sentry.  In an enterprise situation, the  Sentry is likely to be behind an internally signed SSL certificate.  As raven-go using the https://github.com/certifi/gocertifi as it's ONLY source of CA certs, it would refuse to talk to the Sentry.

Please make sure that this new package supports disabling of SSL certificate verification.  And optionally allow CA certificate to be read from the root.

**Comment by kamilogorek** [comment]
@ArcticSnowman I'll make sure it's working as intended

**Comment by kamilogorek** [comment]
Done: https://github.com/getsentry/sentry-go/blob/8c0bc966c9b198c705f94f367073e2b865a74509/transport.go#L40-L65
