### ISSUE TITLE
Make Client.Capture* methods non-exported

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/sentry-go#200]
Typical SDK usage does not include calling `Client.CaptureEvent` directly, but rather using the "static API" (`sentry.CaptureEvent`) or a hub (`Hub.CaptureEvent`).
Even when using multiple clients, it is possible to still use a Hub:

```go
hub.BindClient(client)
hub.CaptureEvent(...)
```

Consider removing `Client.CaptureEvent`, `Client.CaptureException` and `Client.CaptureMessage` from the exported API.

**Comment by cleptric** [comment]
Customers rely on this.
