### ISSUE TITLE
Panics and Fingerprinting

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/sentry-go#210]
Extracted from #107.

@parasssh
> Simply calling sentry.CaptureException followed by sentry.Flush() in the panic handler does the trick. The only downside is that the stack-trace will be useless as it gives the trace to the panic handler which is really a monitoring process. However, the panic-handler's input parameter has the stacktrace of exactly where the panic occurred in the application.

> Since all panics will have the same stack trace (the trace in the monitoring process), they are are all grouped together as one issue even though the panics may happen in different places.

@rhcarvalho 

> you can configure grouping using fingerprints, and use BeforeSend to configure the Event.Fingerprint.
> 
> https://docs.sentry.io/guides/grouping-and-fingerprints/
> https://docs.sentry.io/platforms/go/panics/#using-context

@parasssh
> Now, It seems SDK Fingerprinting in the beforeSend is the way to go for the grouping issue . However, that would mean parsing the panic stack trace (which is actually just a message in the event in the way we implemented capturing panics) and fingerprinting off of that instead of the Default Grouping which relies on the Stack Trace which is always the same. However, I wanted to avoid parsing panics.
> 
> Alternatively,
> 
> - can I just erase the entire stack trace in the event in beforeSend hook to force the Default Grouping to use the event message which in my case is the panic and its stacktrace?
> - -OR- replace the stacktrace with the panic's stacktrace (kinda like cheating /hacky).
>
> Basically, I want Grouping to be done off the panic's stacktrace.

**Comment by rhcarvalho** [comment]
@parasssh 

In [dgraph/x/sentry_integration.go](https://github.com/dgraph-io/dgraph/blob/d3a43051ef31f1612c2ed60d2bd13f0ede806a21/x/sentry_integration.go), instead of creating a new error and passing it to `CaptureException`, you can try something like this:

```go
sentry.WithScope(func(scope *sentry.Scope) {
	scope.SetLevel(sentry.LevelFatal)
	sentry.CaptureMessage(`panic: ...`)
})
```

With this, panics will appear as fatal events in the UI, and they will be grouped by message/ panic stacktrace.

You only need that for panics from a different process. If you can capture a panic in-process, I'd recommend that because then you have a full stacktrace instead of just bytes.

**Comment by parasssh** [comment]
> 
> 
> @parasssh
> 
> In [dgraph/x/sentry_integration.go](https://github.com/dgraph-io/dgraph/blob/d3a43051ef31f1612c2ed60d2bd13f0ede806a21/x/sentry_integration.go), instead of creating a new error and passing it to `CaptureException`, you can try something like this:
> 
> ```go
> sentry.WithScope(func(scope *sentry.Scope) {
> 	scope.SetLevel(sentry.LevelFatal)
> 	sentry.CaptureMessage(`panic: ...`)
> })
> ```
> 
> With this, panics will appear as fatal events in the UI, and they will be grouped by message/ panic stacktrace.
> 
> You only need that for panics from a different process. If you can capture a panic in-process, I'd recommend that because then you have a full stacktrace instead of just bytes.

Correct. I am trying that approach with some success. 
Another approach I did was to still do a CaptureException() but in the beforeSend(), I set the event's stacktrace/raw-stacktrace to nil and type to the panic messages 1st line. In the absence of stacktraces, it is forcing the grouping algorithm to resort to the events' type and value which is essentially same as Message.

Yeah, ideally, I'd like to capture panics in-process.  Waiting/Bumping on #107  , any ETA on that?

**Comment by rhcarvalho** [comment]
#107 is about out-of-process. In-process is supported by the SDK, see `Recover`.

**Comment by parasssh** [comment]
> #107 is about out-of-process. In-process is supported by the SDK, see `Recover`.

Right. However, In-process with Recover() is not scalable/maintainable since we will have to sweep the code-base for go routines and Recover(). 
#107 is still desirable with the stacktrace being that of the panic itself so we dont have to massage the events with beforeSend().
