### ISSUE TITLE
Relative path in stack traces

### ISSUE THREAD

**Issue by eric** [getsentry/sentry-go#216]
I see in #101 that it used to be the case that the path along with the filename was included in the UI for stack traces (similar to how ruby is). Now it's only showing the filename unless you mouse-over, which isn't easy to see a full stack trace.

How do I get the path along with the filename to be included? We use `go build -trimpath` when we build right now so that the full path names don't have meaningless prefixes.

**Comment by rhcarvalho** [comment]
This is indeed an accidental omission, going to fix that. Thanks for reporting, @eric!
