### ISSUE TITLE
Recover and RecoverWithContext with arbitrary types

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/sentry-go#219]
`Recover` and `RecoverWithContext` send events to Sentry when they recover from panics and the recovered value has type `error` or `string`. Any other types are ignored.

https://github.com/getsentry/sentry-go/blob/550a179aaa1655092edfba5d2ea4bfc1690736e5/client.go#L233-L284

We should send events no matter the type we're recovering (and need to handle the case in which the value is not serializable as JSON).

**Comment by trungdq88** [comment]
I'm glad that this is reported, I wasted 1 hour debugging why my `panic(123)` didn't work :(
