### ISSUE TITLE
Possible new capture method - CaptureExceptionWithMessage()

### ISSUE THREAD

**Issue by sk0g** [getsentry/sentry-go#225]
So the common usage I had for Sentry was to capture an error, alongside a message indicating some hints as to what was happening then. The exact method used was `raven.CaptureError()`, which accepted the error, a map of context and details, and the string I passed in.

Is there any alternative to that I might be missing here?

The current options are:
1. `CaptureException(); CaptureMessage()` - this is what I was doing, but it inflates the amount of errors, and it can be hard to correlate them.
2. `errors.Wrap() / errors.WithMessage()` - this loses the stack trace, which is a critical part of the context required to sort the issue out.
3. revert to `raven-go` lol

Regards,
Ani

EDIT: forgot to mention, I am more than happy to give this a shot myself. However, I was not sure if this is open source as in source available but only the cool insider kids can commit *cough Google*, or if it was actually open source :)

**Comment by rhcarvalho** [comment]
> the common usage I had for Sentry was to capture an error, alongside a message indicating some hints as to what was happening then.
> Is there any alternative to that I might be missing here?

Might not be as ergonomic, but possible today.

`sentry.WithScope` (or `hub.WithScope` if you're doing this concurrently from multiple goroutines) allows you to do a lot of things that alter events.
You could use Breadcrumbs or set the Message on the event using an EventProcessor:

```go
sentry.WithScope(func(scope *sentry.Scope) {
	scope.AddEventProcessor(func(event *sentry.Event, hint *sentry.EventHint) *sentry.Event {
		event.Message = "custom message"
		return event
	})
	sentry.CaptureException(err)
})
```
![image](https://user-images.githubusercontent.com/88819/82466163-59403580-9ac0-11ea-83f1-53c9b8f99b01.png)


```go
sentry.AddBreadcrumb(&sentry.Breadcrumb{
	Message: "custom message",
})
sentry.CaptureException(err)
```
![image](https://user-images.githubusercontent.com/88819/82466083-4463a200-9ac0-11ea-9a8a-34eba6684653.png)


---------

As for adding new APIs, the new Sentry SDKs try to follow an unified design https://develop.sentry.dev/sdk/unified-api/.



> I was not sure if this is open source as in source available

The project is open source and we do accept external contributions, not only to the SDKs but also to Sentry itself https://github.com/getsentry/sentry.

**Comment by sk0g** [comment]
Sweet, that worked  perfectly for my use case :) 

It's not ideal in ideal in terms of elegance, but it'll do! Maybe the documentation could explain this a bit better, unless I missed it? More specifically, the raven -> sentry migration guide.

**Comment by rhcarvalho** [comment]
> Sweet, that worked perfectly for my use case :)

Glad it helped!

> Maybe the documentation could explain this a bit better, unless I missed it? More specifically, the raven -> sentry migration guide.

We'd be happy to try to improve it.

@sk0g, were you following the guide in https://docs.sentry.io/platforms/go/migration/ or https://github.com/getsentry/sentry-go/blob/master/MIGRATION.md (or somewhere else?!)?

Which one of the solutions I proposed did you decide to use?  (Maybe a quick note on your decision process would be helpful too).

Thanks!

**Comment by sk0g** [comment]
Hey, I ended up writing the capture exception event like this:

```go
                sentry.WithScope(func(scope *sentry.Scope) {
			scope.AddEventProcessor(func(event *sentry.Event, hint *sentry.EventHint) *sentry.Event {
				event.Message = m
				return event
			})
			sentry.CaptureException(err)
		})
```

I saw all the other options for additional information in the event struct, and decided that was a cleaner way to do it.

https://docs.sentry.io/platforms/go/migration/ is the guide I was following. It did mention messages but more as a separate process. I didn't realise you can use it as scope while capturing an error to propagate the message alongside the error, very cool! 

I guess if the APIs are being kept consistent, there would be no point to this, but I think this hack/ workaround deserves a mention in the migration guide :sweat_smile:
