### ISSUE TITLE
Sentry log : Buffer flushing reached the timeout

### ISSUE THREAD

**Issue by parasssh** [getsentry/sentry-go#226]
A user reported https://github.com/dgraph-io/dgraph/issues/5458 

While we are trying to fix the issue, we also noticed that these events are not being sent to Sentry in some cases. In the above issue, we see logs: 

[Sentry] 2020/05/18 07:58:14 Sending fatal event [0714232f3f3e4737aa05ea9dec53ab2b] to o318308.ingest.sentry.io project: 1805390

[Sentry] 2020/05/18 07:58:16 Buffer flushing reached the timeout.

Opening this issue to see what situation can the buffer containing the sentry event not get flushed and how should we fix / change this so events don't get lost/dropped.

**Comment by rhcarvalho** [comment]
> events are not being sent to Sentry in some cases. In the above issue, we see logs:
> 
> [Sentry] 2020/05/18 07:58:16 Buffer flushing reached the timeout.

As a protection from freezing a crashing program for unbounded amount of time, `sentry.Flush` takes a timeout argument.

`dgraph` uses a `2s` timeout at the moment.

https://github.com/dgraph-io/dgraph/blob/29e44151ba8548f8c981a95f8fcae4080413ec07/x/sentry_integration.go#L91-L94

If the SDK is hanging for more than the timeout trying to send the event, it gives up to allow the program to proceed.

What timeout value to use depends on your "budget", how long can the program afford to wait. How long it actually takes to send an event depends on the network.
