### ISSUE TITLE
negative WaitGroup counter

### ISSUE THREAD

**Issue by bugall** [getsentry/sentry-go#23]
github.com/getsentry/sentry-go/transport.go:200

**Comment by kamilogorek** [comment]
Can you provide a repro-case for this issue? I cannot debug if I'm not able to reproduce it. Thanks!

**Comment by polarina** [comment]
@kamilogorek This looks like a race-condition to me:

https://github.com/getsentry/sentry-go/blob/e3426d1877ca5368ddc0bfc112368a0c293fad0e/transport.go#L147

The write to the `t.buffer` channel is done prior to `t.wg.Add(1)`. If the worker finishes before that call, the call to `t.wg.Done()' will decrement a zero counter and go negative.

**Comment by kamilogorek** [comment]
Thanks @polarina ! Addressed here https://github.com/getsentry/sentry-go/pull/25/
