### ISSUE TITLE
Support for stack frames from xerrors

### ISSUE THREAD

**Issue by nzoschke** [getsentry/sentry-go#246]
## Summary

This is related to the xerrors package: https://godoc.org/golang.org/x/xerrors

For high level context, we are still using this in favor of Go 1.13 stdlib because of the stack trace collection that when logged helps developers understand where the errors are coming from.

An issue was raised before in https://github.com/getsentry/sentry-go/issues/137. While I see that the unwrapping an xerror to its original error is working, I do not see stack traces from xerrors working in Sentry.

## Steps To Reproduce

```go
func foo() {
	sentry.CaptureException(x1())
}

func x1() error {
	return xerrors.Errorf("%w", x2())
}

func x2() error {
	return xerrors.New("x2msg")
}
```

## Expected Behavior

If you print the extended format of the xerror you see a stack trace like:

```
x2msg:
  grax/x/log.x1
    foo/x/log/error_test.go:84
- x2msg:
  grax/x/log.x2
    foo/x/log/error_test.go:88
```

But if I look at Sentry UI I do not see anything about x2 or x1 in the call stack. See the screenshot below.

## Screenshots

<img width="593" alt="Screen Shot 2020-06-05 at 2 23 03 PM" src="https://user-images.githubusercontent.com/147410/83923918-1a54e580-a738-11ea-9e00-087bf1950b78.png">

### SDK
 - `sentry-go` version: `github.com/getsentry/sentry-go v0.6.1`
 - Go version: `go version go1.14.3 darwin/amd64`
 - Using Go Modules? yes

### Sentry
 - Using hosted Sentry in sentry.io? yes

## Additional context

Digging into the `sentry-go` code I see support for getting stack frames from interfaces packages like https://github.com/pkg/errors use. But I do not see anything related to the xerrors interface.

https://github.com/getsentry/sentry-go/blob/master/stacktrace.go#L71

I will attempt to patch this, but wanted to open an issue first to discuss.

**Comment by nzoschke** [comment]
I haven’t found a good way to get the actual frame data in since xerrors doesn’t offer a public interface to get the data out. 

For now I am copying the expanded xerrors formatting with stack trace into the sentry exception message.

**Comment by rhcarvalho** [comment]
@nzoschke thanks for filing the issue. I confirm I've implemented unwrapping and overlooked the stack trace extraction at the time, my bad.

I'm working on revamping the stack trace extraction and was able to extract the stack from an `xerrors` error using reflection:

```go
field := reflect.ValueOf(err).Elem().FieldByName("frame") // type Frame struct{ frames [3]uintptr }
field = field.FieldByName("frames")
pc := make([]uintptr, field.Len())
for i := 0; i < field.Len(); i++ {
	pc[i] = uintptr(field.Index(i).Uint())
}
```

One thing to notice is that unlike `github.com/go-errors/errors` (max depth 50 frames) and `github.com/pkg/errors` (max depth 32 frames), `golang.org/x/xerrors` retains at most 3 (physical) frames (there can be more logical frames due to inlining).

If all goes well this week I should be able to prepare a patch and submit a PR.
