### ISSUE TITLE
Expose `CaptureEvent` submission errors to allow fallback to other reporting mechanisms. 

### ISSUE THREAD

**Issue by brhoades** [getsentry/sentry-go#270]
## Summary
Expose `CaptureEvent` submission errors to allow fallback to other reporting mechanisms. 

## Motivation
When event reporting fails, a log is printed and the error is discarded. I'd prefer that the original event be captured through an existing email event reporter so that events aren't lost. However, I don't see an easy mechanism to allow capturing transport errors without inspecting responses via a custom `http.Transport` or watching stdout.

https://github.com/getsentry/sentry-go/blob/ee5541cf900808891977d1c8d59dbe131986df72/transport.go#L440-L448

In the past, we've really wanted these discarded events when we've hit the event reporting API limit.

## Additional Context
If desired, I'm happy to PR this personally, but would like consensus on how to do this. In my opinion, exposing a `ClientOptions` field with an optional `SentryErrorHandler func(ev *Event, sentryErr error)` callback seems pretty unoffensive.

Allowing a custom `HTTPTransport` is less opinionated and may work as well.

**Comment by rhcarvalho** [comment]
Hi @brhoades, at the moment the use case described here is addressable either by using a custom `sentry.Transport` or `http.RoundTripper`.

https://pkg.go.dev/github.com/getsentry/sentry-go?tab=doc#ClientOptions

The relevant configuration is `ClientOptions.Transport` or `ClientOptions.HTTPTransport`.

I'd suggest starting with a custom `http.RoundTripper`, as it allows you to reuse the logic of the internal transport like respecting rate limits.

I added one example you can start from here: https://godoc.org/github.com/getsentry/sentry-go#example-package--TransportWithHooks. You could use the `After` hook to send the original event payload to your email reporter.

**Comment by brhoades** [comment]
Thanks for the example! Unfortunately, it doesn't provide access to the original `Event` that failed to send, only the JSON body from it. 

I dug into this more since opening this issue; retaining an `Event` for the async transport will likely end up being inelegant. I'm going to give the `RoundTripper` a try and see how good the body looks in an email :).

If it doesn't work out particularly well, I'll reach out again.

**Comment by brhoades** [comment]
I've tried this out and I'm satisfied with using a `RoundTripper`; it's easy to Unmarshal back to the `Event` on failure.

Thanks for the help, I'll close this.

**Comment by rhcarvalho** [comment]
> Thanks for the example!



> I've tried this out and I'm satisfied with using a `RoundTripper`

Happy to help <3
