### ISSUE TITLE
Is there any situation for Method `hub.WithScope` ?

### ISSUE THREAD

**Issue by mozhata** [getsentry/sentry-go#274]
as the code: 
```
func (hub *Hub) WithScope(f func(scope *Scope)) {
	scope := hub.PushScope()
	defer hub.PopScope()
	f(scope)
}
```
ater `f(scope)` executed, the new scope is discard. seems not make sense

**Comment by rhcarvalho** [comment]
> after f(scope) executed, the new scope is discard. seems not make sense

Discarding the scope after its use is exactly the purpose of `WithScope`.

Please see the [Hub.WithScope documentation](https://pkg.go.dev/github.com/getsentry/sentry-go?tab=doc#Hub.WithScope) and compare it with [Hub.ConfigureScope](https://pkg.go.dev/github.com/getsentry/sentry-go?tab=doc#Hub.ConfigureScope).

Here is an usage example:

https://github.com/getsentry/sentry-go/blob/23c562d005a5ee3ce2c46f6a857feb0d72a74368/example/feature-showcase/main.go#L60-L63
