### ISSUE TITLE
How to pass the Git Commit with every message

### ISSUE THREAD

**Issue by ORESoftware** [getsentry/sentry-go#276]
So I am here:
https://sentry.io/onboarding/channelmeter-k3/get-started/

I have this code in main():

```golang
  err := sentry.Init(sentry.ClientOptions{
    Dsn: "https://83df6a51dd574458b08f94048381b613@o449605.ingest.sentry.io/5432858",
  })
  
  if err != nil {
    log.Fatalf("sentry.Init: %s", err)
  }

  defer sentry.Flush(2 * time.Second)

  sentry.CaptureMessage("It works!")

  time.Sleep(time.Second * 5)
  os.Exit(0)
```

my question is - how can I send the git commit for every message? I would have guessed it would have been like this:

```golang
  err := sentry.Init(sentry.ClientOptions{
    CommitId: os.GetEnv("my_git_commit_hash")
    Dsn: "https://83df6a51dd574458b08f94048381b613@o449605.ingest.sentry.io/5432858",
  })
```

but that's not an option in `sentry.ClientOptions` :(  What's the right pattern to use? thanks

**Comment by ORESoftware** [comment]
imo this is way overcomplicated:
https://docs.sentry.io/product/releases/#configure-sdk

why no just pass the repo url and commit id in the client config:

```
 err := sentry.Init(sentry.ClientOptions{
    CommitId: os.GetEnv("my_git_commit_hash"),
    RepoUrl:  "http://github.com/foo/bar",
    Dsn: "https://83df6a51dd574458b08f94048381b613@o449605.ingest.sentry.io/5432858",
  })
```

or something like that?

**Comment by rhcarvalho** [comment]
https://docs.sentry.io/platforms/go/configuration/releases/

```go
 err := sentry.Init(sentry.ClientOptions{
    Dsn: "https://83df6a51dd574458b08f94048381b613@o449605.ingest.sentry.io/5432858",
    Release: "release-id",
  })
```

You can either compile that value into the binary or get it from the environment.
This value is also [automatically picked up from the environment](https://docs.sentry.io/platforms/go/#configure) if you set the `SENTRY_RELEASE` environment variable.

If you prefer to compile it into the binary, this Go linker feature might come in handy: https://stackoverflow.com/a/11355611/963287
