### ISSUE TITLE
Sentry metrics

### ISSUE THREAD

**Issue by tty2** [getsentry/sentry-go#287]
## Summary

Current go sdk doesn't support metrics. https://docs.sentry.io/product/performance/getting-started/
Do you plan to implement it?

## Motivation

Motivation is pretty clear: have metrics as for other languages.

**Comment by tty2** [comment]
Looks like it will be implemented with #286

**Comment by rhcarvalho** [comment]
We're expanding all of our SDKs to add Performance Monitoring.
