### ISSUE TITLE
Link to echo guide is broken

### ISSUE THREAD

**Issue by jack-t** [getsentry/sentry-go#288]
The link to the Echo guide in `README.md` is broken. Right now, it points to [https://docs.sentry.io/platforms/go/echo/](https://docs.sentry.io/platforms/go/echo/), but that URL 404s. Instead, it should point to [https://docs.sentry.io/platforms/go/guides/echo/](https://docs.sentry.io/platforms/go/guides/echo/).

**Comment by rhcarvalho** [comment]
This was fixed in #290.
