### ISSUE TITLE
Export function that builds error chain from wrapped errors

### ISSUE THREAD

**Issue by avgeorge** [getsentry/sentry-go#291]
## Summary

Please export a function that can build an error chain from a wrapped error.

## Motivation

This package has logic that builds an error chain for an event from errors that are wrapped using several different error packages. However, this logic is in a function that builds an event and submits it immediately. I would like to be able to use this logic so that I can make further changes to the event before submitting it.

## Additional Context

The simplest way to achieve this would be to export [Client.eventFromException](https://github.com/getsentry/sentry-go/blob/6ba7f9cc0855829323615e9ba57fb0eb13450cc3/client.go#L368) which builds an event from an error. The function doesn't depend on the client receiver so it's trivial to change it to a standalone function.
It might be better to create a function with a different signature though, e.g. `func ExtractErrorChain(err error) []Exception`

**Comment by rhcarvalho** [comment]
> I would like to be able to use this logic so that I can make further changes to the event before submitting it.

Have you tried `BeforeSend` (global) or using an `EventProcessor` (if you need per-scope customization)? Those are the standard ways to inspect and modify events before sending, including the possibility to drop the event altogether.

- https://pkg.go.dev/github.com/getsentry/sentry-go#ClientOptions
- https://docs.sentry.io/platforms/go/configuration/filtering/#using-beforesend
- https://pkg.go.dev/github.com/getsentry/sentry-go#Scope.AddEventProcessor

**Comment by avgeorge** [comment]
Thanks, I think the Scope.AddEventProcessor should allow me to do what I need.

I want to build a sentry hook for logrus so that errors are sent to sentry automatically when they are logged from logrus. A logrus error log would include the error (or error chain), a message and any additional context as key value pairs. I can set the additional data on the scope, but Hub.CaptureException doesn't allow adding a message. I think I can use an EventProcessor to set the message, but it seems a bit overkill to use it just to set a field I already had when the event was created. So I would still prefer access to this function if possible.

**Comment by cottrellio** [comment]
^ +1 I want logging with the error chain, a custom message, and contextual data

**Comment by KevinSnyderCodes** [comment]
Can we reopen this issue? I am trying to accomplish the same as [here](https://github.com/getsentry/sentry-go/issues/291#issuecomment-719456516): create a custom logger that automatically sends events to Sentry in addition to logging them.

The easiest way to do this is to create a [`NewEvent()`](https://pkg.go.dev/github.com/getsentry/sentry-go#NewEvent) and populate it with a message, exceptions, tags, and extras as the log event gets populated.

The easiest way to add exceptions to this event would be by using the [`Client.eventFromException()`](https://github.com/getsentry/sentry-go/blob/6ba7f9cc0855829323615e9ba57fb0eb13450cc3/client.go#L368) method. However, this method is private, so I must copy the implementation into my own code, which means it might drift from upstream.

Adding a new public method such as `Event.AddException(exception error)` with the same implementation as `Client.eventFromException()` would solve this problem and ensure that anyone's implementation of adding an exception to their event stays the same as upstream.

**Comment by cleptric** [comment]
We did merge and released a Logrus integration (#471) a while ago.

**Comment by KevinSnyderCodes** [comment]
[Logrus](https://github.com/sirupsen/logrus) is now in maintenance mode, with newer libraries such as [zerolog](https://github.com/rs/zerolog) and [zap](https://github.com/uber-go/zap) offering better performance.

What would be nice is to be able to build a custom logger implementation that wraps any number of logging/event capturing solutions (Sentry, Logrus, zerolog, zap) instead of being tightly coupled to Sentry via hooks.

**Comment by cleptric** [comment]
https://github.com/getsentry/sentry-go/pull/607

I can't come up with an immediate answer to why we shouldn't export these two functions.
Maybe you can give this a try and report back in the PR if this is helpful.
