### ISSUE TITLE
Iris v12.0.1 brings in LGPL-licensed packages to module graph

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/sentry-go#297]
My main issue with the large dependency list is not concern over the size of the binary, but that in my organization I have to get the open source licenses reviewed and approved for all transitive dependencies. GPL/LGPL are problematic. 

Starting from `go.mod`:

* `github.com/kataras/iris/v12 v12.0.1` is BSD-3-Clause
    * depends on `github.com/flosch/pongo2@v0.0.0-20190707114632-bbf5a6c351f4`, MIT licensed
        * depends on 3 Juju libraries, all LGPLv3 licensed
            * `github.com/juju/errors@v0.0.0-20181118221551-089d3ea4e4d5`
            * `github.com/juju/loggo@v0.0.0-20180524022052-584905176618`
            * `github.com/juju/testing@v0.0.0-20180920084828-472a3e8b2073`

Those are the only 3 LGPLv3 licensed libraries in the entire graph. The rest are all generally permissive licenses (MIT, BSD, Apache, etc). 

As a workaround, I added this to my `go.mod` to exclude `v12.0.1` of Iris:

```
+exclude (
+       github.com/kataras/iris/v12 v12.0.1
+)
```

This forces Go to use a newer version instead, `v12.1.0`, which thankfully does not pull in the Juju depednencies.

_Originally posted by @peplin in https://github.com/getsentry/sentry-go/issues/156#issuecomment-725098706_

**Comment by peplin** [comment]
Thank you!
