### ISSUE TITLE
Open contributions

### ISSUE THREAD

**Issue by YashishDua** [getsentry/sentry-go#3]
Is this project open to contributions?

**Comment by kamilogorek** [comment]
@YashishDua thanks for asking! I need about 2-3 more weeks to wrap-up a beta version and then it'll be officially published and opened :)

**Comment by YashishDua** [comment]
Yeah, for sure! I will definitely put up my thoughts.

**Comment by kamilogorek** [comment]
We are actively looking for active Go community developers, that would like to help us get this thing done.
If anyone wants to join our community Slack channel, shoot me up and email and I'll send you an invite! :)

**Comment by valentin-krasontovitsch** [comment]
I would like to add my 2 cents, and help with code review / contributions, but my experience with contributing to the last sdk was rather sobering (cf. [a pull request I submitted](https://github.com/getsentry/raven-go/pull/161)).

So if there's a change in how the maintainer(s) plan to respond to contributions compared to the past, I will gladly join in.

**Comment by YashishDua** [comment]
@valentin-krasontovitsch The PR which you submitted is in the Raven client (no longer maintained) which is now being converted to language-specific SDKs. So, this project is totally active and we are actively looking for OSS Go developers here. Shoot an email to @kamilogorek to join our Slack channel.

**Comment by kamilogorek** [comment]
@valentin-krasontovitsch sorry about that, I wasn't involved in the previous SDK and didn't want to spend too much time on it, as we made a decision to create a full-fledged Go SDK that'll follow our unified SDK API and allow to use Sentry to it's fullest.

Any help is appreciated and definitely won't be left out in this repository, so feel free to send me your email and I'll happily send you a Slack request :)

**Comment by valentin-krasontovitsch** [comment]
@YashishDua @kamilogorek thanks for the responses, and that's quite alright - gonna send you an email right away. looking forward to hearing getting some more insight into the sdk / sdk api.

**Comment by kamilogorek** [comment]
**First stable release v0.1 is live!** 🎉 

Community note has been added to the readme, so I'll close this issue :)
