### ISSUE TITLE
Migrate CI from Travis to GitHub Actions

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry-go#313]
Travis sprung some surprise billing changes on us awhile, so we are now prioritizing removing usage of TravisCI completely. This issue will be used by @getsentry/productivity to track overall progress across the organization, but please let us know here if there's anything we should be aware of.

**Comment by armenzg** [comment]
@kamilogorek Is this referring to the `main` branch on https://github.com/golang/go ? I don't see an official support by the [setup-go action](https://github.com/marketplace/actions/setup-go-environment) so it might take some effort to obtain that functionality.
https://github.com/getsentry/sentry-go/blob/db5fae9b7d51408d954204f6813626acf60bf6c1/.travis.yml#L7

@billyvg any suggestions on how to emulate Travis' webhook and notifications? (I see some unverified Webhook actions)
https://github.com/getsentry/sentry-go/blob/db5fae9b7d51408d954204f6813626acf60bf6c1/.travis.yml#L51-L59

**Comment by armenzg** [comment]
@kamilogorek What's happening for this error?
https://github.com/armenzg/sentry-go/runs/1652741273?check_suite_focus=true
```
Run go build ./...
  go build ./...
  shell: /usr/bin/bash -e {0}
  env:
    GO111MODULE: off
    GOROOT: /opt/hostedtoolcache/go/1.14.13/x64
traces_sampler.go:6:2: cannot find package "github.com/getsentry/sentry-go/internal/crypto/randutil" in any of:
	/opt/hostedtoolcache/go/1.14.13/x64/src/github.com/getsentry/sentry-go/internal/crypto/randutil (from $GOROOT)
	/home/runner/go/src/github.com/getsentry/sentry-go/internal/crypto/randutil (from $GOPATH)
client.go:19:2: cannot find package "github.com/getsentry/sentry-go/internal/debug" in any of:
	/opt/hostedtoolcache/go/1.14.13/x64/src/github.com/getsentry/sentry-go/internal/debug (from $GOROOT)
	/home/runner/go/src/github.com/getsentry/sentry-go/internal/debug (from $GOPATH)
```

**Comment by billyvg** [comment]
I would defer to Kamil re: how we want to handle zeus.

**Comment by armenzg** [comment]
@kamilogorek Would I also be able to get write access? It will allow me to run the GH actions as part of the PR.

**Comment by rhcarvalho** [comment]
> What's happening for this error?

I think it's trying to build with `GO111MODULE=off` code checked-out outside of GOPATH, that won't work.
I need to see what's the best practice here, one solution is to set `GOPATH` explicitly to `$GITHUB_WORKSPACE`.

> I would defer to Kamil re: how we want to handle zeus.

We don't need a replacement for Zeus, we already use GH to check build status in Craft (and note we don't need any artifact provider for Go), so we can remove the webhook without affecting the release process.

**Comment by rhcarvalho** [comment]
@armenzg 

https://github.com/mvdan/github-actions-golang#how-do-i-set-up-a-gopath-build

**Comment by armenzg** [comment]
@billyvg @rhcarvalho would you mind reviewing this? https://github.com/getsentry/sentry-go/pull/314

**Comment by armenzg** [comment]
@rhcarvalho do you have some steps as to how to quickly get a go version from source checkout?

I'm looking at the Travis code and I can't figure out what steps are taken to get a development version installed.

**Comment by armenzg** [comment]
Merged: https://github.com/getsentry/sentry-go/pull/314
Next: https://github.com/getsentry/sentry-go/pull/319

@rhcarvalho r? for #319 

FYI You will need to change the "Required checks" at the repository level.

**Comment by armenzg** [comment]
Hi @rhcarvalho how do you feel about dropping the Travis CI? No pressure. Just curious if there's anything left to validate.

**Comment by armenzg** [comment]
@rhcarvalho Would it be possible to land this? In February, `sentry-go` used more than 50% of our Travis credits.

**Comment by armenzg** [comment]
👏🏻
