### ISSUE TITLE
FastHTTP Handler not working with fiber

### ISSUE THREAD

**Issue by anistark** [getsentry/sentry-go#330]
## Summary
I'm using [fiber](https://github.com/gofiber/fiber) which uses fasthttp context.
On integrating `/fasthttp` package, I'm getting the error as : `invalid handler fasthttp.RequestHandler`

## Steps To Reproduce
I'm following the [fasthttp documentation](https://docs.sentry.io/platforms/go/guides/fasthttp/).

## Expected Behavior
Sentry should have initialised.

## Environment
Testing on local right now.

### SDK
 - `sentry-go` version: `v0.9.0`
 - Go version: `1.15`
 - Using Go Modules? yes

**Comment by cleptric** [comment]
This won#t work. You can take a look at https://github.com/gofiber/contrib/tree/main/fibersentry until we get #273 merged.

**Comment by cleptric** [comment]
This won#t work. You can take a look at https://github.com/gofiber/contrib/tree/main/fibersentry until we get #273 merged.
