### ISSUE TITLE
Wrong error check would miss logging important warning 

### ISSUE THREAD

**Issue by alxarch** [getsentry/sentry-go#336]
I suspect the check at
https://github.com/getsentry/sentry-go/blob/8fbb027528f9464e0233afa756cef0f99bd70906/transport.go#L101
Should be `err != nil` instead of `err == nil`.

**Comment by rhcarvalho** [comment]
@alxarch thanks for reporting. I double-checked it is correct in what it does, though awkward looking compared to what one would expect.
