### ISSUE TITLE
Trace `hubFromContext` will never find hub from gin or iris.

### ISSUE THREAD

**Issue by elliotcourant** [getsentry/sentry-go#337]
## Summary

When using the gin or iris middleware (potentially others, these are the only ones I've looked at so far) the middleware creates a hub for each request.

https://github.com/getsentry/sentry-go/blob/57123a409be55f61b1d5a6da93c176c55a399ad0/gin/sentrygin.go#L49-L58

This is because both are trying to derive a hub from the context on the *http.Request object. Neither of these to HTTP libraries allow this context.Context to be modified before hand and if the context is not present on the request object then a new `context.Background()` is returned by `request.Context()` anyway. So the `sentry.GetHubFromContext()` call at the beginning of both the gin and iris handles will always return nil and then create a new hub from the global hub.

That new hub is then stored on the request context object for both gin and iris in these ways respectively:
- `ctx.Set(valuesKey, hub)`
- `ctx.Values().Set(valuesKey, hub)`

## Steps To Reproduce

This leads to my issue (and I may just be doing something super wrong in how I am approaching this problem); I want to create a trace span for my HTTP handlers.

```go
	app.Use(sentrygin.New(sentrygin.Options{
		Repanic: true,
	}))

	app.GET("/things", func(ctx *gin.Context) {
		// The span is created but the hub it is using is not the same as the one that would be returned from
		// sentry.GetHubFromContext(ctx);
		span := sentry.StartSpan(ctx, ctx.Request.Method, sentry.TransactionName(ctx.HandlerName()))
		defer span.Finish()


		// do some work with a database or something.
		renameAllTheUsers(span.Context())

		ctx.Status(http.StatusOK)
	})
```
With that example above each request would have a hub stored on the `*gin.Context` with the values key of `sentry`, but when the trace is started the hub is not pulled from the same context value that the HTTP middleware stored it in.

https://github.com/getsentry/sentry-go/blob/57123a409be55f61b1d5a6da93c176c55a399ad0/tracing.go#L147-L154
https://github.com/getsentry/sentry-go/blob/57123a409be55f61b1d5a6da93c176c55a399ad0/hub.go#L370-L377

This results in the span having a different hub than the actual request, and thus might not have all of the data or might not associate with each other properly if there was anything less than a panic within the handler. 

## Expected Behavior

I would expect that spans created in a HTTP handler would use the same hub created by the HTTP middleware provided. Or at the very least would allow a span to be created from a hub object directly.

### SDK
 - `sentry-go` version: 0.10.0
 - Go version: 1.16.3
 - Using Go Modules? [yes/no]: yes

### Sentry
 - Using hosted Sentry in sentry.io? [yes/no]: yes
 - Using your own Sentry installation? Version: 
 - Anything particular to your environment that could be related to this issue?

## Additional context

If a span were to have the same hub as the request will that add any additional information to the traces sent back to Sentry?

Sorry if I am missing something and I am approaching this completely wrong.

**Comment by elliotcourant** [comment]
Something like this would allow hubs to be used with trace spans without any breaking changes and would allow the use of the provided `GetHubFromContext` method already built into the sentrygin package. Note: This won't work with iris because of how the object is structured, but a custom wrapper could be built by the end user to work around that.

```patch
diff --git a/gin/sentrygin.go b/gin/sentrygin.go
index cd7e9f4..4ea5580 100644
--- a/gin/sentrygin.go
+++ b/gin/sentrygin.go
@@ -12,6 +12,12 @@ import (
 	"github.com/gin-gonic/gin"
 )
 
+var (
+	// Make sure that our method properly matches the method signature we need.
+	_ sentry.DeriveHubFromContext = GetHubFromContext
+)
+
+
 const valuesKey = "sentry"
 
 type handler struct {
@@ -88,11 +94,14 @@ func isBrokenPipeError(err interface{}) bool {
 }
 
 // GetHubFromContext retrieves attached *sentry.Hub instance from gin.Context.
-func GetHubFromContext(ctx *gin.Context) *sentry.Hub {
-	if hub, ok := ctx.Get(valuesKey); ok {
-		if hub, ok := hub.(*sentry.Hub); ok {
-			return hub
+func GetHubFromContext(ginContext context.Context) *sentry.Hub {
+	if ctx, ok := ginContext.(*gin.Context); ok && ctx != nil {
+		if hub, ok := ctx.Get(valuesKey); ok {
+			if hub, ok := hub.(*sentry.Hub); ok {
+				return hub
+			}
 		}
 	}
+
 	return nil
 }
diff --git a/hub.go b/hub.go
index f055c56..b7296ae 100644
--- a/hub.go
+++ b/hub.go
@@ -358,6 +358,8 @@ func HasHubOnContext(ctx context.Context) bool {
 	return ok
 }
 
+type DeriveHubFromContext func(ctx context.Context) *Hub
+
 // GetHubFromContext tries to retrieve Hub instance from the given Context struct
 // or return nil if one is not found.
 func GetHubFromContext(ctx context.Context) *Hub {
diff --git a/tracing.go b/tracing.go
index 125bb3e..792b0b5 100644
--- a/tracing.go
+++ b/tracing.go
@@ -75,6 +75,14 @@ type Span struct { //nolint: maligned // prefer readability over optimal memory
 // root span sends the span and all of its children, recursively, as a
 // transaction to Sentry.
 func StartSpan(ctx context.Context, operation string, options ...SpanOption) *Span {
+	return StartSpanWithDerivedHub(ctx, operation, hubFromContext, options...)
+}
+
+// StartSpanWithDerivedHub is the same as StartSpan but allows a custom method
+// to be provided to extract a *Hub from the context. This is useful when the
+// context you are working with is something like *gin.Context and the hub
+// might not be stored in the same way it normally would be.
+func StartSpanWithDerivedHub(ctx context.Context, operation string, deriveHubFromContext DeriveHubFromContext, options ...SpanOption) *Span {
 	parent, hasParent := ctx.Value(spanContextKey{}).(*Span)
 	var span Span
 	span = Span{
@@ -88,6 +96,8 @@ func StartSpan(ctx context.Context, operation string, options ...SpanOption) *Sp
 	}
 	if hasParent {
 		span.TraceID = parent.TraceID
+		span.ParentSpanID = parent.SpanID
+		span.recorder = parent.spanRecorder()
 	} else {
 		// Implementation note:
 		//
@@ -123,14 +133,13 @@ func StartSpan(ctx context.Context, operation string, options ...SpanOption) *Sp
 		if err != nil {
 			panic(err)
 		}
+
+		span.recorder = &spanRecorder{}
 	}
 	_, err := rand.Read(span.SpanID[:])
 	if err != nil {
 		panic(err)
 	}
-	if hasParent {
-		span.ParentSpanID = parent.SpanID
-	}
 
 	// Apply options to override defaults.
 	for _, option := range options {
@@ -139,16 +148,22 @@ func StartSpan(ctx context.Context, operation string, options ...SpanOption) *Sp
 
 	span.Sampled = span.sample()
 
-	if hasParent {
-		span.recorder = parent.spanRecorder()
-	} else {
-		span.recorder = &spanRecorder{}
-	}
 	span.recorder.record(&span)
 
+	// Will make it possible to derive a hub from something like
+	// sentrygin.GetHubFromContext easily.
+	hub := deriveHubFromContext(ctx)
+	if hub == nil {
+		// Because this is no longer using the normal "hubFromContext"
+		// to extract the hub, it is possible for this to be nil. But
+		// we can simply fallback to the hubFromContext behavior if it
+		// is.
+		hub = currentHub
+	}
+
 	// Update scope so that all events include a trace context, allowing
 	// Sentry to correlate errors to transactions/spans.
-	hubFromContext(ctx).Scope().SetContext("trace", span.traceContext())
+	hub.Scope().SetContext("trace", span.traceContext())
 
 	return &span
 }
```

**Comment by rhcarvalho** [comment]
Hi @elliotcourant, sorry we don't have tracing support for 3rd-party frameworks built into the SDK yet. Tracing support in this SDK is still incomplete. What we cover is the instrumentation of web servers using `net/http`.

That said, I think with a small modification your code should work:

```go
		hub := sentrygin.GetHubFromContext(ctx)
		tracingCtx := sentry.SetHubOnContext(ctx, hub)
		span := sentry.StartSpan(tracingCtx, ctx.Request.Method, sentry.TransactionName(ctx.HandlerName()))
		defer span.Finish()
```

Your observation was completely correct that the hub is stored with different keys, so above I added two lines to adapt from one key to the other.

Obviously, when we add support into the framework integrations themselves, you won't need to do this.

In fact, if you want to trace more routes, you can put the code above in a middleware so you don't have to repeat it over and over.

Thanks for using the SDK, please let me know if I can help in any other way.

Cheers!

---

Notes on the current middleware implementations:

<details>

> Neither of these to HTTP libraries allow this context.Context to be modified before hand

They do by the same mechanism that the Sentry Go SDK uses: any middleware can access and update the request context.

> and if the context is not present on the request object then a new `context.Background()` is returned by `request.Context()` anyway. So the `sentry.GetHubFromContext()` call at the beginning of both the gin and iris handles will always return nil and then create a new hub from the global hub.

It is not always `nil`, we have users that have a hub created explicitly or implicitly earlier on on the call stack, for example when using one of these web frameworks in combination with AWS Lambda.

</details>

**Comment by elliotcourant** [comment]
Thank you very much I will use that!

**Comment by rhcarvalho** [comment]
The question was addressed and transactions are flowing in, so I think we can close this one.
