### ISSUE TITLE
Without being able to use `BeforeSend` how do you scrub traces?

### ISSUE THREAD

**Issue by elliotcourant** [getsentry/sentry-go#341]
https://github.com/getsentry/sentry-go/blob/2524861675d8d1062b339d0e492e50da01d872af/client.go#L518-L529
Creating a trace for an HTTP handler. (In this case iris)

```golang
		p.Use(func(ctx iris.Context) {
			if hub := sentryiris.GetHubFromContext(ctx); hub != nil {
				tracingCtx := sentry.SetHubOnContext(ctx.Request().Context(), hub)
				name := strings.TrimSpace(strings.TrimPrefix(ctx.RouteName(), ctx.Method()))
				span := sentry.StartSpan(tracingCtx, ctx.Method(), sentry.TransactionName(name))
				defer span.Finish()

				ctx.Values().Set(spanContextKey, span.Context())
			} else {
				ctx.Values().Set(spanContextKey, ctx.Request().Context())
			}

			ctx.Next()
		})
```

I am unable to scrub sensitive data from the resulting span events sent to sentry. So sensitive details like cookies can appear in my performance view:

![image](https://user-images.githubusercontent.com/37967690/118288436-11b57500-b49a-11eb-9047-9747df405e26.png)

Is there another way to remove this sensitive data from span events? Or a best practice for keeping that data out of it to begin with?

**Comment by rhcarvalho** [comment]
@elliotcourant you can use an `EventProcessor` to scrub the transaction (or an error event) before it goes to Sentry:

```go
func main() {
	// sentry.Init()
	// ...
	sentry.ConfigureScope(func(scope *sentry.Scope) {
		scope.AddEventProcessor(func(event *sentry.Event, hint *sentry.EventHint) *sentry.Event {

			// mutate event.Request here

			return event
		})
	})
	// ...
}
```

I'll update the inline docs.
