### ISSUE TITLE
Go SDK: Sentry only recognizes custom error type if it is a struct

### ISSUE THREAD

**Issue by ditek** [getsentry/sentry-go#347]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

Sentry only recognizes a custom error type if it is a struct. Meaning, an error type (no struct) would show up as the underlying error. See example below.

## Steps to Reproduce

This code illustrates my point.

```go
package main

import (
	"errors"
	"github.com/getsentry/sentry-go"
	"time"
)

type (
	operationTimeoutError error
	anotherTimeoutError   struct {
		msg string
	}
	thirdTimeoutError struct{ error }
)

var errOperationTimeout operationTimeoutError = errors.New("TIMEOUT")

func (e *anotherTimeoutError) Error() string {
	return e.msg
}

func foo() {
	sentry.CaptureException(errOperationTimeout)
}

func bar() {
	sentry.CaptureException(&anotherTimeoutError{"TIMEOUT"})
}

func blue() {
	sentry.CaptureException(&thirdTimeoutError{errors.New("TIMEOUT")})
}

func main() {
	if err := sentry.Init(sentry.ClientOptions{
		Dsn: dsn,
	}); err != nil {
		println("sentry.Init failed")
	}
	defer sentry.Flush(5 * time.Second)

	foo()
	bar()
	blue()
}
```

Running the code would produce this:

<img width="437" alt="image" src="https://user-images.githubusercontent.com/10835824/118631303-a50ae500-b7cf-11eb-93b1-0978e3d59d2d.png">

You can see that only the struct types show up as the custom types.

### What you expected to happen

Expected the `errorString` in the screenshot to show up as `operationTimeoutError`.

**Comment by kamilogorek** [comment]
@BYK moved and fixed permissions issue

**Comment by rhcarvalho** [comment]
Hi, @ditek!

The distinction is caused by `error` being an interface type. In all three cases we report the concrete type provided by Go's `reflect` package.

https://github.com/getsentry/sentry-go/blob/af57dac8e824517652d918bd828ac23ac6b628df/client.go#L443

All concrete types in your example happened to be `struct`, but there's nothing special about structs, you can see:

![image](https://user-images.githubusercontent.com/88819/118863108-cc040c80-b8de-11eb-8861-8059c0d71ad1.png)

<details>

Your example changed with a few more types implementing the `error` interface:

```go
package main

import (
	"errors"
	"fmt"
	"time"

	"github.com/getsentry/sentry-go"
)

type (
	operationTimeoutError error
	anotherTimeoutError   struct {
		msg string
	}
	thirdTimeoutError struct{ error }
	stringError       string
	intError          int
	chanError         chan bool
)

var errOperationTimeout operationTimeoutError = errors.New("TIMEOUT")

func (e *anotherTimeoutError) Error() string {
	return e.msg
}

func (e stringError) Error() string {
	return string(e)
}

func (e intError) Error() string {
	return fmt.Sprint(int(e))
}

func (e chanError) Error() string {
	return fmt.Sprint((chan bool)(e))
}

func foo() {
	sentry.CaptureException(errOperationTimeout)
}

func bar() {
	sentry.CaptureException(&anotherTimeoutError{"TIMEOUT"})
}

func blue() {
	sentry.CaptureException(&thirdTimeoutError{errors.New("TIMEOUT")})
}

func main() {
	if err := sentry.Init(sentry.ClientOptions{}); err != nil {
		panic("sentry.Init failed")
	}
	defer sentry.Flush(5 * time.Second)

	foo()
	bar()
	blue()
	sentry.CaptureException(stringError("Hello"))
	sentry.CaptureException(intError(404))
	sentry.CaptureException(make(chanError))
}
```

</details>

**Comment by ditek** [comment]
I see. Thanks for the explanation.
