### ISSUE TITLE
Provide possibility to manipulate Stacktrace

### ISSUE THREAD

**Issue by glower** [getsentry/sentry-go#35]
Hi,

with the old `raven` client it was possible to manipulate stack to remove useless caller information (like frameworks, hooks, middleware, ...). With the new client, I can't find how to achieve the same:
```	
stack := raven.NewStacktrace(1, 3, nil)
exc := raven.NewException(err, stack)
```
Please provide the possibility for working with stacktrace, or document how to do this with the current lib.
Thank you!

**Comment by kamilogorek** [comment]
Hey, there's no direct way to do this anymore, however, what we expose instead are custom integrations and `beforeSend` callback that let you manipulate events in any way you need.

Here's an example of integration that enhances events with context lines, which you can base your code on, and use it to filter some frames instead - https://github.com/getsentry/sentry-go/blob/b1d347bb2ed05896d4a570a0a15c25a0d25c4c81/integrations.go#L264

And you use it by appending an instance to `Integrations` config attribute - https://github.com/getsentry/sentry-go/blob/b1d347bb2ed05896d4a570a0a15c25a0d25c4c81/example/basic/main.go#L141-L143

If you want to do it directly inside `Init` call, use `BeforeSend` like this - https://github.com/getsentry/sentry-go/blob/b1d347bb2ed05896d4a570a0a15c25a0d25c4c81/example/basic/main.go#L121-L129

Every `Event` contains all frame caught error frames and you can freely modify them before event goes to the transport for delivery, thus you can write simple filter functions to get rid of unwanted frames.

**Comment by glower** [comment]
Cool, thank you for the answer, that will help me. I think the API is clearer that way

**Comment by kamilogorek** [comment]
Awesome! Thanks :)
