### ISSUE TITLE
Concurrency issue when the hub is already set on the request's context

### ISSUE THREAD

**Issue by victorhurdugaci** [getsentry/sentry-go#358]
## Summary

Based on the documentation around [Concurrency for Go](https://docs.sentry.io/platforms/go/concurrency/), each HTTP request should get its own hub since each of them runs in a different goroutine.

However, the code here: https://github.com/getsentry/sentry-go/blob/aed9115503d3bc31fd9be452423831c2bc7d19c7/http/sentryhttp.go#L85-L88

creates a new hub only if the hub is not set on the context. If it's already set (e.g. by a previous middleware) it will reuse it and will lead to some strange behavior when two requests run at the same time and they both modify the scope.

My 2c is that the `sentryhttp` middleware should always clone the hub, not only when it's not set, to avoid these race conditions. What do you folks think?

**Comment by rhcarvalho** [comment]
The idea is that if your own middleware puts a Hub on the context, it should do so by creating/cloning a new one for every request, in order to have request data separation.

What strange behavior are you running into? Anything we could help you with?

Cheers

**Comment by victorhurdugaci** [comment]
It's a fair ask for the other middleware to clone it. I was just surprised by the behavior because we were using the global sentry instance and when we switched to a custom one, it broke since parallel requests were all updating the same hub.
