### ISSUE TITLE
Proposal: Add `OnTransportErrorCallback`

### ISSUE THREAD

**Issue by Russiancold** [getsentry/sentry-go#372]
## Summary. 
I want to get an ability to monitor cases when sentry is unavailable

## Motivation. 
Sentry might be crucial for service monitoring. It would be good to know about problems with network connection

## Additional Context

I'm proposing to add `OnTransportErrorCallback` Option to allow users to set some action when any transport error occurs.

**Comment by rhcarvalho** [comment]
Hi @Russiancold! This feature request is a duplicate of https://github.com/getsentry/sentry-go/issues/270.

I've proposed using a custom `http.RoundTripper` and that's still my current recommendation.

We have an example at https://pkg.go.dev/github.com/getsentry/sentry-go#example-package-TransportWithHooks.
