### ISSUE TITLE
Add option for setting stack skip

### ISSUE THREAD

**Issue by mfridman** [getsentry/sentry-go#38]
Often times in larger applications one will use wrappers around loggers, alerters, mailers, etc.  to not tie the application code to a specific implementation.

As a crude example..

```go
func (a *alertWrapper) Error(err error) error {
	sentry.CaptureException(err)
	return err
}
```

In sentry the first stackframe will always report the wrapper code as the caller, followed by subsequent frames which we are actually interested in.

Instead of the approach outlined in #35 would you consider adding an option to directly skip n number of frames. 99% of the time it'd likely be 1, but this would make the API slightly more generous :)

**Comment by kamilogorek** [comment]
Tbh I don't want to pile up more and more options, especially that with ones like this, that work globally and are based on specific assumptions (eg. that your errors will _always_ start with this frame), it's very easy to shot yourself in the foot. If it removed the frame incorrectly, you'll lose the most important information.

Here's copy-paste solution for your needs :)

```go
func filterAlertWrapperFrames(frames []sentry.Frame) []sentry.Frame {
	filteredFrames := make([]sentry.Frame, 0, len(frames))
	for _, frame := range frames {
		if strings.Contains(frame.Module, "alertWrapper") {
			continue
		}
		filteredFrames = append(filteredFrames, frame)
	}
	return filteredFrames
}

func filterAlertWrapper(event *sentry.Event) *sentry.Event {
	for _, ex := range event.Exception {
		if ex.Stacktrace == nil {
			continue
		}
		ex.Stacktrace.Frames = filterAlertWrapperFrames(ex.Stacktrace.Frames)
	}
	// This interface is used when we extract stacktrace from caught strings, eg. in panics
	for _, th := range event.Threads {
		if th.Stacktrace == nil {
			continue
		}
		th.Stacktrace.Frames = filterAlertWrapperFrames(th.Stacktrace.Frames)
	}
	return event
}

func main() {
	sentry.Init(sentry.ClientOptions{
		Dsn:   "",
		BeforeSend: func(event *sentry.Event, hint *sentry.EventHint) *sentry.Event {
			return filterAlertWrapper(event)
		},
	})
}
```

We might think about `FramesProcessor` or some similar option that'd let you write basically just that:

```go
if strings.Contains(frame.Module, "alertWrapper") {
		continue
}
filteredFrames = append(filteredFrames, frame)
```

and it'd still work, but till now, it's still possible with just a few more lines of code.

Cheers!
