### ISSUE TITLE
Feat: another API like `ContinueFromRequest` but allow parameter (not http.Request)

### ISSUE THREAD

**Issue by yeqown** [getsentry/sentry-go#387]
## Summary

another API like `ContinueFromRequest` but allow a different parameter (not `http.Request`)

## Motivation

support trace information transfer across process bwtween different protocols

## Additional Context

maybe looks like: 

```go
func ContinueFromXXXX(trace string) SpanOption {
	return func(s *Span) {
		if trace == "" {
                        return
                 }
		s.updateFromSentryTrace([]byte(trace))
	}
}
```

**Comment by cleptric** [comment]
Fixed in v0.14.0 via https://github.com/getsentry/sentry-go/pull/434
