### ISSUE TITLE
Suppress structured context

### ISSUE THREAD

**Issue by mfridman** [getsentry/sentry-go#39]
Is it possible to suppress the default contexts set when preparing an event?

I couldn't find (or missed) if this is possible from the docs:

https://docs.sentry.io/enriching-error-data/context/?platform=go

https://github.com/getsentry/sentry-go/blob/8f1abfd73947517f4344066cc9314814b126fa40/client.go#L379-L388

E.g., I created a wrapper around sentry 

```go
func (a *alertWrapper) Error(err error) error {
	hub := sentry.CurrentHub().Clone()
        hub.ConfigureScope(func(scope *sentry.Scope) {

        }
}
```

I can set tags and new contexts inside the `ConfigureScope` closure, but, is it possible to remove or modify underlying contexts to alter what appears in the GUI?

<img width="639" alt="Screen Shot 2019-07-27 at 10 02 05 PM" src="https://user-images.githubusercontent.com/6278244/62001255-7aabdd00-b0ba-11e9-8794-e94ce57300b8.png">

**Comment by kamilogorek** [comment]
Yes, but not all of them. Eg. the one you linked there, no, as it's the data important for the data collection to work correctly (we need to be able to somehow filter, group and tag events). Unless you remove it using `BeforeSend` callback, which you can do, but you shouldn't :P

However, device and runtime are not in the core SDK code, they are separate integrations that you can remove: https://github.com/getsentry/sentry-go/blob/8f1abfd73947517f4344066cc9314814b126fa40/integrations.go#L167-L201

See: https://docs.sentry.io/platforms/go/config/#removing-default-integrations

**Comment by kamilogorek** [comment]
Also if you want to do it per-scope, you can use event processors: https://github.com/getsentry/sentry-go/blob/24bba70a9ee3a6f3c46d6dde1bbdf0d7517b6251/scope.go#L209-L214

```go
func (a *alertWrapper) Error(err error) error {
	hub := sentry.CurrentHub().Clone()
	hub.ConfigureScope(func(scope *sentry.Scope) {
		scope.AddEventProcessor(func(event *sentry.Event, hint *sentry.EventHint) *sentry.Event) {
			// modify event here, for example:
			delete(event.Context, "device")
			return event
		})
	}
}
```

**Comment by mfridman** [comment]
Thanks!

I went with the first option in the `Init` function, by removing the `"Environment"` integration, which left us with: message, exception, user, additional data and sdk.

Is it possible to remove the User (which only shows IP Address)? This isn't really useful for a BE service buried deep inside the infra with ELBs and proxies.

---

I couldn't get the latter approach to work, possibly due to misuse of the API. (migrating from raven-go)

Here is a crude implementation (once called we assume no further context will be passed and this event should end up in sentry)

```
type alertWrapper struct {
	hub *sentry.Hub
}
```

https://gist.github.com/mfridman/31e88e50b48680fad8ebb0ae3fb77e57

I tried calling `hub.ConfigureScope` after cloning the hub but could not get the "device" removed through modification of this scope. (not because of the typos in the above response 😛 )

**Comment by kamilogorek** [comment]
> Is it possible to remove the User (which only shows IP Address)?

It's extracted from the request headers on the server. You can turn it off in your project's settings.

![image](https://user-images.githubusercontent.com/1523305/62043890-dc2a9380-b201-11e9-8e9d-3d1b373adfdf.png)

> I couldn't get the latter approach to work, possibly due to misuse of the API. (migrating from raven-go)

No, it's due to me forgetting that order of processors execution is inversed... created issue to track this - https://github.com/getsentry/sentry-go/issues/40 Sorry about that 😅

(you can still do this in `BeforeSend` callback)

**Comment by mfridman** [comment]
> Unless you remove it using BeforeSend callback, which you can do, but you shouldn't :P

It almost seems users shouldn't be able to modify the necessary bits for "data collection to work correctly".

If SDK (and others)  are hard requirement the Go SDK client shouldn't enable accidental misuse.

We prefer to display less items to declutter the UI and instead augment relevant bits through the `Extra` fields ("Additional Data").

@kamilogorek thanks for the support. Feel free to close this issue. And keep up the great job.

**Comment by kamilogorek** [comment]
>If SDK (and others) are hard requirement the Go SDK client shouldn't enable accidental misuse.

They are not hard requirements per-se, as event will still be delivered. It'll just make it impossible to search using `platform:go` for example. But everything else will still work just fine :)

And we allow to do everything you want, because our platform is also open-source, therefore some users may fork it and change the shape of the event to their needs, and SDK should allow to follow that as well.

> @kamilogorek thanks for the support. Feel free to close this issue. And keep up the great job.

Thanks!
