### ISSUE TITLE
Please support StackTraces which return a slice of `runtime.Frame`

### ISSUE THREAD

**Issue by kat-co** [getsentry/sentry-go#391]
I am working with an errors package that reports a stack trace as a slice of `runtime.Frame`. Sentry does not look for the `PC` [field](https://cs.opensource.google/go/go/+/refs/tags/go1.17.3:src/runtime/symtab.go;l=31) which `runtime.Frame` contains:

https://github.com/getsentry/sentry-go/blob/bd116d6ce79b604297c6497aa07d7ac01768adbb/stacktrace.go#L123-L127

This makes utilizing `sentry.ReportException` less useful in this case since it will only generate a new stacktrace from the place `sentry.ReportException` was called.

Thank you!

**Comment by kat-co** [comment]
Apologies, I need to rebase this off of the last release. I'm closing this PR in favor of another.

**Comment by rhcarvalho** [comment]
Hi @kat-co, is the error package you're working with publicly available?

**Comment by kat-co** [comment]
Sorry, @rhcarvalho, it is not. I think the salient bit is that our error type satisfies this interface:
```go
type MyError interface {
  StackTrace() []runtime.Frame
}
```

If it helps, I can tell you that a fork of `sentry-go` with the addition of my commit has been running in production for a few weeks now and is working well.
