### ISSUE TITLE
Improvement on Go SDK example

### ISSUE THREAD

**Issue by albert-csms** [getsentry/sentry-go#397]
In the [Usage](https://docs.sentry.io/platforms/go/guides/http/#usage) example, there is a function `ServeHTTP`, but it's not used. I am aware that there is a [complete example](https://github.com/getsentry/sentry-go/blob/master/example/http/main.go), but the two examples vary quite a bit. As someone new to Go, it would be nice to see how `ServeHTTP` is being used in the example. If warranted, I'd be more than happy to make the commit.

**Comment by rhcarvalho** [comment]
Welcome to Sentry and welcome to the Go community!

The `ServeHTTP` function/method is a special name. Adding a method like that to type makes it implement the [`http.Handler`](https://pkg.go.dev/net/http#Handler) interface.

The package `net/http` in Go's standard library uses that to serve HTTP requests.

In the example, calls to `http.Handle` and `http.HandleFunc` register functions that will be called to handle request to given URL patterns, and [`http.ListenAndServe(someAddr, nil)`](https://pkg.go.dev/net/http#ListenAndServe) starts an HTTP server listening at `someAddr` and dispatches requests to the previously registered functions.

There's an overview right at the top of the documentation for the `net/http` package at https://pkg.go.dev/net/http#section-documentation.

Please let us know if you have any feedback on how we could make the documentation better. Thank you!
