### ISSUE TITLE
remove other dependency

### ISSUE THREAD

**Issue by hidu** [getsentry/sentry-go#405]
## Summary

A basic SDK should have the least dependence.
But in go.mod, it requred too many other pkgs, these should be reduced.
eg:
```
github.com/gin-gonic/gin v1.4.0
github.com/kataras/iris/v12 v12.1.8
github.com/labstack/echo/v4 v4.5.0
...
```
these adapters should in a separate module

**Comment by rhcarvalho** [comment]
Closing as a duplicate of #156.
