### ISSUE TITLE
Store Endpoint Support

### ISSUE THREAD

**Issue by Integralist** [getsentry/sentry-go#406]
## Summary
Support for https://develop.sentry.dev/sdk/store/

## Motivation
Lots of applications I work on will typically send instrumentation data as JSON for richer parsing.

## Additional Context
I see that Sentry supports [accepting of JSON](https://develop.sentry.dev/sdk/store/) and so having this in the SDK means I don't have to figure out how to construct the request manually.

**Comment by rhcarvalho** [comment]
Hi @Integralist! Constructing and sending events (to the `/store` endpoint) is already what the SDK does through [`CaptureEvent`](https://pkg.go.dev/github.com/getsentry/sentry-go#CaptureEvent) and others. Is that what you were looking for?

**Comment by Integralist** [comment]
@rhcarvalho thanks for the reply. 

I'm looking for the simplest way to send JSON data to Sentry (as I have very structured data that I would like to collect and analyse). Would `CaptureEvent` be the most appropriate way to achieve that?

**Comment by Integralist** [comment]
Ah, nvm. I managed to figure it out. I had a complex data structure that was tracking all errors in a single request flow and I was able to utilise `CaptureException` along with `AddBreadcrumb` to do what I needed.

**Comment by rhcarvalho** [comment]
Awesome!
