### ISSUE TITLE
RecoveryHandler from raven-go

### ISSUE THREAD

**Issue by MichaelSnowden** [getsentry/sentry-go#407]
## Summary

I'm migrating from raven-go to sentry-go. Is there something like raven-go's RecoveryHandler in sentry-go?

**Comment by rhcarvalho** [comment]
Hi @MichaelSnowden! Yes, the `net/http` integration package at [github.com/getsentry/sentry-go/http](https://pkg.go.dev/github.com/getsentry/sentry-go/http) captures panics and can optionally repanic after reporting to Sentry.

https://docs.sentry.io/platforms/go/migration/#nethttp

**Comment by rhcarvalho** [comment]
Closing as the answer above might be sufficient. Please write back if you need more help with the migration!

**Comment by MichaelSnowden** [comment]
Thanks!
