### ISSUE TITLE
Test client?

### ISSUE THREAD

**Issue by MichaelSnowden** [getsentry/sentry-go#409]
## Summary

I'd like the ability to instantiate a Sentry client which just records errors sent to it, but doesn't do anything else.

## Motivation

I want to do this to test that we're logging errors properly in our codebase.

**Comment by rhcarvalho** [comment]
In your tests, you can initialize Sentry with a custom `BeforeSend` function that keeps track of events and always returns `nil` to drop every event (nothing will be sent over the network and you can use a fake DSN if you like).

**Comment by MichaelSnowden** [comment]
Thanks! So does something like this seem correct? https://gist.github.com/MichaelSnowden/f51ff683785148758a65398564b16e3c

**Comment by rhcarvalho** [comment]
> Thanks! So does something like this seem correct? https://gist.github.com/MichaelSnowden/f51ff683785148758a65398564b16e3c

Yes, that looks good.

**Comment by MichaelSnowden** [comment]
Thanks for reviewing!
