### ISSUE TITLE
Update github.com/coreos/etcd v3.3.10+incompatible as it is an vulnerable dependency

### ISSUE THREAD

**Issue by Monis1** [getsentry/sentry-go#415]
## Steps To Reproduce

```go

```

### SDK
 - `sentry-go` version: 
 - Go version: 
 - Using Go Modules? [yes/no]

### Sentry
 - Using hosted Sentry in sentry.io? [yes/no]
 - Using your own Sentry installation? Version: 
 - Anything particular to your environment that could be related to this issue?

**Comment by kamilogorek** [comment]
Our package doesnt depend directly on this package, thus it can be updated by the consumer.
