### ISSUE TITLE
What is the minimum Sentry version supported with this API

### ISSUE THREAD

**Issue by mfridman** [getsentry/sentry-go#42]
What Sentry version(s) is this new SDK Go compatible with, e.g., 8.x.x, 9.x.x ?

**Comment by kamilogorek** [comment]
Every version down to 8.0.0. You may get some "unknown attribute" errors in the UI for some miscellaneous extra data, but core functionality like errors, stacktraces, tags, extra, users request will work just fine in all of them.

**Comment by kamilogorek** [comment]
(whoops, didnt mean to close it, wrong button 😅let me know if I should reopen)
