### ISSUE TITLE
sentry-go triggers xcode cli tools install on macos if a release is not set

### ISSUE THREAD

**Issue by ubergeek42** [getsentry/sentry-go#426]
## Summary

On macos, if the xcode dev tools are not installed and a release is not set in sentry, sentry triggers the xcode developer tools install workflow because it tries to invoke git. We encountered this on an upgrade from the old raven library to the new sentry-go library.

Based on the comment [here](https://github.com/getsentry/sentry-go/blob/c40f30a89cdda4cb59239f2f77466d3d4219de61/client.go#L148-L171) it appears invoking git is expected behavior, but it does not great things for macos users who are not developers/don't have the developer tools installed. Obviously we'll just set a release, but this is surprising behavior and took some digging to figure out why git was being invoked in the first place.

## Steps To Reproduce

Don't set the release attribute, then build a binary for macos and run it. Observe that you are prompted to install the xcode developer cli tools because git isn't installed.

## Expected Behavior

The app to run and not set a release, and no devtools prompts to appear.

### SDK
 - `sentry-go` version: v0.13.0
 - Go version: 1.12
 - Using Go Modules? [yes/no] yes

### Sentry
 - Using hosted Sentry in sentry.io? [yes/no] yes
 - Using your own Sentry installation? Version: 
 - Anything particular to your environment that could be related to this issue?

**Comment by cleptric** [comment]
I'm not a big fan of running commands on people's machines to fetch some stuff from git.
I'll talk with the team but I would rather see this removed.

**Comment by greywolve** [comment]
This should be fixed now in #737
