### ISSUE TITLE
SetContext is under documented

### ISSUE THREAD

**Issue by rkuska** [getsentry/sentry-go#427]
## Summary
SetContext function signature can be improved to make it clear to users that it only accept maps. Unless it is not a case and there is a bug to be fixed.

I searched the repository for usage but it seems the same (the tests are using the same approach as mine above). In [online documentation](https://docs.sentry.io/platforms/go/enriching-events/context/#structured-context) there is a following statement:

> The best practice to attach custom data is via structured contexts. A **context must always be a dictionary or map**, and its values can be arbitrary.

Why the function doesn't have in its signature that it accepts only `map[string]interface{}` but instead there is `interface{}`? Current signature seems counter-intuitive. 

Also, is there a way to enrich the context under a given key later? Right now the object under the key is being [overwritten](https://github.com/getsentry/sentry-go/blob/c40f30a89cdda4cb59239f2f77466d3d4219de61/scope.go#L216) so the namespace can't be enriched.

## Steps To Reproduce

```go
hub := sentry.CurrentHub().Clone()
hub.ConfigureScope(func(scope *sentry.Scope) {
	scope.SetContext("tx_type", batch.ttype)
	scope.SetContext("strategy", batch.strategy)
})
_ = hub.CaptureMessage("Message")
```

## Expected Behavior
Values to be rendered correctly.

## Screenshots

<img width="457" alt="Screenshot 2022-03-31 at 16 44 18" src="https://user-images.githubusercontent.com/1709417/161086683-247bcabf-c0ab-41f3-b895-23535cb6be67.png">

### SDK
 - `sentry-go` version:  	github.com/getsentry/sentry-go v0.12.0
 - Go version: 1.16
 - Using Go Modules? yes

### Sentry
 - Using hosted Sentry in sentry.io? Yes
 - Using your own Sentry installation? Version: 
 - Anything particular to your environment that could be related to this issue?

**Comment by cleptric** [comment]
Fixed in `v0.14.0` via https://github.com/getsentry/sentry-go/pull/444
