### ISSUE TITLE
Remove unnecessary dependency update while updating sentry SDK version

### ISSUE THREAD

**Issue by epikjjh** [getsentry/sentry-go#437]
## Summary
Current sentry-go has a dependency with [gin](https://github.com/getsentry/sentry-go/blob/master/go.mod#L6), so when we are going to update the sentry-go version, it requires an update of the proper gin version too.

However, by searching this repository, gin is only used for creating test & example codes.

## Motivation
When I update sentry SDK version from v0.11.0 to v0.13.0, I found out it requires an update for gin too.
However, updating gin version seems unnecessary to us since this is actually not used in sentry.
It seems to be a burden for users to consider unnecessary dependency updates.

Could you please consider this case? 🙏

**Comment by ghouscht** [comment]
This is true for all the "web-framework" dependencies. They should be removed from the main sentry-go library in my opinion. sentry-go is a library package and should have minimum dependencies. I use none of the sentry-go imported web frameworks so I don't want to have a dependency on them, but I'm forced to. :(

**Comment by ghouscht** [comment]
Unfortunately this is still a problem but this issue didn't get attention so far...
