### ISSUE TITLE
http.ErrAbortHandler error should be ignored in the HTTP recoverer middleware

### ISSUE THREAD

**Issue by VojtechVitek** [getsentry/sentry-go#448]
## Summary
Hi, we're receiving `http.ErrAbortHandler` error in Sentry. However, this net/http sentinel error is [defined as follows](https://pkg.go.dev/net/http#pkg-variables):

> var ErrAbortHandler = [errors](https://pkg.go.dev/errors).[New](https://pkg.go.dev/errors#New)("net/http: abort Handler")
>
> ErrAbortHandler is a sentinel panic value to abort a handler. While any panic from ServeHTTP aborts the response to the client, panicking with ErrAbortHandler also suppresses logging of a stack trace to the server's error log.

This error is thrown by `httputil.ReverseProxy` when the HTTP client simply disconnects early (before the response is flushed properly).

https://github.com/golang/go/blob/b2116f748a7acd32facdbbdaf40117ed40564083/src/net/http/httputil/reverseproxy.go#L360

http.Server handler is handling this sentinel panic error by its own, and it doesn't log the `panic()` to stdout.

I believe we could ignore these errors too by default instead of sending them to Sentry.

## Steps To Reproduce
1. Apply Sentry HTTP middleware.
2. Make a request that is reverse-proxied to another server.
3. Cancel the request mid-flight.

## Expected Behavior
No error is reported to Sentry

## Screenshots
![Screen Shot 2022-06-15 at 7 37 01 PM](https://user-images.githubusercontent.com/139342/173890467-142d09f0-9e95-40aa-a3f7-579804f420e0.png)

## Environment
Go 1.18.3 on any OS/architecture.

### SDK
 - `sentry-go` version: github.com/getsentry/sentry-go v0.13.0
 - Go version: 1.18.3
 - Using Go Modules? yes

### Sentry
 - Using hosted Sentry in sentry.io? yes

**Comment by VojtechVitek** [comment]
I'm happy to provide a fix if this makes sense.

**Comment by cleptric** [comment]
Did you try out to set [`ClientOptions.IgnoreErrors`](https://github.com/getsentry/sentry-go/blob/master/client.go#L131) when initializing the SDK?

**Comment by VojtechVitek** [comment]
@cleptric no, I haven't. This may help, thank you.

Even though, I'd prefer if Sentry accepted a list of sentinel errors `errors.Is(sentinelErr)` over the regex matching error strings. Errors strings can change over time. Is this something you'd consider?

Anyway, thanks for your help and feel feel to close.

**Comment by williambrode** [comment]
@VojtechVitek the IgnoreErrors actually match the name of the error class as well (as I understand it).  So if you just did `[]string{"sentinelErr"}` it should work.

FWIW I have the same issue.  And it would be nice if sentry ignored `http.ErrAbortHandler` by default, but I could see reasons why that might not always be desired.  For now I'm trying: `IgnoreErrors: []string{"ErrAbortHandler"},`
