### ISSUE TITLE
How to Set `Tags` for Trace?

### ISSUE THREAD

**Issue by ComputerComedian** [getsentry/sentry-go#461]

**Comment by smeubank** [comment]
Hi @ComputerComedian 

See here are docs about [enriching events](https://docs.sentry.io/platforms/go/enriching-events/tags/) and [custom instrumentation](https://docs.sentry.io/platforms/go/performance/instrumentation/custom-instrumentation/) for examples of `SetTag`

These docs might be lacking a bit, so please let us know if this does not answer your scenario, and apologies on the delay in response to your question!
