### ISSUE TITLE
Handler to support gorilla/mux router

### ISSUE THREAD

**Issue by cdignam-segment** [getsentry/sentry-go#468]
## Summary
The current net/http handler uses the [URL request path](https://github.com/getsentry/sentry-go/blob/33f7b6930327848cea5fdb2bdc65b5992632aef9/http/sentryhttp.go#L90) to define the transaction name of a request. A gorilla/mux handler could use mux's [`Route.GetPathTemplateAdd`](https://pkg.go.dev/github.com/gorilla/mux#Route.GetPathTemplate) method to define the transaction name.

## Motivation
Using a more consistent transaction name across requests will enable better issue grouping in the Sentry UI.

I'd make a PR for this if it would be accepted

## Additional Context
The go otel package uses this for their own middleware here:

https://github.com/open-telemetry/opentelemetry-go-contrib/blob/df16f32df86b40077c9c90d06f33c4cdb6dd5afa/instrumentation/github.com/gorilla/mux/otelmux/mux.go#L119-L130

**Comment by cleptric** [comment]
@cdignam-segment Sounds like a great idea to me. We're currently working towards Otel support in the SDK #486 but having a mux integration is something we would like to add as well 👍

**Comment by paambaati** [comment]
Now that OTEL support has landed, would you folks be willing to reconsider this?

**Comment by cleptric** [comment]
> The Gorilla project has been archived, and is no longer under active maintainenance.

https://github.com/gorilla/mux

We should hold off on adding a non-maintained integration to the Go SDK.
There seems to be an Otel package you could use instead.
https://pkg.go.dev/go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux
