### ISSUE TITLE
Is it possible to set a type of span to DB?

### ISSUE THREAD

**Issue by odannyc** [getsentry/sentry-go#481]
## Summary

The documentation suggests that some SDKs allow us to set some spans as `DB` type: https://docs.sentry.io/product/performance/filters-display/widgets/#slow-db-ops

But reading through the code it doesn't seem that sentry-go supports this.
Is it currently possible? If not, can we get this ability? Thanks

**Comment by kamilogorek** [comment]
Yes, it is possible, as a type (category) of span, is the first part of its operation name - https://develop.sentry.dev/sdk/performance/span-operations/#database

Thus `StartSpan`, which accepts `category` as its argument, can already set it - https://github.com/getsentry/sentry-go/blob/2503eee7cb11316861b52c5c68c6f364092c5d78/tracing.go#L41-L45

**Comment by odannyc** [comment]
I don't see `StartSpan` accept a `category`. This is the function signature in `master`:

https://github.com/getsentry/sentry-go/blob/master/tracing.go#L77

```go
func StartSpan(ctx context.Context, operation string, options ...SpanOption) *Span
```

Can you provide some sample code on how to set the category to database?

**Comment by kamilogorek** [comment]
Sorry for the confusion, I should say "which accepts `operation`" in my previous command.

When you call `StartSpan(ctx, 'db.query')`, Sentry translates it to `category=db, operation=query`.
