### ISSUE TITLE
[GO] Add basic OpenTelemetry support

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-go#486]
### Details
- SDK develop spec https://github.com/getsentry/develop/pull/686
- span processor - transforming OTEL spans into Sentry spans within Sentry transactions
  - span name and description
  - parent child relationships
- trace/context propagator - including DSC and trace context 
  - https://opentelemetry.io/docs/reference/specification/context/api-propagators/

## Reference
Ruby issues with initial implementation https://github.com/getsentry/sentry-ruby/issues/1907

**Comment by cleptric** [comment]
We should take a look at https://github.com/getsentry/sentry-go/issues/468 during

@smeubank The Go SDK currently does not support Dynamic Sampling.

**Comment by smeubank** [comment]
stay alive! :D
