### ISSUE TITLE
Update integrations & examples around performance monitoring

### ISSUE THREAD

**Issue by cleptric** [getsentry/sentry-go#496]
## Summary
With the addition of `StartTransaction`, we should update our integrations to support performance monitoring out of the box.

- [x] net/http
- [x] Echo
- [x] FastHTTP
- [x] Gin
- [x] Fiber
- [x] Iris
- [x] Negroni

We will also need to update or docs, I'll use this issue to track this work as well.

**Comment by uded** [comment]
Any progress with Gin? We are using custom code now, not a great way...

**Comment by aldy505** [comment]
Some updates:
- Echo: https://github.com/getsentry/sentry-go/pull/722
- Fasthttp: https://github.com/getsentry/sentry-go/pull/723
- Fiber: https://github.com/getsentry/sentry-go/pull/795

I'll do the rest next (Iris, Martini, Negroni), I haven't use them before but I'll give it a try.

**Comment by cleptric** [comment]
You can skip Martini. Will remove it, no updates for 8 years. https://github.com/go-martini/martini

**Comment by aldy505** [comment]
Great. Assign this to me, maybe? 😝

**Comment by cleptric** [comment]
PRs are welcome.
