### ISSUE TITLE
For Gin Middleware: Scope Modification Only Works with Events Like Message/Error, Fails with Transaction

### ISSUE THREAD

**Issue by Aberd33n** [getsentry/sentry-go#499]
Use the example from https://github.com/getsentry/sentry-go/tree/master/gin

Set appending tags or some other scope changes via the router like the code below:

```go
app.Use(func(ctx *gin.Context) {
    if hub := sentrygin.GetHubFromContext(ctx); hub != nil {
        hub.Scope().SetTag("someRandomTag", "maybeYouNeedIt")
    }
    ctx.Next()
})
```

The scope chagne only works with CaptureMEssage or Exception, and not works on Trasnactions.

So for the transactions, any solutions?

**Comment by cleptric** [comment]
Use `SetTag` on the transaction.

https://github.com/getsentry/sentry-go/blob/b31dec1f53a6e0b4b51a6a905793675223828d56/tracing.go#L197

Currently, we do not take the current `scope` into account when creating the event from a transaction.

**Comment by xinxiaoxian** [comment]
@cleptric @Aberd33n Maybe it's caused by context key, the Gin middleware and the Sentry core SDK use different context key, such it got different Hub for Event and Transaction.

**Comment by cleptric** [comment]
The gin integration has its own function to receive the correct context

https://github.com/getsentry/sentry-go/blob/b31dec1f53a6e0b4b51a6a905793675223828d56/gin/sentrygin.go#L91

When cloning the hub, the scope gets cloned as well, so this should work.
