### ISSUE TITLE
captureException not linking to trace

### ISSUE THREAD

**Issue by ImDevinC** [getsentry/sentry-go#502]
## Summary
When creating a transaction and a trace and then doing `sentry.CaptureException(err)`, the error is not linked to the trace properly.

## Steps To Reproduce
```go
func TestTracing(t *testing.T) {
	err := sentry.Init(sentry.ClientOptions{
		Dsn:              os.Getenv("SENTRY_DSN"), // test-project
		Debug:            true,
		TracesSampleRate: 1.0,
		Release:          "development",
	})
	if err != nil {
		t.Error(err)
	}
	ctx := context.Background()
	defer sentry.Flush(2 * time.Second)
	transaction := sentry.StartTransaction(ctx, "TestTracing", sentry.OpName("function"))
	defer transaction.Finish()
	span := transaction.StartChild("function")
	defer span.Finish()
	err = errors.New("this is an error")
	sentry.CaptureException(err)
}

```

## Expected Behavior
When viewing the issue on sentry.io, the exception should have a link to the relevant trace. When viewing the trace, the exception should be shown in the trace view.

## Screenshots
![image](https://user-images.githubusercontent.com/3997333/203859637-5a460522-94b3-414a-a880-c5ac295d2f4c.png)
![image](https://user-images.githubusercontent.com/3997333/203859656-6796e1d1-d3ec-4fbc-bb02-4d2f5ddf6b64.png)

## Sentry.io Event
Error Event: 120248f44d174a1a8d2a60073153e75a
Trace Event: 7b8eaba5361f4c698e79508fa6af68f4

### SDK
 - `sentry-go` version: `v0.15.0`
 - Go version: `1.19.3`
 - Using Go Modules? `yes`

### Sentry
 - Using hosted Sentry in sentry.io? `yes`

**Comment by cleptric** [comment]
Thanks for writing in.
I do confirm that the error event sent to Sentry does indeed not contain the missing `contexts.trace` values to make the link between the transaction and error work.

I'll take a look!

**Comment by ImDevinC** [comment]
Thanks! Let me know if I can provide any more information to help

**Comment by ImDevinC** [comment]
For clarification, this seems to work just fine
```
func TestTracing(t *testing.T) {
	err := sentry.Init(sentry.ClientOptions{
		Dsn:              "https://500ec0d1c287437da8165c0a4833054f@o4504167699382272.ingest.sentry.io/4504169589309440",
		Debug:            true,
		TracesSampleRate: 1.0,
		Release:          "development",
	})
	if err != nil {
		t.Error(err)
	}
	ctx := context.Background()
	defer sentry.Flush(2 * time.Second)
	span := sentry.StartSpan(ctx, "function", sentry.TransactionName("TestTracing"))
	defer span.Finish()
	childspan := sentry.StartSpan(span.Context(), "function")
	defer childspan.Finish()
	err = errors.New("this is an error")
	sentry.CaptureException(err)
}
```

**Comment by cleptric** [comment]
@ImDevinC I opened a PR to get this fixed. This might take a while to get released, for the moment I suggest using `StartSpan` instead.
