### ISSUE TITLE
Please don't tie sentry-go to gin version

### ISSUE THREAD

**Issue by eric** [getsentry/sentry-go#503]
We are currently pinned to a specific version of gin and that is preventing us from upgrading from sentry-go 0.13 to 0.15. It would be nice if sentry-go allowed us to update sentry-go without our gin dependency.

**Comment by cleptric** [comment]
This came up in the past in https://github.com/getsentry/sentry-go/issues/156.
We are very aware of this issue, but I can't give you a timeline for moving our integrations into their own modules.

May I ask which version of Gin you're using? We might look into lowering the required version to unblock you if the versions below `1.8.1` do not contain any security issues.

**Comment by eric** [comment]
We’re on 0.13 right now.

**Comment by cleptric** [comment]
I meant the version of Gin you're using 🙂

**Comment by eric** [comment]
Oh sorry. Looks like we’re on v1.7.7
