### ISSUE TITLE
Breaking change from v0.15.0 to v0.16.0

### ISSUE THREAD

**Issue by Pawda** [getsentry/sentry-go#514]
## Summary
After upgrading sentry from version v0.15.0 to version v0.16.0, tracing is not enabled by default.
This is due to the introduction of `EnableTracing` clientOption property.

## Steps To Reproduce
Update packages 
eg. `go get -u ./...`

## Expected Behavior
Either:
- No change to tracing is expected as long as `TracesSampleRate` is greater than 0.0
- An explicit comment next to `EnableTracing` specifying this is the new behavior.

### SDK
 - `sentry-go` version: v0.16.0
 - Go version: 1.19.3
 - Using Go Modules? yes

### Sentry
 - Using hosted Sentry in sentry.io? yes

**Comment by cleptric** [comment]
I was hoping the extra effort that went into the changelog made this more visible.

https://github.com/getsentry/sentry-go/releases/tag/v0.16.0

**Comment by Pawda** [comment]
@cleptric Oh... My bad for having missed that one. I was actually looking for such changelog from the readme...
The Readme is pointing to: https://pkg.go.dev/github.com/getsentry/sentry-go?tab=versions which does not include the details.

Thank you for the link, the efforts are greatly appreciated !

**Comment by cleptric** [comment]
I opened #515 to update the link. The changelog on pkg.go.dev is, well, not very useful indeed 😬
