### ISSUE TITLE
No http headers are sent if `ClientOptions.SendDefaultPii` is set to false

### ISSUE THREAD

**Issue by ikorihn** [getsentry/sentry-go#523]
## Summary
`SendDefaultPii` option was added in #485 .
This option behaves as follows:
- client is not nil and SendDefaultPii is true -> all headers are sent
- client is not nil and SendDefaultPii is false -> no headers are sent
- client is nil -> headers without sensitive data are sent

Is this expected behaviour?
In case of other language, it looks like all http headers except sensitive headers are sent when `SendDefaultPii` is false.

sentry-python:
https://github.com/getsentry/sentry-python/blob/2f67f12e405f8a6f89418d96071158367fcf516f/sentry_sdk/integrations/_wsgi_common.py#L160

sentry-spring:
https://github.com/getsentry/sentry-java/blob/8ade22549f328b48fd01aea726141f7186f3bd65/sentry-spring/src/main/java/io/sentry/spring/SentryRequestResolver.java#L33

## Steps To Reproduce

```go
func Run(addr string) error {
	_ = sentry.Init(sentry.ClientOptions{
		SendDefaultPII: false,
	})
	defer sentry.Flush(2 * time.Second)

	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()
		hub := sentry.GetHubFromContext(ctx)

		hub.CaptureMessage("my message")
	})

	handler := sentryhttp.New(sentryhttp.Options{}).Handle(http.DefaultServeMux)
	return http.ListenAndServe(addr, handler)
}
 ```

## Expected Behavior
When `ClientOptions.SendDefaultPii` is false, http headers except sensitive data are sent.
I made a PR #524 .

### SDK
- sentry-go version: v0.16.0
- Go version: 1.19
- Using Go Modules? yes

### Sentry
 - Using hosted Sentry in sentry.io? yes

**Comment by cleptric** [comment]
> - client is not nil and SendDefaultPii is true -> all headers are sent
> - client is not nil and SendDefaultPii is false -> no headers are sent

Correct.

> - client is nil -> headers without sensitive data are sent
In this case, nothing should be sent actually.

**Comment by cleptric** [comment]
@ikorihn fixed in https://github.com/getsentry/sentry-go/releases/tag/v0.17.0

**Comment by ikorihn** [comment]
Thanks for review!
