### ISSUE TITLE
Sentry client crashes entire process with "concurrent map writes" due to unsynchronized contextifyFramesIntegration

### ISSUE THREAD

**Issue by james-johnston-thumbtack** [getsentry/sentry-go#55]
We are attempting to use the same Sentry client in a server with many goroutines, as we assumed this client was thread-safe.  However, we're getting "concurrent map writes" errors.

1. Is the Sentry client intended to be thread-safe?  Specifically, is it intended to be safe to concurrently send events to the client returned by `sentry.NewClient`?

1. If yes, then we have found a bug: the `contextifyFramesIntegration` in `integrations.go` is not thread-safe.  In particular, it has a `cachedLocations` variable which is a map, and access to this variable is not synchronized.  We're getting stack traces from the concurrent map writes errors that point to reads/writes of this map.

I noticed that `sourceReader` has a similar caching mechanism, but that one is protected by a mutex....

We're using the Sentry client from commit 510f01e3c1e95d434331b518fdc62b2adaf5cff8, but I don't see anything fixed in the latest master, either.

**Comment by kamilogorek** [comment]
@james-johnston-thumbtack thanks for the report. I'll try to investigate it this week.
