### ISSUE TITLE
`TracesSamplerFunc` seems to be gone

### ISSUE THREAD

**Issue by muety** [getsentry/sentry-go#551]
After upgrading from `0.15.0` to `0.17.0`, I'm getting these compile time errors:

```
config/sentry.go:114:25: undefined: sentry.TracesSamplerFunc
config/sentry.go:128:19: undefined: sentry.UniformTracesSampler
config/sentry.go:130:18: undefined: sentry.UniformTracesSampler
```

Here's an excerpt from my code:

```go
TracesSampler: sentry.TracesSamplerFunc(func(ctx sentry.SamplingContext) sentry.Sampled {
	hub := sentry.GetHubFromContext(ctx.Span.Context())
	txName := hub.Scope().Transaction()

	for _, ex := range excludedRoutes {
		if strings.HasPrefix(txName, ex) {
			return sentry.SampledFalse
		}
	}
	if txName == "POST /api/heartbeat" {
		return sentry.UniformTracesSampler(config.SampleRateHeartbeats).Sample(ctx)
	}
	return sentry.UniformTracesSampler(config.SampleRate).Sample(ctx)
}),
```

`TracesSamplerFunc` and `UniformTracesSampler` seem to not be existing anymore, even though still mentioned [in the docs](https://docs.sentry.io/platforms/go/performance/).

**Comment by tonyo** [comment]
Yes, there was a breaking change in 0.16.0 related to `TracesSampler`: https://github.com/getsentry/sentry-go/blob/master/CHANGELOG.md#0160

We'll need to update the docs to reflect that. Thanks for reporting!

**Comment by muety** [comment]
Awesome, thanks! I was looking for an "upgrade notice" in the release notes, but couldn't even find release 0.16.0. Changelog helps though.

**Comment by tonyo** [comment]
Huh, the releases seem to be out of order on [the release page](https://github.com/getsentry/sentry-go/releases), which seems to be a [known GitHub bug](https://github.com/community/community/discussions/8226) 🤔 

Just in case, here are the 0.16.0 release notes: https://github.com/getsentry/sentry-go/releases/tag/v0.16.0

**Comment by cleptric** [comment]
@muety Thanks for reporting this, I updated our docs.
