### ISSUE TITLE
[OTel] Expose context-aware methods for capturing events in public API

### ISSUE THREAD

**Issue by tonyo** [getsentry/sentry-go#555]
Extracted from https://github.com/getsentry/sentry-go/pull/537.

### Problem

Associating errors with transactions is generally implemented (see `otel/event_processor.go`), but there's a caveat: the `EventHint` of the event processor has to contain a valid Context with a set OpenTelemetry span. This means that e.g. messages captured with `sentry.CaptureMessage` or `hub.CaptureMessage` won't be linked to Sentry spans at the moment.

So to properly link the raised exception now users have to do things like:

```go
	client := sentry.CurrentHub().Client()
	client.CaptureException(
		errors.New("test sentry exception"),
		&sentry.EventHint{Context: ctx},
		nil,
	)
```

### Proposed Solution

We might want to expose methods like `CaptureMessageWithContext(ctx context.Context, message string)` and others that also take a `ctx` parameter. Under the hood, they would set add the passed `ctx` to `EventHint`.

**Comment by vtfr** [comment]
I'm currently wrapping my `TraceProvider`, `Tracer` and `Span` with custom logic to accommodate these caveats, so I can keep using the OTEL API, but I feel having to maintain these workarounds is a big no-no.

**Comment by LesDomen** [comment]
I am very interested in implementing this feature. Anything I should know or pay special atention to?

**Comment by ProjectIcarusX** [comment]
This sounds like a smart request and also geared towards increasing interoperability with industry standards such as open telemetry. Would be really helpful to have such a feature and make Sentry even more useful with other tools.

Hoping it might get reopened and thought about.

The implementation doesn't look too complicated based on what @LesDomen already proposed.
