### ISSUE TITLE
Make writing default sentry properties optional

### ISSUE THREAD

**Issue by SupaHam** [getsentry/sentry-go#571]
## Summary
There should be a way to disable the forceful nature of some sentry defaults being inserted for transactions

## Motivation
#570 is an issue with concurrent writes caused by sentry's transaction submission code. SDK tries to be useful and inserts data which isn't accurate to the context of the user. In our case we have access to device model but not CPU, arch etc, (which we don't have access to) so sentry will insert that automatically, but it ends up crashing the application instead. Crash rate is low, but still non-zero and that shouldn't be acceptable from a library of error reporting tools.

**Comment by cleptric** [comment]
You can overwrite which integrations are applied by passing `ClientOptions.Integrations` during the SDK init.

```go
sentry.Init(sentry.ClientOptions{
	Integrations: func(integrations []sentry.Integration) []sentry.Integration {
		var filteredIntegrations []sentry.Integration
		for _, integration := range integrations {
			if integration.Name() == "Environment" {
				continue
			}
			filteredIntegrations = append(filteredIntegrations, integration)
		}
		return filteredIntegrations
	},
})
```

**Comment by SupaHam** [comment]
Alright, thanks.
