### ISSUE TITLE
Invalid transaction source: echo

### ISSUE THREAD

**Issue by jjbayer** [getsentry/sentry-go#588]
## Summary
Relay is reporting an invalid transaction source emitted by the Go SDK version 0.17.0. If this was fixed in >= 0.18.0, feel free to close this issue.

```json
"sdk": {
    "name": "sentry.go",
    "version": "0.17.0",
    "integrations": [
        "ContextifyFrames",
        "Environment",
        "IgnoreErrors",
        "Modules"
    ],
    "packages": [
        {
            "name": "sentry-go",
            "version": "0.17.0"
        }
    ]
},
"transaction_info": {
    "source": "echo"
}
```

## Steps To Reproduce
Go to https://sentry.my.sentry.io/organizations/sentry/issues/391873, and use the `project` tag to find example events in that project.

## Expected Behavior
The SDK sends one of the transaction sources listed in 
https://develop.sentry.dev/sdk/event-payloads/transaction/#transaction-annotations.

### SDK
See JSON snippet

### Sentry
 - Using hosted Sentry in sentry.io? yes

**Comment by tonyo** [comment]
Looks like we should add additional guards in places where we set transaction sources from external inputs, e.g.
* https://github.com/getsentry/sentry-go/blob/master/tracing.go#L774

**Comment by cleptric** [comment]
We would also need to not export the `Span.Source` field then. Adding a getter/setter seems reasonable.
