### ISSUE TITLE
OTel Context Missing

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-go#596]
## Summary
Events sent to Sentry which were converted from OTel spans, should have an OTel context with attributes and other data sourced from OTel SDKs. It appears that some events do not have this. 

[Python event with context](https://sentry-sdks.sentry.io/performance/otel-demo-recommendationservice:0394771c82c54ec3890da6659659ae9b/?project=4504259429859328&query=&referrer=performance-transaction-summary&statsPeriod=14d&transaction=%2Fhipstershop.RecommendationService%2FListRecommendations&unselectedSeries=p100%28%29#context-otel)

<img width="845" alt="image" src="https://user-images.githubusercontent.com/47563310/223389391-71fe745f-19e6-4ca7-acd7-f0c68b01ec91.png">

[Go event without context](https://sentry-sdks.sentry.io/performance/otel-demo-accountingservice:274d0f0e4cbb4813995dd4234394d160/?project=4504536076582912&query=&referrer=performance-transaction-summary&statsPeriod=14d&transaction=orders+receive&unselectedSeries=p100%28%29)

Develop Spec: [Add OpenTelemetry Context](https://develop.sentry.dev/sdk/performance/opentelemetry/#step-5-add-opentelemetry-context)

## Expected Behavior
OTel SDK data populated in the OTel context and appearing in the product on the transaction detail page

### SDK
 - `sentry-go` with OTel Go SDKs

**Comment by AbhiPrasad** [comment]
Why did we re-open?

**Comment by cleptric** [comment]
So this is about "OTel Context Missing", and as we currently always get an empty Hub here https://github.com/getsentry/sentry-go/blob/master/otel/span_processor.go#L120-L123, so even with #599 being merged, it won't work just yet.

**Comment by AbhiPrasad** [comment]
Alright I will push up a PR then!
