### ISSUE TITLE
Package source code in Sentry

### ISSUE THREAD

**Issue by enumag** [getsentry/sentry-go#598]
## Summary

I successfully set up Sentry for my project and can see the errors there including stack traces.
However while for my own code I can click and show a piece of the code around the line, the same isn't possible for the stack trace lines that point to a package - the first 7 lines in the screenshot are missing the toggling arrow on the right.

![Screenshot from 2023-03-07 13-44-02](https://user-images.githubusercontent.com/539462/223427340-b9e30b05-a912-4ae2-8f34-1f0521231d18.png)

Is it possible to setup sentry in a way that the source code from packages would be available there as well?

## Motivation

It would help understanding the context of the error.

**Comment by cleptric** [comment]
Have a look at https://docs.sentry.io/platforms/go/troubleshooting/#missing-stack-trace on how to enable source contexts. 
Refs #177

**Comment by cleptric** [comment]
Sorry, I miss-read the issue.

**Comment by enumag** [comment]
Why was the backlog tag removed? This would be very useful.

**Comment by cleptric** [comment]
Tbh, I don't think we can actually fetch the source code for 3rd party packages easily, and if we do so, it might be too cumbersome to setup. Closing for now.
