### ISSUE TITLE
Add debug logging for dropped packets due to "full request buffer" and configurable buffer size.

### ISSUE THREAD

**Issue by christian-ehmig** [getsentry/sentry-go#6]
I suggest to add logging here (via Logger) https://github.com/getsentry/sentry-go/blob/v0.0.1-beta/transport.go#L97 - otherwise there is no info about dropped packets when using debug mode. Dropped packets are just logged as being sent in https://github.com/getsentry/sentry-go/blob/v0.0.1-beta/transport.go#L85.

Shouldn't a sentry.Flush() call fail if there were some dropped packets? Currently it does not. I know this is no common use case, since usually non-blocking calls would be used and Flush might not hit the buffer size.

Furthermore it would be great to configure the request worker buffer size https://github.com/getsentry/sentry-go/blob/v0.0.1-beta/transport.go#L16

Thanks for your work! We currently evaluate Sentry & this Go client.

**Comment by kamilogorek** [comment]
Logging fixed: https://github.com/getsentry/sentry-go/commit/e97ead2229dc3754c87ef9f6175d159e43488cf4
Buffer configuration added: https://github.com/getsentry/sentry-go/commit/6eeb2a3826f67452c960533c8a66fc0e971e35bc

As for a `Flush` question, we decided in all the SDKs, that allowing it to timeout if there are too many events queued is just fine and shouldn't cause any troubles.

Cheers!

**Comment by christian-ehmig** [comment]
Thanks for your quick response, configurable buffer size and the info about `Flush`. Just noting that queuing up e.g. 500 events in a simple for loop and immediately flushing them afterwards will not yield a timeout. The flush will return early in case of a low buffer size and just drop packages. If it timeouts in such a case it would be ok (I know, not a common use-case ;))

Sth like this:
```go
for i := 0; i < 500; i++ {
	sentry.CaptureMessage("Message" + strconv.Itoa(i))
}	

if sentry.Flush(time.Second * 2) {
	// not triggered
} else {
	fmt.Println("timeout")
}
```

**Comment by kamilogorek** [comment]
If events get delivered in <2sec, then sure, it won't timeout :) However, we try to aim for the most common scenario, and leave enough room for configuration so that we can cover the rest of the cases in one way or another.

In this specific case, it's possible to do:

```go
type customTransport struct {
  interrupted chan bool
  flushing bool
}

func (t *customTransport) Configure(options ClientOptions) {}

func (t *customTransport) SendEvent(event *Event) {
  if t.flushing == true && reachedBufferLimit (
    t.interrupted <- true
  )

  // send, add to wait group etc. etc.
}

func (t *customTransport) Flush(timeout time.Duration) bool {
  t.flushing = true
  c := make(chan struct{})

  go func() {
    t.wg.Wait()
    t.flushing = false
    close(c)
  }()

  select {
  case <-c:
    return true
  case <-time.After(timeout):
  case <-t.interrupted:
    return false
  }
}
```

**Comment by christian-ehmig** [comment]
In our case they weren't, we received 30 packets in Sentry and 470 were dropped ;) Thanks, the customTransport will do.

**Comment by kamilogorek** [comment]
@christian-ehmig if you get so many events, you may also want to give `SampleRate` a try :)
