### ISSUE TITLE
Very little sentry.Recover documentation

### ISSUE THREAD

**Issue by doismellburning** [getsentry/sentry-go#61]
I just started integrating sentry-go and found the documentation on `sentry.Recover` slightly light

Specifically:

* I only found it because Google took me to https://docs.sentry.io/platforms/go/migration/ (which I hadn't read, because I was a new sentry-go user, not migrating from Raven) - it doesn't appear in the regular sentry-go docs
* Common usage scenarios/issues like https://github.com/getsentry/sentry-go/issues/30 aren't documented either (much like @DimitriosLisenko, I couldn't get the simple `defer sentry.Recover()` example provided to actually ever result in an error reaching Sentry)

I'd love to see the usage docs improved here, with some canonical examples and references please!

**Comment by msiemens** [comment]
Seconding this, there's no real documentation on how to log panics from Go to Sentry - which is a major type of error I want to see there 🙈

**Comment by kamilogorek** [comment]
Hey, thanks for the patience. I've scheduled some time for patches/features and releasing a new version of sentry-go this and next week. I'll make sure to fix all the remaining issues till the EOD next week. Cheers!

**Comment by kamilogorek** [comment]
PR pending https://github.com/getsentry/sentry-docs/pull/1348
@doismellburning @msiemens can you take a peek and tell me whether it's explained enough for new-comers? Thanks!

**Comment by msiemens** [comment]
Looks good to me 🙂

**Comment by doismellburning** [comment]
Much better, thank you!
