### ISSUE TITLE
Give more control by overriding http.Client or http.RoundTripper

### ISSUE THREAD

**Issue by yansal** [getsentry/sentry-go#62]
This issue is a feature request.

It's possible to override the http.Transport via the HTTPTransport field in ClientOptions.

Instead, it would be great to allow to override the http.Client, or http.RoundTripper (which is an abstract http.Transport). This feature would allow users of this package to add hooks at the http level.

**Comment by kamilogorek** [comment]
Hey, thanks for the patience. I've scheduled some time for patches/features and releasing a new version of sentry-go this and next week. I'll make sure to fix all the remaining issues till the EOD next week. Cheers!

**Comment by kamilogorek** [comment]
@yansal done. Will release new tag soon
