### ISSUE TITLE
Can't build `_examples/http` since v0.20.0

### ISSUE THREAD

**Issue by kei2100** [getsentry/sentry-go#620]
## Summary
Since `Scope.SetTransaction()` was removed in issue #605,  building the [_examples/http](https://github.com/getsentry/sentry-go/blob/v0.20.0/_examples/http/main.go#L109) now fails.

## Steps To Reproduce

```bash
$ git clone https://github.com/getsentry/sentry-go
$ cd sentry-go
$ git checkout refs/tags/v0.20.0
$ cd _examples/http/
$ go build
# github.com/getsentry/sentry-go/_examples/http
./main.go:109:15: hub.Scope().SetTransaction undefined (type *sentry.Scope has no field or method SetTransaction)
```

**Comment by cleptric** [comment]
Thanks for letting us know about this. Fixed in #621 🙂
