### ISSUE TITLE
Add ignoreTransactions and ignoreErrors

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-go#628]
### Background:
To further simplfiy ignoring certain events from being sent to sentry, it is also suggested to provide `ignoreTransactions` and `ignoreErrors`

More info here develop docs updated: https://develop.sentry.dev/sdk/features/#event-sampling

- [ ] ignoreErrors
- [ ] ignoreTransactions
- [ ] SDK docs

**Comment by onewland** [comment]
@cleptric I think I'm probably not the right assignee for this.

**Comment by cleptric** [comment]
@onewland Yep, this was meant for @greywolve 😬
