### ISSUE TITLE
Migrate to envelopes

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-go#629]
A transaction is already reported as an [envelope](https://github.com/getsentry/sentry-go/blob/c63acf9745fa0a018e3a4a53a7d677ceebdaacc7/transport.go#L97) - it would be good to do some refactoring & migrate the rest to [Envelopes](https://develop.sentry.dev/sdk/envelopes/) as well, same as in other SDKs.

**Comment by cleptric** [comment]
We'll tackle this in 1.0.
For now, we will do https://github.com/getsentry/team-webplatform-meta/issues/49 as a quick win.
