### ISSUE TITLE
Go Profiling

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-go#630]
Sentry has not committed to build profiling for Go yet.

That said, given @vaind's experience with Go, and that [he built that for .NET](https://github.com/getsentry/sentry-dotnet/pull/2206), I proposed he investigates what a potential Go Profiling support could look like.

This doesn't mean commitment from Sentry to build, it's just an early experimentation, to share the idea with the SDK maintainers.

Turns out that within a couple days from a customer asking, and proposing he investigates what would take, he already shared his experiment with us via a Draft PR: https://github.com/getsentry/sentry-go/pull/626

**Comment by bruno-garcia** [comment]
Relates to Java profiling: https://github.com/getsentry/sentry-java/issues/2635

**Comment by tonyo** [comment]
Go profiling has been released as part of [v0.22.0](https://github.com/getsentry/sentry-go/releases/tag/v0.22.0), so we can close this one.
Thanks @vaind @bruno-garcia 👍

**Comment by tonyo** [comment]
Started a discussion for feedback and ideas here: https://github.com/getsentry/sentry-go/discussions/657
