### ISSUE TITLE
Get EOF Error while setup sentry for a new project

### ISSUE THREAD

**Issue by NaLLiFFuNT** [getsentry/sentry-go#650]
## Steps To Reproduce

```go
package main

import (
	"log"
	"time"

	"github.com/getsentry/sentry-go"
)

func main() {
	err := sentry.Init(sentry.ClientOptions{
		Dsn: "https://link-to-sentry",
		// Set TracesSampleRate to 1.0 to capture 100%
		// of transactions for performance monitoring.
		// We recommend adjusting this value in production,
		TracesSampleRate: 1.0,
		Debug:            true,
	})
	if err != nil {
		log.Fatalf("sentry.Init: %s", err)
	}
	// Flush buffered events before the program terminates.
	defer sentry.Flush(2 * time.Second)

	sentry.CaptureMessage("It works!")
}
```

## Expected Behavior
See error on sentry

## Debug log
[Sentry] 2023/06/08 17:48:10 Integration installed: ContextifyFrames
[Sentry] 2023/06/08 17:48:10 Integration installed: Environment
[Sentry] 2023/06/08 17:48:10 Integration installed: Modules
[Sentry] 2023/06/08 17:48:10 Integration installed: IgnoreErrors
[Sentry] 2023/06/08 17:48:10 Sending info event [97ad9696d0c04dbabf7e5272dd8cd1b5] to **** project:**
[Sentry] 2023/06/08 17:48:11 There was an issue with sending an event: Post "https://******/envelope/": EOF

## Environment

I run my project inside docker container on MacBook laptop with M1. Idk if it's important.

### SDK
 - `sentry-go` version: v0.21.0
 - Go version: 1.20.4
 - Using Go Modules? yes

go.mod
```
github.com/getsentry/sentry-go v0.21.0
```

go.sum
```
github.com/getsentry/sentry-go v0.21.0 h1:c9l5F1nPF30JIppulk4veau90PK6Smu3abgVtVQWon4=
github.com/getsentry/sentry-go v0.21.0/go.mod h1:lc76E2QywIyW8WuBnwl8Lc4bkmQH4+w1gwTf25trprY=
```

### Sentry
 - Using hosted Sentry in sentry.io? yes
 - Using your own Sentry installation? Version: Sentry 23.2.0 8cfa6b9

## Additional context
New project, try to set up sentry. I've just copied code sample from [Installation Instructions] and got EOF error without explanation what's wrong.

**Comment by cleptric** [comment]
I'm not able to reproduce your issue.

```
[Sentry] 2023/06/12 07:42:56 Integration installed: ContextifyFrames
[Sentry] 2023/06/12 07:42:56 Integration installed: Environment
[Sentry] 2023/06/12 07:42:56 Integration installed: Modules
[Sentry] 2023/06/12 07:42:56 Integration installed: IgnoreErrors
[Sentry] 2023/06/12 07:42:56 Sending info event [436bd5e72ebe4146a15772a08bab71e7] to o447951.ingest.sentry.io project: 5774600
[Sentry] 2023/06/12 07:42:56 Buffer flushed successfully.
```

There may be some issues with your docker setup, as in it cannot reach sentry.io or similar.

**Comment by NaLLiFFuNT** [comment]
It's appeared that was an issue with network. The next day everything worked out. I think issue should be closed.
