### ISSUE TITLE
Cron implementation

### ISSUE THREAD

**Issue by aldy505** [getsentry/sentry-go#659]
Implement this feature: https://docs.sentry.io/product/crons/

(@cleptric) I would imagine something similar to what we did in PHP https://github.com/getsentry/sentry-php/pull/1467 & https://github.com/getsentry/sentry-php/pull/1511

Node implementation: https://github.com/getsentry/sentry-javascript/pull/8039

It turns out there's a parent issue: https://github.com/getsentry/sentry/issues/48560

UPDATE: Wrong parent issue 🤦

**Comment by tonyo** [comment]
Thanks for opening the issue @aldy505 

Curious to hear about use cases for Go specifically. What kind of periodic jobs do you want to monitor? Do you use any frameworks for periodic tasks?

**Comment by aldy505** [comment]
@tonyo Sure!

> What kind of periodic jobs do you want to monitor? 

Basically a database clean-up job, there are a few tasks that I also need to create with Go in mind. I also have 1 job written in plain C to clean up self-hosted Github Actions runner's VM including downloaded Docker images and so on forth. It executes some commands and have some logics that's hard to understand if it was written in pure Bash.

> Do you use any frameworks for periodic tasks?

Nope. Just `time.Sleep` and infinite for loop. But maybe others are using some libraries like [robfig/cron](github.com/robfig/cron), similar to what I did here: https://github.com/getsentry/vroom/pull/284
