### ISSUE TITLE
Adding http status code to transactions and errors

### ISSUE THREAD

**Issue by XDoubleU** [getsentry/sentry-go#664]
I would like to add the http status code of a response to Sentry transactions and errors. However, I can't find any documentation on how to do this and haven't been able to figure this out on my own neither.

I'm using the following project for this: https://github.com/XDoubleU/check-in-go-api-proto

Thanks in advance

**Comment by tonyo** [comment]
If you want to add the status code as a (searchable/queryable) event tag to your error event, then this might help: https://docs.sentry.io/platforms/go/enriching-events/tags/
For spans/transactions you can use `span.SetTag`.
