### ISSUE TITLE
Any planned support for displaying local variables?

### ISSUE THREAD

**Issue by elliotw23** [getsentry/sentry-go#68]
According to the docs only the Python and PHP sdks will include local variables in frames of stack traces. 
Any planned support for including this in the Go sdk? If not, can you explain the reasons?

**Comment by kamilogorek** [comment]
As far as I know, there's technically no way to achieve this in Go. Please correct me if I'm wrong.

**Comment by elliotw23** [comment]
Yea, I haven't seen the functionality anywhere else but just wanted to verify it was due to technical reasons.

**Comment by kamilogorek** [comment]
Unfortunately not that I'm aware of, sorry
