### ISSUE TITLE
add a per event sample rate.

### ISSUE THREAD

**Issue by james-lawrence** [getsentry/sentry-go#686]
## Summary
the global sample rate is wonderful for a default setting but misses the mark for actual usage. Its a fact of life that events are more critical than others and you'll want to sample those are higher frequencies.

## Motivation
getting actionable alerts faster without blowing up overall usage.

## Additional Context
this is actually applicable to most global options (like attaching a stack trace)

**Comment by cleptric** [comment]
There are quite a few mechanisms in place you can use to downsample specific errors.
Have a look at https://docs.sentry.io/platforms/go/configuration/filtering/.

**Comment by james-lawrence** [comment]
that's a lot of work to offload to end users using a globally scoped functionality for something that should be straight forward to mark in a apm and will lead to spooky action at a distance behaviors in the code base.

**Comment by james-lawrence** [comment]
@cleptric as I mentioned SampleRate/TracesSampleRate are global; not all errors/traces are equal. having the ability to set the sample rate per event/trace would resolve the issue here. the 'solutions' you mentioned are all much larger maintenance burdens for end users of sentry. we're likely talking < 10 lines of code to handle this gracefully (assuming reasonable internals in the client sdks) which is to add the sample rate to the events themselves and default the value from the global hub.
