### ISSUE TITLE
gin integration does not ignore broken pipe errors

### ISSUE THREAD

**Issue by macklin-10x** [getsentry/sentry-go#69]
Gin's default recovery handler is clever about ignoring broken pipe errors, to avoid logging/alerting when no response will be sent because the connection has already closed.  The current gin/sentry integration doesn't handle this case and we get false positive sentry alerts due to broken pipes.  Integrating this check should be just a few lines of code; see https://github.com/gin-gonic/gin/blob/master/recovery.go#L45

**Comment by kamilogorek** [comment]
Hey, thanks for the patience. I've scheduled some time for patches/features and releasing a new version of sentry-go this and next week. I'll make sure to fix all the remaining issues till the EOD next week. Cheers!

**Comment by macklin-10x** [comment]
Fabulous, thank you for the improvement!
