### ISSUE TITLE
All errors show up as *errors.withStack

### ISSUE THREAD

**Issue by federicobond** [getsentry/sentry-go#70]
I am using `github.com/pkg/errors` and all errors show up in Sentry with the title `*errors.WithStack`. Is there any way of customizing this message so that it's more informative? The full error message is shown below but it's hard to differentiate issues when they all have the same title. 

Using Sentry 9.1.2 on the server side.

**Comment by mfridman** [comment]
Don't think this question belongs here per se.

But, when composing a Sentry event you can assert the `error` and get an underlying error (if available) through `.Cause(err)`

e.g.,

```
ev := sentry.NewEvent()

// ..

if _, ok := err.(interface{ Cause() error }); ok {
	e := errors.Cause(err)

	ev.Exception[0].Type = e.Error()
	ev.Exception[0].Value = reflect.TypeOf(e).String()
}
```

In sentry this will show up like so, here is an example where we retrieve an underlying `*pq.Error` which was wrapped many layers down.

<img width="719" alt="Screen Shot 2019-10-21 at 9 45 44 PM" src="https://user-images.githubusercontent.com/6278244/67254729-9e2dbc00-f44c-11e9-8a34-041afd02ef83.png">

Hope this helps.

**Comment by kamilogorek** [comment]
Hey, thanks for the patience. I've scheduled some time for patches/features and releasing a new version of sentry-go this and next week. I'll make sure to fix all the remaining issues till the EOD next week. Cheers!
