### ISSUE TITLE
*sentry.Scope has no field or method Transaction

### ISSUE THREAD

**Issue by GGuinea** [getsentry/sentry-go#706]
## Summary
I have a problem while trying to setup sentry according to this docs. https://docs.sentry.io/platforms/go/guides/gin/performance/?original_referrer=https%3A%2F%2Fwww.google.com%2F

## Steps To Reproduce
```go
func initSentry(cfg *config.Config) error {
	if err := sentry.Init(sentry.ClientOptions{
		Dsn:           cfg.Sentry.DSN,
		EnableTracing: cfg.Sentry.EnableTracing,
		Environment:   cfg.App.Environment,
		TracesSampler: sentry.TracesSampler(func(ctx sentry.SamplingContext) float64 {
			hub := sentry.GetHubFromContext(ctx.Span.Context())
			name := hub.Scope().Transaction()
			return 0.2
		}),
		AttachStacktrace: true,
	}); err != nil {
		fmt.Printf("Sentry initialization failed:%v\n", err)
		return err
	}
	return nil
}
```

## Expected Behavior
I wan to filter out some request. 

## Screenshots
<img width="1115" alt="image" src="https://github.com/getsentry/sentry-go/assets/44040042/239393c7-acad-4974-96ae-8455460c9447">

### SDK
 - `sentry-go` version: 0.23
 - Go version: 1.20
 - Using Go Modules? [yes/no] yes

### Sentry
 - Using hosted Sentry in sentry.io? [yes/no] yes

**Comment by cleptric** [comment]
You can do the following.

```go
TracesSampler: func(ctx sentry.SamplingContext) float64 {
	if ctx.Span.Name == "GET /health" {
		return 0
	}
	return 1
},
```

I'll get the docs updated.
