### ISSUE TITLE
Upgrading from 0.19.0 to 0.24.1

### ISSUE THREAD

**Issue by jon-whit** [getsentry/sentry-go#719]
I'm trying to upgrade from 0.19.0 to 0.24.1 but I have some code that was dealing with setting the scope transaction that is no longer part of the API.

```go
c.hub.ConfigureScope(func(scope *sentry.Scope) {
    scope.SetExtras(meta)
    scope.SetTransaction(operation) // this bit
    scope.SetUser(sentry.User{ID: user})
})
```

What is the recommended upgrade path to set the `transaction` field? I use it to identify the RPC method that was invoked.

**Comment by cleptric** [comment]
This depends on whether you're using our performance product or not.

If you do, setting the transaction name now works as outlined here: https://github.com/getsentry/sentry-go/releases/tag/v0.20.0.
If not, you can set the operation as a tag `scope.setTag`, which makes it searchable but with certain length limits, or you can use a context, which is similar to extras but useful for more structured data, `scope.setContext`.
