### ISSUE TITLE
Cannot rename project

### ISSUE THREAD

**Issue by agaudreault-jive** [getsentry/sentry-go#73]
It is impossible to use the Update project method to rename a project. Sending an object requires us to use the current slug. we can update the `Name` property but this one maps to the Legacy Name.

The current implementation use the slug from the object. Instead, the slug should be a separate parameter `UpdateProject(o Organization, projectSlug string, p Project)`
```golang
// UpdateProject takes a organization and project then updates it on the server side
func (c *Client) UpdateProject(o Organization, p Project) error {
	return c.do("PUT", fmt.Sprintf("projects/%s/%s", *o.Slug, *p.Slug), &p, &p)
}
```

**Comment by kamilogorek** [comment]
Hey, thanks for the patience. I've scheduled some time for patches/features and releasing a new version of sentry-go this and next week. I'll make sure to fix all the remaining issues till the EOD next week. Cheers!
