### ISSUE TITLE
Got error when it list metric alerts

### ISSUE THREAD

**Issue by keyolk** [getsentry/sentry-go#734]
## Summary

Got error below when I listing metric alerts with this SDK v2.4
```
Error: json: cannot unmarshal number into Go struct field MetricAlertTriggerAction.triggers.actions.targetIdentifier of type string
```

When I dumped its response, there was a item which has numeric value of targetIdentifier see https://github.com/turbot/steampipe-plugin-sentry/issues/5#issuecomment-1765819504

## Steps To Reproduce

I tested this with https://github.com/turbot/steampipe-plugin-sentry/blob/main/sentry/table_sentry_metric_alert.go#L153C44-L153C44

## Expected Behavior

No error

### SDK
 - `sentry-go` version: v2.4.0
 - Go version: 1.20.4
 - Using Go Modules? yes

### Sentry
 - Using hosted Sentry in sentry.io? no
 - Using your own Sentry installation? Version: no
 - Anything particular to your environment that could be related to this issue?

## Additional context

organizationId: 31416

**Comment by greywolve** [comment]
Hi @keyolk,

Are you sure you have the correct project? Seems like you're depending on https://github.com/jianyuan/go-sentry which is a different project to this. AFAIK we don't have any way to list metrics etc. This SDK is purely for instrumentation. :)
