### ISSUE TITLE
Add WithDescription SpanOption

### ISSUE THREAD

**Issue by moneymikeMD** [getsentry/sentry-go#739]
## Summary

Pretty simple. For Spans, the current process of creating them is:
```
span := sentry.StartSpan(ctx, "function")
span.Description = "doWork"
defer span.Finish()
```
This requires multiple lines each time. If there was a `WithDescription` SpanOption, this then becomes:
```
defer sentry.StartSpan(ctx, "function", WithDescription("doWork").Finish()
```

making calls to sentry a less distracting one-liner at the top of a function. 

## Motivation

The current way to create spans can be made more concise. The more involved change is allowing description to be added in another `StartSpan` function signature, i.e. `StartSpan(ctx, "function", "doWork")`, but that would require more testing to get out. The least intrusive way to accomplish the same thing is adding a SpanOption instead. This doesn't existing uses and is the way we accomplish this now. Would love for this to come from the standard library instead of our `helpers` package.

**Comment by greywolve** [comment]
Seems reasonable @moneymikeMD . :)
