### ISSUE TITLE
Including additional info in the environment integration

### ISSUE THREAD

**Issue by sigsevneo** [getsentry/sentry-go#74]
Currently the environment integration ships two datapoints about the runtime:
1. Name
2. Version

Can we add two more datapoints provided by default by the lib?
3. Number of goroutines
4. GOMAXPROCS

Has there been a decision to consciously exclude these datapoints from the runtime information provided?

**Comment by kamilogorek** [comment]
Added in https://github.com/getsentry/sentry-go/pull/76
