### ISSUE TITLE
Support uploading Go source code with a release

### ISSUE THREAD

**Issue by eric** [getsentry/sentry-go#740]
## Summary

I would like to see support for uploading Go source code with a release. 

## Motivation

We are not able to package the source code with our binary but still would like to have the improved experience of seeing the source code in Sentry.

## Additional Context

We ship the binary to customers and do not want to provide them with the source code.

**Comment by cleptric** [comment]
We discussed this internally and would consider adding this in the future. I can't give you any timeline, though.

**Comment by eric** [comment]
Not having this greatly reduces the usefulness of Sentry for Go for us. It involves manually looking at the files in an editor, because there is no linking to github, no context, and the stack frames as they are listed make it difficult to capture both the file name and the line number at the same time.

**Comment by cleptric** [comment]
You would need to create a source bundle and upload it at compile time. And then you would also need to upload debug files, which is odd in Go, that include a debug ID so we can map your code to the event in Sentry. None of this is currently supported in Go, so it takes different teams to get this going. Hence it's unlikely that we will get to this in a short timeframe. 

Can you expand on the stack trace layout? What exactly bothers you with the visuals?

**Comment by eric** [comment]
<img width="459" alt="screenshot-2023-10-30-11 29 00@2x" src="https://github.com/getsentry/sentry-go/assets/470/e574324e-ab9f-420a-8e55-e994a8169f14">

Not having the format of `<file>:<line>` means that I can't paste it into a VSCode Quick Open dialog or anything like that.

Honestly I've said this all over the place, but it would just be really nice if I could map some file/package locations to GitHub URLs to at least link to the code. It's terribly frustrating to have literally nothing that can easily get me to the code to look at what's going wrong.

> None of this is currently supported in Go, so it takes different teams to get this going. Hence it's unlikely that we will get to this in a short timeframe.

I understand that it doesn't sound like you have many customers that you know of that are shipping Go binaries to places that can't have access to the source code, but not having this functionality severely limits the usefulness of the product to those of us who do. Is this on the radar of the wider PM org to prioritize this?

**Comment by cleptric** [comment]
I filled part of this as https://github.com/getsentry/sentry/issues/59030 and pinged the PM involved. I totally agree btw, this is crazy bad!

> Is this on the radar of the wider PM org to prioritize this?

Yep, it is. But as you also mentioned, we don't have many customers with this use case 🙁 
But I do have a project where it bothers me to include my source code in the docker container to get source context working, so rest assured, this is not just a you issue!

**Comment by eric** [comment]
It sure would be great if someone could handle this before the bot closes it.

**Comment by cleptric** [comment]
We did ship an update to our stack trace view, which now lets you map your stack trace to GitHub without the need for having source context availiable.

<img width="1195" alt="image" src="https://github.com/getsentry/sentry-go/assets/6617432/bf5f5c6e-cdc7-4fd0-8ada-06a4ca0e84eb">

**Comment by cleptric** [comment]
Tracking this as https://github.com/getsentry/sentry-go/issues/177.
