### ISSUE TITLE
Stack trace has confusing top frame when using sentry.CurrentHub().Recover(err)

### ISSUE THREAD

**Issue by eric** [getsentry/sentry-go#741]
## Summary

When using `sentry.CurrentHub().Recover(err)` to report an exception the stack trace contains that stack frame at the top.

## Steps To Reproduce

Create recover block:

```go
		defer func() {
			if err := recover(); err != nil {
				log.Printf("[ERR] Error: %v", err)
				sentry.CurrentHub().Recover(err)
			}
		}()
```

Have panic after that in a nested function.

## Expected Behavior

I expect the top stack frame to be the frame that caused the panic. Instead, it is the stack frame that has the recover. This makes some logical sense, because it is the thing that is calling `sentry.CurrentHub().Recover(err)` but it is unintuitive.

### SDK
 - `sentry-go` version: 0.25.0
 - Go version: go1.20.10
 - Using Go Modules? yes

### Sentry
 - Using hosted Sentry in sentry.io? yes

**Comment by cleptric** [comment]
I wasn't able to reproduce this.

![grafik](https://github.com/getsentry/sentry-go/assets/6617432/94f42f48-a353-46ef-bc94-fd713a558927)

**Comment by eric** [comment]
Here is an example exception: https://fancy-bits-llc.sentry.io/issues/3485598464/

What does the recover handler look like in your example?

**Comment by cleptric** [comment]
https://github.com/getsentry/sentry-go/blob/master/gin/sentrygin.go#L94

The issue you linked uses Go SDK 0.13.0 btw.

**Comment by eric** [comment]
Ah, you are correct. Here is one from the 0.25.0 SDK: https://fancy-bits-llc.sentry.io/issues/4575378790/

**Comment by cleptric** [comment]
So to confirm, the panic stems from `reflect/value.go in Value.Field at line 1272` in your linked issue?

**Comment by eric** [comment]
Yes. Line 341 of processor.go is:

```
				sentry.CurrentHub().Recover(err)
```

from the above example recover block.

**Comment by eric** [comment]
Your repro doesn't properly reproduce the issue because you are relying on the `recover()` that is within the `sentry-go` package:

https://github.com/getsentry/sentry-go/blob/8f8897dc8b964b6116f737c6e78ecd55af0f90dd/stacktrace.go#L323-L327

If you try to reproduce this in a separate repo that contains its own `recover()` call like the one in my original post, I expect you will be able to reproduce this easily.

**Comment by eric** [comment]
I believe it's common in implementations to provide an argument for the number of stack frames to suppress instead of just blanket ignoring all frames from a given package. As the comment in `shouldSkipFrame()` said, the current implementation could hide other stack frames from inside sentry-go that caused a problem.

**Comment by eric** [comment]
Related: #649

**Comment by eric** [comment]
Related: #458

**Comment by eric** [comment]
Any progress?

**Comment by cleptric** [comment]
We merged a PR two years ago that closed this issue.

**Comment by eric** [comment]
And then it was reverted? #882

**Comment by giortzisg** [comment]
We might be able to filter through the stacktrace for `runtime.panic` to throw away the not so useful frames, reopening for now and will have a look.

**Comment by giortzisg** [comment]
This might be trickier to implement. We can capture all frames after `runtime.gopanic` and in the recover case we would successfully skip the  SDK frames, but this affects all captureException calls. A hacky solution might be to just add a completely new code path only for `sentry.Recover` but this seems like a half baked solution.

**Comment by eric** [comment]
It seems like the only person who knows how many frames should be thrown away is the caller, and they would need to provide the number of frames to skip. Isn't this how this sort of thing is handled on most platforms?

**Comment by giortzisg** [comment]
> It seems like the only person who knows how many frames should be thrown away is the caller, and they would need to provide the number of frames to skip

I agree in general, but this partly mixes this issue with #458. Caller-provided frame skipping makes sense for skipping user owned wrappers, but it doesn't work for recover. Recover can receive either an active panic or an ordinary handled error, and some errors already carry their own stacktrace, thus making it impossible to know how to skip a fixed number of frames. 

The only somewhat comparable platform here is Rust, where panics are treated separately to ordinary errors, so I suppose the aforementioned `runtime.gopanic` solution is probably good enough.
