### ISSUE TITLE
Bump gin-gonic/gin from v1.8.1 to v1.9.1 due to vulnerabilities

### ISSUE THREAD

**Issue by metinogurlu** [getsentry/sentry-go#742]
## Summary
`gin-gonic/gin` `v1.8.1` [has security vulnerabilities](https://www.cvedetails.com/vulnerability-list/vendor_id-24141/product_id-91039/version_id-1015118/). Could we bump the version to v1.9.1

**Comment by cleptric** [comment]
We won't bump the base line in this case, please have a look at https://github.com/getsentry/sentry-go/security/policy#dependency-update-policy and let me know if you have any more questions.
