### ISSUE TITLE
When using gin to report an error to sentry, sentry never receives it.

### ISSUE THREAD

**Issue by jroam** [getsentry/sentry-go#753]
## Steps To Reproduce

 eg. 
https://go.dev/play/p/GB3vtOfnOo4
 

### SDK
 - `sentry-go` version: 0.25.0 
 - Go version:  1.20.3
 - Using Go Modules? yes

### Sentry
 - Using hosted Sentry in sentry.io? no
 - Using your own Sentry installation? Version:  9.1.2
 - Anything particular to your environment that could be related to this issue? No

**Comment by cleptric** [comment]
See https://github.com/getsentry/sentry-go/releases/tag/v0.21.0

You need to either upgrade your self-hosted instance or downgrade to version 0.20.0.
