### ISSUE TITLE
Support for User Feedback feature

### ISSUE THREAD

**Issue by aldy505** [getsentry/sentry-go#756]
## Summary

Since User Feedback is out in beta and other backend-related SDKs are supporting them, also considering the envelope payload is simple, why don't we have it here?

The implementation should be similar to how JS and Java/Kotlin SDKs are doing it:

* https://docs.sentry.io/platforms/javascript/user-feedback/#user-feedback-api
```js
import * as Sentry from "@sentry/browser";

const eventId = Sentry.captureMessage("User Feedback");
// OR: const eventId = Sentry.lastEventId();

const userFeedback = {
  event_id: eventId,
  name: "John Doe",
  email: "john@doe.com",
  comments: "I really like your App, thanks!",
};
Sentry.captureUserFeedback(userFeedback);
```

* https://docs.sentry.io/platforms/kotlin-multiplatform/user-feedback/
```kotlin
import io.sentry.kotlin.multiplatform.Sentry
import io.sentry.kotlin.multiplatform.protocol.UserFeedback

val sentryId = Sentry.captureMessage("My message")

val userFeedback = UserFeedback(sentryId).apply {
  comments = "It broke."
  email = "john.doe@example.com"
  name = "John Doe"
}
Sentry.captureUserFeedback(userFeedback)
```

## Motivation

The Go SDK hasn't implement this. Let's implement this.

## Additional Context

I didn't find any issue that track the implementation of this feature from the [getsentry/team-sdks](https://github.com/getsentry/team-sdks/issues)

**Comment by cleptric** [comment]
The API you're showing is the old user feedback, not the new one. I'm not aware of any plans to add this to any BE SDKs.

**Comment by aldy505** [comment]
> The API you're showing is the old user feedback, not the new one. I'm not aware of any plans to add this to any BE SDKs.

I see. I found those from [this link](https://docs.sentry.io/product/user-feedback/setup/) as "Supported SDKs for Crash-Report API".

**Comment by aldy505** [comment]
As I think of this further, this is not feasible for Go.
