### ISSUE TITLE
OTel SDK casts all span `data` values to string

### ISSUE THREAD

**Issue by gggritso** [getsentry/sentry-go#758]
## Summary

Something in the interaction between Go and OTel is casting all span `data` values to strings, even well-known measurement fields like `http.response_content_length`

## Steps To Reproduce

I found this data in the wild, so I don't have actual repro steps, sorry! I can provide more details if you contact me on Slack

## Expected Behavior
`data.http.response_content_length` is an integer

## Screenshots
<img width="607" alt="Screenshot 2024-01-08 at 4 35 49 PM" src="https://github.com/getsentry/sentry-go/assets/989898/2cd8f683-8e3d-4316-9c4c-202433a477cd">

### SDK
 - `sentry-go` version: `0.25.0`
 - `opentelemetry` version: `1.18.0`

### Sentry
 - Using hosted Sentry in sentry.io? yes

**Comment by AbhiPrasad** [comment]
We are using https://pkg.go.dev/go.opentelemetry.io/otel@v1.21.0/attribute#Value.Emit - this forces everything to be strings https://github.com/getsentry/sentry-go/blob/fff66d18d3019c0c75c88edb26f8d79d52d8a126/otel/span_processor.go#L129.

We should remove the casting.

See https://opentelemetry.io/docs/concepts/signals/traces/#attributes

> Values must be a non-null string, boolean, floating point value, integer, or an array of these values

**Comment by AbhiPrasad** [comment]
cc @cleptric
