### ISSUE TITLE
thread_id is typed as a string but Sentry actually sends ints

### ISSUE THREAD

**Issue by grandstaish** [getsentry/sentry-go#767]
https://github.com/getsentry/sentry-go/blob/master/interfaces.go#L244

^This field, `thread_id`, is typed as a `string` but Sentry actually sends `int`s.  This is blocking us from deserialising any event from Sentry. 

This is the only issue with the modelling I've found. 

Background: 
We have the Android Sentry SDK set up in our app. We've got a Go webhook consuming alert events. These events cannot be deserialised currently because of this bug. Not sure if this problem is somehow specific to `event_alert`s coming from a JVM/Android project or not.

**Comment by grandstaish** [comment]
I can confirm that `thread_id` is a `Long` in JVM-land: https://github.com/getsentry/sentry-java/blob/72864a09a5ea170caa37bccf6b21aa3a1f7efafb/sentry/src/main/java/io/sentry/protocol/SentryException.java#L47

**Comment by cleptric** [comment]
It looks like Relay expects an integer as well, https://github.com/getsentry/relay/blob/master/relay-event-schema/src/protocol/exception.rs#L89. I think we can make this change.

**Comment by grandstaish** [comment]
Glad to hear it @cleptric.  For us this is a blocker to using Sentry. When do you see this being fixed? It's a tough one to workaround.

**Comment by cleptric** [comment]
We can get a fix out later this week.
