### ISSUE TITLE
stacktraces are including source code

### ISSUE THREAD

**Issue by pkieltyka** [getsentry/sentry-go#77]
hello, I'm just wondering how the stacktrace reporting works with the sentry-go client?

it appears my source code is being recorded in sentry's servers, which is quite concerning as our company source is private. I'd like it to only record+report the raw stacktrace as the standard go stacktrace prints in a binary.

please let me know as we can't use sentry-go until this is clarified. thanks

**Comment by pkieltyka** [comment]
yikes, https://github.com/getsentry/sentry-go/blob/master/sourcereader.go

this is a massive nono, you should have a massive warning about this project for anyone using it in commercial use. That is a massive invasion of privacy and rights.

I know the intent is to give developers a nice experience for the sentry dashboard to easily view the source of their errors, but, this cannot be the default behaviour, you could probably get sued and taken down as a company if you ever leaked someone's source code because of a security breach.

I suggest to remove sourcereader.go asap and to never make this a default and make it double opt-in. Not for my project, and no for my dependencies.

**Comment by pkieltyka** [comment]
next steps: please inform me how to ensure 100% my source code has been removed by your virus library.

**Comment by pkieltyka** [comment]
I'm switching our company to rollbar.com 

good day.

**Comment by ianha** [comment]
@kamilogorek Can you please provide an update ASAP confirming the removal of our source on your servers. This is outrageous.

**Comment by pkieltyka** [comment]
btw for others, I've been trying https://honeybadger.io service for error reporting and its quite a wonderful project and their Go library is lean and doesn't have any viruses. Their service has also a number of other cool features like uptime + pinging for monitoring service health with a push model.

**Comment by mitsuhiko** [comment]
Sentry does not store your source on the servers. For exceptions the context line information is stored within an event. If you delete a project all events within it will be deleted.

**Comment by kamilogorek** [comment]
This is literally one of the features that are listed on the main https://sentry.io page and in our features list - https://sentry.io/features/stacktrace/

If you want to disable it, it's explained in the documentation how to do this - https://docs.sentry.io/platforms/go/config/#removing-default-integrations

**Comment by pkieltyka** [comment]
its including a few lines of source per frame in a stack trace. the code itself makes me nervous for potentially what else it's doing.

for interrupted languages this might feel okay, but its not okay for a language like Go. As well, this should not be the default behaviour for developers who would want this, because in many cases, they won't understand its implications. Again, just FYI, its enough for me to stop using Sentry for any of our server infrastructure and switch to a different provider.

**Comment by mitsuhiko** [comment]
I'm not sure why Go would be any different here. It can only access context line information if the source is stored on the same machine next to your executable. As mentioned there is a way to turn this off. Since it only transmits contextual information the total risk here is pretty limited and it only gets sent via an encrypted connection to your own or our trusted sentry installation on sentry.io.

The only way you can see source code snippets ever show up in Sentry is if you distribute the source with your application (for instance in the docker container etc.).

**Comment by pkieltyka** [comment]
@mitsuhiko I'm saying this should not be included as a default option for any server program. It should be a specific opt-in to say `UploadSnippetsOfMySourceCodeForStackTraces: true`. 

Developers will make mistakes and they will cause these snippets to be triggered even if source isn't shipped in a container -- more reason why it's not a useful feature as common Go practice is to ship binaries in deployment environments. 

In any case, we've already made our decision, but hope this feedback has been useful.

**Comment by mitsuhiko** [comment]
I'm going to close this as resolved. It's already possible to disable this. The likelihood to accidentally do this is pretty minimal since most developers will fire a test event ahead of time which shows the source context anyways.

**Comment by c2h5oh** [comment]
@mitsuhiko I believe this on ON by default in Go Sentry client - it's a part of contextifyFrames integration which is enabled by default based on release notes for 0.1.3

https://github.com/getsentry/sentry-go/releases/tag/v0.1.3

**Comment by mitsuhiko** [comment]
Correct, the integration is enabled by default like it is for all our platforms.

**Comment by nanmu42** [comment]
For those like me who finds this feature suprising, adding following lines into `sentry.init` may help:

```go
err = sentry.Init(sentry.ClientOptions{
		// Sentry takes snippets of source code by default,
		// which is a little surprising.
		// Refs:
		// https://github.com/getsentry/sentry-go/issues/77
		// https://docs.sentry.io/platforms/go/configuration/options/#removing-default-integrations
		Integrations: func(integrations []sentry.Integration) []sentry.Integration {
			var filteredIntegrations []sentry.Integration
			for _, integration := range integrations {
				if integration.Name() == "ContextifyFrames" {
					continue
				}
				filteredIntegrations = append(filteredIntegrations, integration)
			}
			return filteredIntegrations
		},
	})
```
