### ISSUE TITLE
[go] Add support for Sentry Metrics

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-go#787]
### Description
Metrics! Sentry will support Metrics finally! First we need all of our SDKs to support Metrics, including the Go SDK

#### Requirements:

- [ ] API for sending Metrics
- [ ] Tag normalization (or sanitization)
- [ ] Metrics Summary
- [ ] Span Aggregator (trace correlation) 
- [ ] Code location

#### Document(s)
[Develop Specs](https://develop.sentry.dev/delightful-developer-metrics/)
[SDK Develop Specs](https://develop.sentry.dev/delightful-developer-metrics/sending-metrics-sdk/)
[Product Specs](https://develop.sentry.dev/sdk/metrics/)

**Comment by aldy505** [comment]
@cleptric any plan for working on this? Or can I work on this instead?

**Comment by cleptric** [comment]
We started working on Metrics this week.

**Comment by wlzhou** [comment]
>[cleptric](https://github.com/cleptric) closed this as [not planned](https://github.com/getsentry/sentry-go/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3A%22not+planned%22) [last month](https://github.com/getsentry/sentry-go/issues/787#event-13015301503)

Will this be supported eventually still, or should we expect this to never be added?

**Comment by cleptric** [comment]
Yes, but not in its current form. See https://sentry.zendesk.com/hc/en-us/articles/26369339769883-Upcoming-API-Changes-to-Metrics for more details.
