### ISSUE TITLE
IgnoreErrors not filtering certain events.

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry-go#817]
Trying to filter the following errors on the SDK side:

*mysql.MySQLError
Error 188 (HY000): FTS query exceeds result cache limit

For that, we are using the ignoreErrors configuration with value: `Error 188 (HY000): FTS query exceeds
result cache limit`, however it does not filter the events. Changing the filter to only `FTS query exceeds
result cache limit` serves as a workaround. 

```
opts := sentry.ClientOptions{
    Dsn: config.Sentry.Dsn,
    Debug: true,
    Integrations: func(i []sentry.Integration) []sentry.Integration {
            return i
    },
    IgnoreErrors: []string{
            "FTS query exceeds result cache limit",
    },
}
```

SDK version: 0.25.0.

**Comment by ribice** [comment]
Since the values in IgnoreErrors are converted to regex patterns, characters `(` and `)` need to be escaped for this to  work.

This is how you can add it:

```
IgnoreErrors: []string{`Error 188 \(HY000\): FTS query exceeds result cache limit`},
```

**Comment by cleptric** [comment]
Could we change `IgnoreErrors` to take both regex and strings into account? Same for `IgnoreTransactions`.

**Comment by cleptric** [comment]
Yep, e.g. in JS https://docs.sentry.io/platforms/javascript/configuration/options/#ignore-errors
