### ISSUE TITLE
option to disable sending sdk and packages list with every sentry event

### ISSUE THREAD

**Issue by asif2k** [getsentry/sentry-go#821]
there should a be a flag that disable sending sdk and packages list with every sentry event , that is annoying and add lot of data to the packet.

this option will use less network resource and also sentry event look much cleaner on sentry side

**Comment by cleptric** [comment]
You can use [`ClientOptions.Integrations`](https://github.com/getsentry/sentry-go/blob/master/client.go#L157-L159) to overwrite which integrations should be used.
