### ISSUE TITLE
Provide a customisable hint when capturing an event

### ISSUE THREAD

**Issue by crswty** [getsentry/sentry-go#823]
## Summary

Would it be possible have a way to provide a `Hint` along with an `Event` in `Hub`

## Motivation

I'm customising the errors I send to sentry by calling `sentry.Hub.CaptureEvent` with an event from `sentry.Client.EventFromException`. This works well apart from the fact that I lose the Hint that I would get if I called `CaptureException` making it harder to use other parts of the API like BeforeSend.

Unfortunately there doesn't seem to be a way to add an EventHint manually with the Hub API, that can only be done at the client level but if I call the client directly myself it looks like I will be breaking handling of `lastEventID` in the hub.

Would it be reasonable to add a version of `CaptureEvent` that took both an event and a hint to allow callers to have this flexibility without breaking other parts of the API?

**Comment by cleptric** [comment]
What are you using `lastEventID` for? When using the default, async transport, `CaptureException` & Co. simply return the event id, so it's not a guarantee that the event was actually sent to Sentry, but rather, it was queued up in the transport.

**Comment by crswty** [comment]
I'm not actually using it but was worried that if it wasn't set I would be breaking some contract with the hub. Should I just get the client and the scope from the hub and call the client's CaptureEvent myself?

**Comment by cleptric** [comment]
Yeah, nothing wrong about this approach.

**Comment by crswty** [comment]
Then I'll go with that for now, thanks!
