### ISSUE TITLE
Cannot "go get github.com/getsentry/sentry-go/fiber"

### ISSUE THREAD

**Issue by assembly-winston** [getsentry/sentry-go#829]
## Summary
Running the install command causes the following issue:

```
go: module github.com/getsentry/sentry-go@upgrade found (v0.27.0), but does not contain package github.com/getsentry/sentry-go/sentryfiber
```

## Steps To Reproduce
Run the suggested install command: go get github.com/getsentry/sentry-go/fiber.

## Expected Behavior
For it to download and make available the Sentry Fiber package.

### SDK
 - `sentry-go` version: v0.27.0
 - Go version: 1.22.1
 - Using Go Modules? yes

### Sentry
 - Using hosted Sentry in sentry.io? yes

**Comment by cleptric** [comment]
We did not release the fiber integration, so the current behavior is to be expected.

**Comment by assembly-winston** [comment]
Is there an ETA for the release?

**Comment by cleptric** [comment]
Next week.
