### ISSUE TITLE
Backwards compatibility not maintained, profiling broke

### ISSUE THREAD

**Issue by thnk2wn** [getsentry/sentry-go#830]
## Summary
We noticed profiling stopped working some time ago for our Go apps. We were able to get it working again after upgrading the SDK but there were breaking changes despite being minor version updates.

## Steps To Reproduce
1. Used version `v0.13.0` for some time successfully with profiling
2. Several months passed, eventually noticed no profiling despite no changes on our end
3. Upgraded to `v0.27.0`
4. Immediately noticed breaking code changes, despite minor version bump. For example, `sentry.TransactionName()` was now `sentry.WithTransactionName()`
5. Set `Debug` to true on sentry options.
6. Noticed logging like `Dropping transaction: EnableTracing is set to false`
7. We never had to set any `EnableTracing` property before and we got tracing, breaking behavior change

## Expected Behavior
* SemVer, breaking changes only on major version bumps
* Sentry client libraries continue to work while the backend evolves
* If there is some client/server behavior mismatch over time, somewhere the issue is surfaced / communicated

### SDK
 - `sentry-go` version: v0.13.0 => v0.27.0
 - Go version: 1.22.1
 - Using Go Modules? yes

### Sentry
 - Using hosted Sentry in sentry.io? yes
 - Using your own Sentry installation? no 
 - Anything particular to your environment that could be related to this issue? No, outside of not updating Sentry for a while as this app hasn't changed in a long while

**Comment by cleptric** [comment]
The SDK is still pre `1.0`, so breaking changes might occur in any minor version, in accordance with [SemVer](https://semver.org/). We always point out any breaking changes in our change logs, too.

**Comment by thnk2wn** [comment]
@cleptric Thanks. It'd be great if this could be surfaced in Sentry somewhere as we generally wouldn't be checking release notes if we're not upgrading the SDK (we have seen similar on web/JS side). Code breaks on upgrades are less of a concern than things stop working when nothing has changed.

Additionally calling this out on the readme would be helpful.

**Comment by cleptric** [comment]
We didn't ship profiling support prior version `0.22.0` so I'm not sure what you are referring to.
See https://docs.sentry.io/platforms/go/profiling/

**Comment by thnk2wn** [comment]
@cleptric Sorry, incorrect terminology on my part - traces that show up under Performance - `sentry.StartSpan()` etc. I consider this a form of profiling albeit more custom / manual than automagic profiling.
