### ISSUE TITLE
Transaction names are set but show up as <unlabeled transaction>

### ISSUE THREAD

**Issue by thnk2wn** [getsentry/sentry-go#832]
## Summary
Transaction name is specified but always shows up in Sentry as `<unlabeled transaction>`

## Steps To Reproduce

```go
func Backfill(ctx *context.Context, options Options) error {
	*ctx = context.WithValue(*ctx, "backfill", true)
	transaction := sentry.StartTransaction(*ctx, "Backfill")
	transaction.SetTag("days", strconv.Itoa(options.Days))
	defer transaction.Finish()

	span := sentry.StartSpan(*ctx, "Some database query")
	// DB query
	span.Finish()
	
	// other code...

	span = sentry.StartSpan(*ctx, "Operation N")
	// operation code...
	span.Finish()
	// other code...
	
	return nil
}
```

Previously with older SDK we had something more like:

```go
	rootSpan := sentry.StartSpan(*ctx, "Backfill", sentry.WithTransactionName("Backfill"))
	defer rootSpan.Finish()
	
	span := sentry.StartSpan(rootSpan.Context(), "Some database query")
	// DB query
	span.Finish()
```

Neither option works. It's possible we're calling this wrong but it's also confusing without good examples and with similar ways to do different things over time leading to confusion.

The operation names show up as expected but the transaction name doesn't show up for the root transaction or any of the spans within the transaction.

Maybe the transaction context needs to be passed to the spans? [Docs](https://docs.sentry.io/platforms/go/performance/instrumentation/custom-instrumentation/) made it sounds like the same context can be passed around as normal and it'd keep track of everything.

## Expected Behavior
Transaction name in Sentry matches transaction name in Go code, in this case `Backfill`.

## Sentry.io Event
[Performance Events](https://jobot.sentry.io/performance/?environment=uat&project=4507250621022208&query=&referrer=performance-transaction-summary&statsPeriod=24h&unselectedSeries=p100%28%29&unselectedSeries=avg%28%29)

### SDK
 - `sentry-go` version: `v0.27.0`
 - Go version: `1.22`
 - Using Go Modules? `yes`

### Sentry
 - Using hosted Sentry in sentry.io? `yes`
 - Using your own Sentry installation? `no`
 - Anything particular to your environment that could be related to this issue? `no`

**Comment by aldy505** [comment]
> Maybe the transaction context needs to be passed to the spans?

Yeah usually this is the culprit. Your code should look like this though:
```go
// context.Context is an interface, no need to set it as a pointer. The default context implementation is a pointer already
func Backfill(ctx context.Context, options Options) error {
	// But most Go convention overrrides the ctx variable, so yeah..
	ctx = context.WithValue(*ctx, "backfill", true)
	// IMO StartTransaction should be deprecated already. It's useless now.
	transaction := sentry.StartSpan(*ctx, "Backfill (operation name)", sentry.WithTransactionName("Backfill"))
	transaction.SetTag("days", strconv.Itoa(options.Days))
	// Acquire the subsequent context from the StartSpan function
	ctx = transaction.Context()
	defer transaction.Finish()

	span := sentry.StartSpan(ctx, "Some database query")
	// DB query
	span.Finish()
	
	// other code...

	span = sentry.StartSpan(ctx, "Operation N")
	// operation code...
	span.Finish()
	// other code...
	
	return nil
}
```

Most of my code isn't like this though, I usually have each `StartSpan` and `defer span.Finish()` on top of every function that I feel like need tracing. So it'd be something like
```go
func main() error {
  span := sentry.StartSpan(context.Background(), "root", sentry.WithTransaction("root span"))
  defer span.Finish()

  err := functionA(span.Context(), "foo")
  if err != nil {
    return err
  }
  
  err = functionB(span.Context(), "bar")
  if err != nil {
    return err
  }
}

func functionA(ctx context.context p string) error {
  span := sentry.StartSpan(ctx, "functionA")
  defer span.Finish()
  // do things
}

func functionB(ctx context.Context, p string) error {
  span := sentry.StartSpan(ctx, "functionB")
  defer span.Finish()
  // do things
}
```

It's more verbose, sure, but for what I experienced, that's easier to maintain.

**Comment by thnk2wn** [comment]
@aldy505 Thanks. Believe the second block is closer to what I had started with originally then saw unlabeled transactions. It's interesting that `StartTransaction` is deprecated when the docs show examples of it i.e. https://docs.sentry.io/platforms/go/performance/instrumentation/custom-instrumentation/#add-more-spans-to-the-transaction. Although I do recall seeing something in SDK for JavaScript or another language about it being deprecated.

**Comment by aldy505** [comment]
No, I meant StartTransaction _should_ be deprecated. It's my opinion though 😂😂

**Comment by thnk2wn** [comment]
On the JS side https://github.com/getsentry/sentry-javascript/issues/10273#issuecomment-1905663678
