### ISSUE TITLE
Request body logging isn't working for server requests

### ISSUE THREAD

**Issue by flash286** [getsentry/sentry-go#84]
Hello everyone,
Trying to use request body logging in some cases, but it doesn't seem to be working

```go
request := sentry.Request{}
request = request.FromHTTPRequest(req)
```
request.Data is always empty :(

I guess a problem can be here

```go
if request.GetBody != nil {
		if bodyCopy, err := request.GetBody(); err == nil && bodyCopy != nil {
			body, err := ioutil.ReadAll(bodyCopy)
			if err == nil {
				r.Data = string(body)
			}
		}
	}
```

request.GetBody is always == nil and [Doc](https://golang.org/pkg/net/http/#Request) says 
> For server requests, it is unused.

request.Body looks like a right field.

**Comment by flash286** [comment]
up

**Comment by aschade92** [comment]
I'm having the same issue

**Comment by kamilogorek** [comment]
@flash286 @aschade92 I'll take a look at it in the morning

**Comment by flash286** [comment]
@kamilogorek let me know if it's a bug. I'm ready to make PR.

**Comment by rhcarvalho** [comment]
Hi @flash286! I can confirm this is a bug, thank you for reporting it 😄 

Please go ahead and send in a PR, I'll be happy to help you get that merged. Thanks!
