### ISSUE TITLE
Add constant for `SENTRY_DSN` environment variable

### ISSUE THREAD

**Issue by davidjb** [getsentry/sentry-go#845]
## Summary

To avoid having to re-define `SENTRY_DSN` in my application, it'd be easier to refer to this as a constant, such as `sentry.DSNEnv` if defined like:

```go
package sentry
...
const DSNEnv = "SENTRY_DSN"
```

This constant would also be referenced in the codebase where it is utilised (https://github.com/getsentry/sentry-go/blob/master/client.go#L285) so a client application can guarantee themselves to be using the same env variable.

Other env variables could be considered as constants and would be equally useful, but `SENTRY_DSN` is the one my projects primarily utilise.

## Motivation

Allows users to reference the env variable(s) centrally as a constant exposed by this package, reducing repetition and avoiding potential typos - essentially, the standard justifications of creating constants.

**Comment by cleptric** [comment]
Thanks for the suggestion, but I don't see this being necessary to be added to the SDK.
