### ISSUE TITLE
Handing runtime errors in a production application

### ISSUE THREAD

**Issue by louiscb** [getsentry/sentry-go#856]
Rather than an issue this is more understanding the best way to incorporate Sentry into a real world production Go application. I feel that the documents for this section could be improved.

From reading [this section](https://docs.sentry.io/platforms/go/usage/panics/) of the documents I see that If I have code that potentially could cause a `panic: runtime error`,  I should initially call `defer sentry.Recover()` to handle the potential panic. E.g

```
func() {
	defer sentry.Recover()

        numbers := []int{1, 2, 3}
        fmt.Println(numbers[3])
}()
```

This will cause a `panic: runtime error: index out of range [3] with length 3` error that Sentry will pick up.

However in a real world application with many lines of code I'm not sure what the best practice is. Do I have to identify every piece of code that potentially causes an unblended panic and prepend it with the sentry recover? Is there a way I can implement my project so I can pick up every panic in a general case?

**Comment by ribice** [comment]
In general, you need to handle panics whenever you spawn a new goroutine. For your usual http server, you have a middleware that handles panics per request, and then every subsequent function that spawns a new goroutine needs a panic handler.

I'm not sure if there is a way around that.

**Comment by eduardo-mior** [comment]
On my HTTP server I have a global Middleware to capture Panics, and then I need to manually capture panics for new goroutines created within Controllers and EndPoints
