### ISSUE TITLE
fiber dependency has vulnerability

### ISSUE THREAD

**Issue by shivamsouravjha** [getsentry/sentry-go#868]
## Summary

* Currently `github.com/gofiber/fiber/v2 v2.52.2` is being used in Sentry because of this a critical vulnerability is introduced.
* if [RHDA](https://marketplace.visualstudio.com/items?itemName=redhat.fabric8-analytics) is checked this would give a critical score of 10/10.
![Image](https://github.com/user-attachments/assets/f9cd90a9-bd0a-4307-a52d-5fd129b15e14)
* This led to the check around the fibre releases and in the latest release they themselves have mentioned solving [Vulnerability](https://github.com/gofiber/fiber/releases/tag/v2.52.5)

* Would be great if this could be solved with a minor version bump as this tool is used by many OSS projects.

**Comment by shivamsouravjha** [comment]
I've added a minor fix around this and have linked the PR here https://github.com/getsentry/sentry-go/pull/869

Best Regards.

**Comment by cleptric** [comment]
https://github.com/getsentry/sentry-go/pull/869#issuecomment-2269636064
