### ISSUE TITLE
remove iris dependency

### ISSUE THREAD

**Issue by edocevol** [getsentry/sentry-go#870]
Iris author make a breaking change

![Image](https://github.com/user-attachments/assets/2f8d2235-6f01-4d97-a5cd-4b42d2bd469d)

this change force developer upgrade golang version to 1.22.

Can we patch a version to remove iris dependency.

**Comment by edocevol** [comment]
We can move `gin`、`iris` integration to other repository.

**Comment by cleptric** [comment]
Can you please elaborate on the problem with us having a baseline of `github.com/kataras/iris/v12 v12.2.0`?

**Comment by edocevol** [comment]
Project with golang v1.21, use sentry sdk with version v0.11.0， after `go mod tidy`, will update mod file with.


![Image](https://github.com/user-attachments/assets/f11164ea-55d6-48b0-86c0-cd455fe62a66)

If our CI pipeline's version is lower than go1.21.0, it will throw an error due to the minimum version declared in go.mod. The reason for this situation is that Iris has deprecated the entire v12.0.0 ~ v12.1.8 versions, and the latest version requires a minimum Go version of go1.22. Moreover, after Go 1.21, the Go version declared in the mod file is already the minimum required version. Therefore, I think the unilateral modification by the Iris author has affected the use of existing projects.

**Comment by edocevol** [comment]
Perhaps we can have Gin use the `contrib repository` to manage various middleware. We can move the integration support for Sentry with Gin and Iris to a separate contrib repository, ensuring that the core SDK of Sentry remains clean and tidy.

https://github.com/gin-contrib/

**Comment by cleptric** [comment]
Please update the Sentry Go SDK to the latest version (0.28.1) and you won't run into this problems.
The baseline on this version is `github.com/kataras/iris/v12 v12.2.0` which is not retracted and the SDK works fine with Go 1.21.
