### ISSUE TITLE
Idea for more ergonomic SDK by allowing passthrough errors

### ISSUE THREAD

**Issue by assembly-winston** [getsentry/sentry-go#874]
Rather than doing the following which is unergonomic:

```
if err != nil {
  sentry.CaptureException(err)
  return err
}
```

There should be an additional API for one that captures the error then returns it:

```
if err != nil {
  return sentry.CaptureThenReturn(err)
}
```

Which is equivalent to above. It can even support format strings for an alt to fmt.Errorf().

**Comment by aldy505** [comment]
I like this approach. Do you want to open a PR for this? @assembly-winston 

The usage should also support this kind:
```go
sentry.GetHubFromContext(ctx).CaptureThenReturn(err)
```

**Comment by cleptric** [comment]
This can be added in userland. We historically added too many of these helper methods that unnecessarily cluttered the API surface and I’m since being very reluctant to add such methods.
