### ISSUE TITLE
"Missing Trace Root" on v0.29

### ISSUE THREAD

**Issue by Cyberax** [getsentry/sentry-go#884]
## Summary
Upgrade to v0.29 results in "Missing Trace Root" traces. Downgrade to 0.28.1 resolves the issue.

## Steps To Reproduce

Use the Go OTEL sample

```go
	sp := sentryotel.NewSentrySpanProcessor()
	tracerProvider := sdktrace.NewTracerProvider(
		sdktrace.WithResource(serviceResource),
		sdktrace.WithSpanProcessor(sp),
	)
```

## Expected Behavior
The trace root should be correct.

## Screenshots
![Image](https://github.com/user-attachments/assets/b033bf69-4ffd-4057-b03a-a31555dc6e45)

### SDK
 - `sentry-go` version: v0.29
 - Go version: 1.22
 - Using Go Modules? yes

### Sentry
 - Using hosted Sentry in sentry.io? yes

**Comment by cleptric** [comment]
We'll take a look.

**Comment by cleptric** [comment]
This is currently to be expected. The reason is adding support to something we call "Tracing without performance", a way to connect errors from different services together without the need to emit traces. As the payload of each event now always contains a `parent_span_id`, the product now displays "Missing Trace Root". We'll make the changes in Sentry itself. I'll get back here once I have a rough timeline.

**Comment by radazen** [comment]
@cleptric I may be wrong, but it feels like there's still a bug here. Note the part of the original screenshot where two different spans in the same trace have the same `Span ID` (2e28b774). This is happening to me as well! My top-level transaction span is what I'd expect to see as the Trace Root, and if I record a trace with a single span and no children, that's exactly what happens: I see a proper trace root, not a `Missing Trace Root`.

But if I record any child spans, the root transaction span ends up having its original `Span ID` overwritten by the span ID of one of the child spans, and I end up with two spans with the same `Span ID` and a `Missing Trace Root`.

**Comment by cleptric** [comment]
Yes, I was able to reproduce this and will look into a fix. Thanks @radazen for calling this out!

**Comment by bububa** [comment]
Same problem, really annoying on self host

**Comment by ribice** [comment]
@Cyberax / @radazen I was able to reproduce this as well using the tracing without performance, but downgrading to 0.28.1 lacks this feature, so I have to pull some commits in.

Could you share a reproducible snippet?

**Comment by cleptric** [comment]
A fix has been shipped with https://github.com/getsentry/sentry-go/releases/tag/v0.29.1
