### ISSUE TITLE
Event ingestion: Mechanism.Type is missing

### ISSUE THREAD

**Issue by ioxenus** [getsentry/sentry-go#896]
In Sentry's docs on [event payloads - exception mechanism](https://develop.sentry.dev/sdk/data-model/event-payloads/exception/#exception-mechanism) it says that the "type" attribute is required.

However, sentry-go v0.29.1 sometimes sends an event that has mechanism included, but the type is [omitted](https://github.com/getsentry/sentry-go/blob/6bd150ff66a7a888c70f8d6bc9233a73abe71d88/interfaces.go#L403-L412).

Reproduction:

```
mkdir issue350
cd issue350
go mod init issue350
go get github.com/getsentry/sentry-go@v0.29.1
touch test.txt
chmod 407 test.txt
```

`main.go`:
```go
package main

import (
	"os"
	"time"

	sentry "github.com/getsentry/sentry-go"
)

func main() {
	sentry.Init(sentry.ClientOptions{
		Dsn:              "https://foo@bar.baz/1",
		Debug:            true,
	})

	defer func() {
		if err := recover(); err != nil {
			sentry.CurrentHub().Recover(err)
			sentry.Flush(time.Second * 5)
		}
	}()

	if err := os.WriteFile("test.txt", []byte("foobar"), 0666); err != nil {
		panic(err)
	}
}
```

It yields such a JSON payload:
```
"exception": [
    {
        "type": "syscall.Errno",
        "value": "permission denied",
        "mechanism":{
            "exception_id": 0, 
            "is_exception_group": true
        }
    },
    {
        "type":"*fs.PathError",
        "value":"open test.txt: permission denied",
        "stacktrace": ...
        ...
    }
]
```

Maybe it'd be better to remove `json:"type,omitempty"` from [Mechanism.Type](https://github.com/getsentry/sentry-go/blame/6bd150ff66a7a888c70f8d6bc9233a73abe71d88/interfaces.go#L227)?

————

I solved that myself by adding such a `BeforeSend` to `sentry.ClientOptions`:
```
sentry_err := sentry.Init(sentry.ClientOptions{
	Dsn: "https://foo@bar.baz/1",
	Debug: true,

	BeforeSend: func(event *sentry.Event, hint *sentry.EventHint) *sentry.Event {
		for _, x := range event.Exception {
			if x.Mechanism != nil && x.Mechanism.Type == "" {
				x.Mechanism.Type = "foobar"
			}
		}
		return event
	},
})
```

(can also be done with `sentry.ConfigureScope` and `scope.AddEventProcessor`)

**Comment by ribice** [comment]
You are right, this Type is never set. Currently `IsExceptionGroup`, `ExceptionID` and `ParentID` are used in Mechanism. I'll see what can we set for Type.

**Comment by ribice** [comment]
@cleptric I inspected other SDKs for this - for example in the javascript one it either sets this type as ([generic](https://github.com/getsentry/sentry-javascript/blob/e0820cf2896312d2c4d5d26fdc29e153650a7dbd/dev-packages/e2e-tests/test-applications/nextjs-13/tests/server/getServerSideProps.test.ts#L26)), [angular](https://github.com/getsentry/sentry-javascript/blob/e0820cf2896312d2c4d5d26fdc29e153650a7dbd/packages/angular/test/errorhandler.test.ts#L80), [cloudflare](https://github.dev/getsentry/sentry-javascript/blob/e0820cf2896312d2c4d5d26fdc29e153650a7dbd/packages/cloudflare/test/request.test.ts#L168).

The easiest way to resolve it would be to set it to `generic`, or copy the same Type from Exception (which may serve no purpose, but might be better than generic?).

**Comment by cleptric** [comment]
Just using `generic` is fine.
