### ISSUE TITLE
Any cgo crash capture support?

### ISSUE THREAD

**Issue by foobra** [getsentry/sentry-go#899]
## Summary
I want to capture cgo crash with sentry-go

Or How can I use sentry-go and sentry-native togather to capture native crash?

**Comment by cleptric** [comment]
We currently have no plans for this.

**Comment by cleptric** [comment]
We took a look but it's currently not worth the amount of work required to integrate the [native SDK](https://github.com/getsentry/sentry-native) with the Go SDK.
