### ISSUE TITLE
How do we check if sentry has been previously initialized?

### ISSUE THREAD

**Issue by mattcollum** [getsentry/sentry-go#9]
What series of calls could be used to determine if Sentry had been previously initialized?

**Comment by kamilogorek** [comment]
We don't expose a direct `IsInitialized` method or something similar, but if your Hub (what's hub? https://docs.sentry.io/enriching-error-data/scopes/ ) has a SDK Client bound, then you can be sure it's ready to go.

```go
if sentry.CurrentHub().Client() != nil {
  fmt.Println("Sentry was not yet initialized, or Client was somehow dropped, so it's not ready to go")
} else {
  fmt.Println("Sentry was initialized and ready to go")
}
```

Cheers!

**Comment by jnelken** [comment]
For anyone who stumbles across this solution, the API has changed:
```
// old
 sentry.CurrentHub().Client()
// new
Sentry.getCurrentHub().getClient()
````

**Comment by kamilogorek** [comment]
@jnelken that's not correct. You quoted JS SDK Api. In Go it's still `CurrentHub()` :)

**Comment by B3rs** [comment]
Hi everybody, is this method still valid?
Also, is `!= nil` the correct condition to check? shouldn't it be `== nil`?

**Comment by kamilogorek** [comment]
It is. `sentry.CurrentHub().Client()` is still working API.
And yes, its `nil` if there was no initialization, my bad. Updated the comment.
