### ISSUE TITLE
Setting Logger Name

### ISSUE THREAD

**Issue by petersng** [getsentry/sentry-go#90]
Hi, I am trying to migrate from the old `raven` client and using that client, one could call `SetDefaultLoggerName ` to set the logger name for the event.  It's possible I am missing something, but I can't seem to find a way to set this value in the `sentry-go`. Is this currently possible?  

We use this functionality to make it easier to discern events from different components in our code.  If it is currently not possible, any suggestions for a similar solution would be much appreciated.

**Comment by rhcarvalho** [comment]
Hi @petersng! Thanks for trying out the new SDK.

In the new SDK you can set the logger name by setting a field in the [`Event`](https://godoc.org/github.com/getsentry/sentry-go#Event) type.

You might find it useful to use a [BeforeSend](https://godoc.org/github.com/getsentry/sentry-go#ClientOptions) function to automatically set the `Event.Logger` value for all events in a certain scope.

Here's an example adapted from the docs in https://docs.sentry.io/error-reporting/configuration/filtering/?platform=go:

```go
sentry.Init(sentry.ClientOptions{
	BeforeSend: func(event *sentry.Event, hint *sentry.EventHint) *sentry.Event {
		// Modify the event here
		if event.Logger == "" {
			event.Logger = "logger-name"
		}
		return event
	},
})
```

@petersng does that work for you?

**Comment by petersng** [comment]
Great, thanks for the suggestion, I think that will work for me.

**Comment by rhcarvalho** [comment]
@petersng I'm closing this then. We're always happy to hear feedback on the new SDK! Thank you!
