### ISSUE TITLE
Panic in fasthttp handler

### ISSUE THREAD

**Issue by ainar-g** [getsentry/sentry-go#911]
## Summary

The fasthttp integration can panic when converting a fasthttp context into an `*http.Request`.

## Steps To Reproduce

If the URL parsing fails at
https://github.com/getsentry/sentry-go/blob/24ffea568912a2e729f80c388be5400c67f698de/fasthttp/sentryfasthttp.go#L151

this panics,
https://github.com/getsentry/sentry-go/blob/24ffea568912a2e729f80c388be5400c67f698de/fasthttp/sentryfasthttp.go#L170

and while that panic is caught,
https://github.com/getsentry/sentry-go/blob/24ffea568912a2e729f80c388be5400c67f698de/fasthttp/sentryfasthttp.go#L140-L144

that means that this line panics now, since `r` is now nil.
https://github.com/getsentry/sentry-go/blob/24ffea568912a2e729f80c388be5400c67f698de/fasthttp/sentryfasthttp.go#L73

## Expected Behavior
No panics.

## Screenshots

\[not applicable\]

## Sentry.io Event
\[not applicable\]

### SDK
 - `sentry-go` version: v0.29.1
 - Go version: Go 1.23.3
 - Using Go Modules? yes

### Sentry
\[not applicable\]

## Additional context
The solution is to either always return a non-nil request from `convert` or not expect that r is always non-nil in `Handle`.

**Comment by cleptric** [comment]
A fix was released in version [0.30.0](https://github.com/getsentry/sentry-go/releases/tag/v0.30.0).
