### ISSUE TITLE
Support custom package in shouldSkipFrame

### ISSUE THREAD

**Issue by LesDomen** [getsentry/sentry-go#932]
### Problem Statement

We want to wrap sentry.CaptureException(err error) with some additional logic, while reporting the error at the call location of the wrapped function.

It seems that currently only frames from `runtime`, `testing` and `github.com/getsentry/sentry-go` modules are skipped. 

### Solution Brainstorm

Add a option to sentry.Init, to specify skipped suffixes/prefixes/modules. I'm wary of implementing such a solution, because of a [TODO](https://github.com/getsentry/sentry-go/blob/3a08424cafd4f1c683f7cd0ca51beb3749607db3/stacktrace.go#L312).

**Comment by cleptric** [comment]
Have a look at https://github.com/getsentry/sentry-go/issues/38#issuecomment-515959896.
While this issue is about skipping n frames, the solution would also fir your use-case.
