### ISSUE TITLE
why the process of sending event is single threaded(goroutine) ?

### ISSUE THREAD

**Issue by armagg** [getsentry/sentry-go#933]
### Problem Statement

I see in the code base that all of events send to a single channel and that process with a single goroutine. 
Is there any reason for that? if our code want to send a lot of events, most of them drop but we want to have track of all of them. 

### Solution Brainstorm

We can add another custom transport type to handle event with more workers.

**Comment by armagg** [comment]
do you accept if I make a PR for that?

**Comment by cleptric** [comment]
Most likely not, as I fail to see the issue at hand. Potentially, there might be cases were an error event could be dropped due to the queue being full. If you have indeed such high throughput, it's more likely that you'll get rate-limited server side, so all events get's dropped anyways.
