### ISSUE TITLE
Change a fuctory func to return a concrete struct instead of `slog.Handler` interface

### ISSUE THREAD

**Issue by MatsuoTakuro** [getsentry/sentry-go#937]
### Problem Statement

Currently, `NewSentryHandler` returns the `slog.Handler` interface:  
```go
func (o Option) NewSentryHandler() slog.Handler
```  
This limits access to methods and fields in the `SentryHandler` struct without type assertions.  

### Solution Brainstorm

Change the return type to the concrete struct:  
```go
func (o Option) NewSentryHandler() *SentryHandler
```  
This improves usability, matches Go's standard library (e.g., `NewJSONHandler`), and avoids unnecessary type assertions.

**Comment by ribice** [comment]
Which fields and methods you need to access from SentryHandler that are not available via slog.Handler interface, since there are none?

```go
type Handler interface {
	Enabled(context.Context, Level) bool
	Handle(context.Context, Record) error
	WithAttrs(attrs []Attr) Handler
	WithGroup(name string) Handler
}
```

**Comment by MatsuoTakuro** [comment]
@ribice 
After giving it more thought, I think this issue is fine to close.  

It seems unlikely that `SentryHandler` will need to expose any additional public methods beyond the `slog.Handler` interface in the future. Returning `slog.Handler` directly should be sufficient.  

The main reason I initially thought about returning the concrete `*SentryHandler` was for cases like this example, where I wanted to implement an extended logger combining `*slog.Logger` (e.g., JSON handler) with Sentry capturing. In this scenario, having the `capturer` field as `*sentryslog.SentryHandler` instead of `slog.Handler` felt slightly clearer. But, honestly, it’s not a big deal.  

```go
type Logger struct {
	logger    *slog.Logger
	captureOn bool
	capturer  slog.Handler // actually this is sentryslog.SentryHandler
}
```

That said, this example could also be handled using type assertions, so returning the interface doesn’t seem to cause any major issues after all.  

---
I’d appreciate it if you could also take a look at this new issue: 
#940 

Thanks for your time and response.
