### ISSUE TITLE
No LastEventID provided

### ISSUE THREAD

**Issue by oott123** [getsentry/sentry-go#98]
I'm trying to get the last event id using `sentry.LastEventID()` api, but i got nothing. `hub.LastEventID()` don't work either.

Use the following code to get last event id:

```go
func main() {
	sentry.Init(sentry.ClientOptions{})

	id1 := sentry.CaptureException(errors.New("my error"))
	id2 := sentry.LastEventID()

	fmt.Printf("1: %s 2:%s\n", string(*id1), string(id2))
}
```

expect:
```
1: 706aceab39e1479f98a36a763ca268a3 2: 706aceab39e1479f98a36a763ca268a3
```

but got:
```
1: 706aceab39e1479f98a36a763ca268a3 2:
```

playgroud that can reproduce this: https://play.golang.org/p/Sw5TOo0Dvj1

**Comment by rhcarvalho** [comment]
Hi @oott123! Could you please elaborate more on your use case?

Why don't you simply use `id1` as returned from `sentry.CaptureException`?

**Comment by oott123** [comment]
@rhcarvalho I'm using sentrygin middleware to handle panics. It works fine, but it doesn't save eventId for later use. I want to get the last event id from the hub.

And:

1. All (or almost all) other language implementations of sentry do have `LastEventID` method provided.
2. Although global `sentry.LastEventID` is not very useful in concurrent code, `hub.LastEventID` is useful.

**Comment by rhcarvalho** [comment]
Hi @oott123 thanks for describing what you are trying to achieve.

You are absolutely right about `LastEventID()` being present in other language SDKs.

Other languages also have a different concurrency model. I've been exploring how we can make `sentry-go` familiar for users coming from other languages, while still having an idiomatic SDK that fits the Go ecosystem. Your feedback is very important.

Would you be so kind and tell me one more thing, what kind of operation do you indent to do with the `eventID` you'd retrieve from `hub.LastEventID()`?

If possible, could you share a snippet of code too?

Thank you!

**Comment by oott123** [comment]
Hi @rhcarvalho , I just want the eventID and then display to the end user when something happend, and then they can send it to us, and we can then paste that into the searchbox, to dig deeper into the details. Like:

```go
r := gin.New()

r.Use(func() gin.HandlerFunc {
	return func(c *gin.Context) {
		defer func() {
// this middleware execute later than sentrygin report event, and I want that event id here
			r := recover()

			if hub := sentrygin.GetHubFromContext(c); hub != nil {
				c.Header("X-Sentry-Event-ID", hub.LastEventID()) // like, just add it to response header, and front end apps will read it
			}

			panic(r)
		}()
	}
})

// panic recovers here, which event has been reported to sentry
r.Use(sentrygin.New(sentrygin.Options{
	Repanic: true,
}))
```

I should say the code above is not real code, just some pesudo examples to describe what i want to do.
